//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.WcfService.PriMiddleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PriMiddleService.IMemberInfoService")]
    public interface IMemberInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberInfo", ReplyAction="http://tempuri.org/IMemberInfoService/MemberInfoResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoResult MemberInfo(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberInfo", ReplyAction="http://tempuri.org/IMemberInfoService/MemberInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoResult> MemberInfoAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberInfoGeneral", ReplyAction="http://tempuri.org/IMemberInfoService/MemberInfoGeneralResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoGeneralResult MemberInfoGeneral(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberInfoGeneral", ReplyAction="http://tempuri.org/IMemberInfoService/MemberInfoGeneralResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoGeneralResult> MemberInfoGeneralAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberInfoCompany", ReplyAction="http://tempuri.org/IMemberInfoService/MemberInfoCompanyResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoCompanyResult MemberInfoCompany(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberInfoCompany", ReplyAction="http://tempuri.org/IMemberInfoService/MemberInfoCompanyResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoCompanyResult> MemberInfoCompanyAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/PasswordValidation", ReplyAction="http://tempuri.org/IMemberInfoService/PasswordValidationResponse")]
        bool PasswordValidation(int userNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/PasswordValidation", ReplyAction="http://tempuri.org/IMemberInfoService/PasswordValidationResponse")]
        System.Threading.Tasks.Task<bool> PasswordValidationAsync(int userNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/IsNickNameDuplicated", ReplyAction="http://tempuri.org/IMemberInfoService/IsNickNameDuplicatedResponse")]
        int IsNickNameDuplicated(string nickName, int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/IsNickNameDuplicated", ReplyAction="http://tempuri.org/IMemberInfoService/IsNickNameDuplicatedResponse")]
        System.Threading.Tasks.Task<int> IsNickNameDuplicatedAsync(string nickName, int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberSaveGeneral", ReplyAction="http://tempuri.org/IMemberInfoService/MemberSaveGeneralResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserResult MemberSaveGeneral(Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserRequestGeneral request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberSaveGeneral", ReplyAction="http://tempuri.org/IMemberInfoService/MemberSaveGeneralResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserResult> MemberSaveGeneralAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserRequestGeneral request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberSaveCompany", ReplyAction="http://tempuri.org/IMemberInfoService/MemberSaveCompanyResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserResult MemberSaveCompany(Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserRequestCompany request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberSaveCompany", ReplyAction="http://tempuri.org/IMemberInfoService/MemberSaveCompanyResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserResult> MemberSaveCompanyAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserRequestCompany request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberNameChange", ReplyAction="http://tempuri.org/IMemberInfoService/MemberNameChangeResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.NameChangeResult MemberNameChange(int userNumber, string requestNo, string encryptedData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberNameChange", ReplyAction="http://tempuri.org/IMemberInfoService/MemberNameChangeResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.NameChangeResult> MemberNameChangeAsync(int userNumber, string requestNo, string encryptedData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetKakaoUserInfoExists", ReplyAction="http://tempuri.org/IMemberInfoService/GetKakaoUserInfoExistsResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSKakao GetKakaoUserInfoExists(System.Nullable<int> userNumber, long kakaoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetKakaoUserInfoExists", ReplyAction="http://tempuri.org/IMemberInfoService/GetKakaoUserInfoExistsResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSKakao> GetKakaoUserInfoExistsAsync(System.Nullable<int> userNumber, long kakaoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetFacebookUserInfoExists", ReplyAction="http://tempuri.org/IMemberInfoService/GetFacebookUserInfoExistsResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSFacebook GetFacebookUserInfoExists(System.Nullable<int> userNumber, long facebookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetFacebookUserInfoExists", ReplyAction="http://tempuri.org/IMemberInfoService/GetFacebookUserInfoExistsResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSFacebook> GetFacebookUserInfoExistsAsync(System.Nullable<int> userNumber, long facebookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetNaverUserInfoExists", ReplyAction="http://tempuri.org/IMemberInfoService/GetNaverUserInfoExistsResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSNaver GetNaverUserInfoExists(System.Nullable<int> userNumber, long naverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetNaverUserInfoExists", ReplyAction="http://tempuri.org/IMemberInfoService/GetNaverUserInfoExistsResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSNaver> GetNaverUserInfoExistsAsync(System.Nullable<int> userNumber, long naverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetKakaoUserInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetKakaoUserInfoResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSKakao GetKakaoUserInfo(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetKakaoUserInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetKakaoUserInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSKakao> GetKakaoUserInfoAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetFacebookUserInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetFacebookUserInfoResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSFacebook GetFacebookUserInfo(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetFacebookUserInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetFacebookUserInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSFacebook> GetFacebookUserInfoAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetNaverUserInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetNaverUserInfoResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSNaver GetNaverUserInfo(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetNaverUserInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetNaverUserInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSNaver> GetNaverUserInfoAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberPasswordChange", ReplyAction="http://tempuri.org/IMemberInfoService/MemberPasswordChangeResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.PasswordChangeResult MemberPasswordChange(int userNumber, string passwordOriginal, string passwordNew, string passwordConfirm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberPasswordChange", ReplyAction="http://tempuri.org/IMemberInfoService/MemberPasswordChangeResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.PasswordChangeResult> MemberPasswordChangeAsync(int userNumber, string passwordOriginal, string passwordNew, string passwordConfirm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberPasswordDelay", ReplyAction="http://tempuri.org/IMemberInfoService/MemberPasswordDelayResponse")]
        void MemberPasswordDelay(int userNumber, System.DateTime alarmDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberPasswordDelay", ReplyAction="http://tempuri.org/IMemberInfoService/MemberPasswordDelayResponse")]
        System.Threading.Tasks.Task MemberPasswordDelayAsync(int userNumber, System.DateTime alarmDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberAgreementOption2Change", ReplyAction="http://tempuri.org/IMemberInfoService/MemberAgreementOption2ChangeResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.AgreementOption2ChangeResult MemberAgreementOption2Change(int userNumber, string option2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberAgreementOption2Change", ReplyAction="http://tempuri.org/IMemberInfoService/MemberAgreementOption2ChangeResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.AgreementOption2ChangeResult> MemberAgreementOption2ChangeAsync(int userNumber, string option2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberSecessionCheck", ReplyAction="http://tempuri.org/IMemberInfoService/MemberSecessionCheckResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionCheckResult MemberSecessionCheck(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberSecessionCheck", ReplyAction="http://tempuri.org/IMemberInfoService/MemberSecessionCheckResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionCheckResult> MemberSecessionCheckAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberSecession", ReplyAction="http://tempuri.org/IMemberInfoService/MemberSecessionResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionResult MemberSecession(int userNumber, string secessionReasonKey, string secessionReasonDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/MemberSecession", ReplyAction="http://tempuri.org/IMemberInfoService/MemberSecessionResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionResult> MemberSecessionAsync(int userNumber, string secessionReasonKey, string secessionReasonDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/PasswordConfirm", ReplyAction="http://tempuri.org/IMemberInfoService/PasswordConfirmResponse")]
        bool PasswordConfirm(int userNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/PasswordConfirm", ReplyAction="http://tempuri.org/IMemberInfoService/PasswordConfirmResponse")]
        System.Threading.Tasks.Task<bool> PasswordConfirmAsync(int userNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetMemberGrade", ReplyAction="http://tempuri.org/IMemberInfoService/GetMemberGradeResponse")]
        Wow.Tv.Middle.Biz.Member.MemberGradeModel GetMemberGrade(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetMemberGrade", ReplyAction="http://tempuri.org/IMemberInfoService/GetMemberGradeResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Biz.Member.MemberGradeModel> GetMemberGradeAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetTvReplayAuthorityInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetTvReplayAuthorityInfoResponse")]
        Wow.Tv.Middle.Biz.Member.TvReplayAuthorityInfoModel GetTvReplayAuthorityInfo(int userNumber, int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetTvReplayAuthorityInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetTvReplayAuthorityInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Biz.Member.TvReplayAuthorityInfoModel> GetTvReplayAuthorityInfoAsync(int userNumber, int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/TvReplayPaymentByPoint", ReplyAction="http://tempuri.org/IMemberInfoService/TvReplayPaymentByPointResponse")]
        Wow.Tv.Middle.Biz.Member.TvReplayPaymentByPointModel TvReplayPaymentByPoint(int userNumber, int num, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/TvReplayPaymentByPoint", ReplyAction="http://tempuri.org/IMemberInfoService/TvReplayPaymentByPointResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Biz.Member.TvReplayPaymentByPointModel> TvReplayPaymentByPointAsync(int userNumber, int num, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetMemberInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetMemberInfoResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.tblUser GetMemberInfo(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetMemberInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetMemberInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUser> GetMemberInfoAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetDormancyMemberInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetDormancyMemberInfoResponse")]
        Wow.Tv.Middle.Model.Db89.Sleep_wowbill.bak_tblUser GetDormancyMemberInfo(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetDormancyMemberInfo", ReplyAction="http://tempuri.org/IMemberInfoService/GetDormancyMemberInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.Sleep_wowbill.bak_tblUser> GetDormancyMemberInfoAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetUserDetail", ReplyAction="http://tempuri.org/IMemberInfoService/GetUserDetailResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.tblUserDetail GetUserDetail(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetUserDetail", ReplyAction="http://tempuri.org/IMemberInfoService/GetUserDetailResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserDetail> GetUserDetailAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetUserSMS", ReplyAction="http://tempuri.org/IMemberInfoService/GetUserSMSResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.tblUserSMS GetUserSMS(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/GetUserSMS", ReplyAction="http://tempuri.org/IMemberInfoService/GetUserSMSResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSMS> GetUserSMSAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/UserIdExists", ReplyAction="http://tempuri.org/IMemberInfoService/UserIdExistsResponse")]
        bool UserIdExists(string userId, bool onlyApplied);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/UserIdExists", ReplyAction="http://tempuri.org/IMemberInfoService/UserIdExistsResponse")]
        System.Threading.Tasks.Task<bool> UserIdExistsAsync(string userId, bool onlyApplied);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/ChangeSmsAdAggrement", ReplyAction="http://tempuri.org/IMemberInfoService/ChangeSmsAdAggrementResponse")]
        void ChangeSmsAdAggrement(int userNumber, string smsAd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberInfoService/ChangeSmsAdAggrement", ReplyAction="http://tempuri.org/IMemberInfoService/ChangeSmsAdAggrementResponse")]
        System.Threading.Tasks.Task ChangeSmsAdAggrementAsync(int userNumber, string smsAd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemberInfoServiceChannel : Wow.Tv.Middle.WcfService.PriMiddleService.IMemberInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberInfoServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Middle.WcfService.PriMiddleService.IMemberInfoService>, Wow.Tv.Middle.WcfService.PriMiddleService.IMemberInfoService {
        
        public MemberInfoServiceClient() {
        }
        
        public MemberInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoResult MemberInfo(int userNumber) {
            return base.Channel.MemberInfo(userNumber);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoResult> MemberInfoAsync(int userNumber) {
            return base.Channel.MemberInfoAsync(userNumber);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoGeneralResult MemberInfoGeneral(int userNumber) {
            return base.Channel.MemberInfoGeneral(userNumber);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoGeneralResult> MemberInfoGeneralAsync(int userNumber) {
            return base.Channel.MemberInfoGeneralAsync(userNumber);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoCompanyResult MemberInfoCompany(int userNumber) {
            return base.Channel.MemberInfoCompany(userNumber);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberInfoCompanyResult> MemberInfoCompanyAsync(int userNumber) {
            return base.Channel.MemberInfoCompanyAsync(userNumber);
        }
        
        public bool PasswordValidation(int userNumber, string password) {
            return base.Channel.PasswordValidation(userNumber, password);
        }
        
        public System.Threading.Tasks.Task<bool> PasswordValidationAsync(int userNumber, string password) {
            return base.Channel.PasswordValidationAsync(userNumber, password);
        }
        
        public int IsNickNameDuplicated(string nickName, int userNumber) {
            return base.Channel.IsNickNameDuplicated(nickName, userNumber);
        }
        
        public System.Threading.Tasks.Task<int> IsNickNameDuplicatedAsync(string nickName, int userNumber) {
            return base.Channel.IsNickNameDuplicatedAsync(nickName, userNumber);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserResult MemberSaveGeneral(Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserRequestGeneral request) {
            return base.Channel.MemberSaveGeneral(request);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserResult> MemberSaveGeneralAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserRequestGeneral request) {
            return base.Channel.MemberSaveGeneralAsync(request);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserResult MemberSaveCompany(Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserRequestCompany request) {
            return base.Channel.MemberSaveCompany(request);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserResult> MemberSaveCompanyAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.SaveUserRequestCompany request) {
            return base.Channel.MemberSaveCompanyAsync(request);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.NameChangeResult MemberNameChange(int userNumber, string requestNo, string encryptedData) {
            return base.Channel.MemberNameChange(userNumber, requestNo, encryptedData);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.NameChangeResult> MemberNameChangeAsync(int userNumber, string requestNo, string encryptedData) {
            return base.Channel.MemberNameChangeAsync(userNumber, requestNo, encryptedData);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSKakao GetKakaoUserInfoExists(System.Nullable<int> userNumber, long kakaoId) {
            return base.Channel.GetKakaoUserInfoExists(userNumber, kakaoId);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSKakao> GetKakaoUserInfoExistsAsync(System.Nullable<int> userNumber, long kakaoId) {
            return base.Channel.GetKakaoUserInfoExistsAsync(userNumber, kakaoId);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSFacebook GetFacebookUserInfoExists(System.Nullable<int> userNumber, long facebookId) {
            return base.Channel.GetFacebookUserInfoExists(userNumber, facebookId);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSFacebook> GetFacebookUserInfoExistsAsync(System.Nullable<int> userNumber, long facebookId) {
            return base.Channel.GetFacebookUserInfoExistsAsync(userNumber, facebookId);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSNaver GetNaverUserInfoExists(System.Nullable<int> userNumber, long naverId) {
            return base.Channel.GetNaverUserInfoExists(userNumber, naverId);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSNaver> GetNaverUserInfoExistsAsync(System.Nullable<int> userNumber, long naverId) {
            return base.Channel.GetNaverUserInfoExistsAsync(userNumber, naverId);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSKakao GetKakaoUserInfo(int userNumber) {
            return base.Channel.GetKakaoUserInfo(userNumber);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSKakao> GetKakaoUserInfoAsync(int userNumber) {
            return base.Channel.GetKakaoUserInfoAsync(userNumber);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSFacebook GetFacebookUserInfo(int userNumber) {
            return base.Channel.GetFacebookUserInfo(userNumber);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSFacebook> GetFacebookUserInfoAsync(int userNumber) {
            return base.Channel.GetFacebookUserInfoAsync(userNumber);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSNaver GetNaverUserInfo(int userNumber) {
            return base.Channel.GetNaverUserInfo(userNumber);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSNSNaver> GetNaverUserInfoAsync(int userNumber) {
            return base.Channel.GetNaverUserInfoAsync(userNumber);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.PasswordChangeResult MemberPasswordChange(int userNumber, string passwordOriginal, string passwordNew, string passwordConfirm) {
            return base.Channel.MemberPasswordChange(userNumber, passwordOriginal, passwordNew, passwordConfirm);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.PasswordChangeResult> MemberPasswordChangeAsync(int userNumber, string passwordOriginal, string passwordNew, string passwordConfirm) {
            return base.Channel.MemberPasswordChangeAsync(userNumber, passwordOriginal, passwordNew, passwordConfirm);
        }
        
        public void MemberPasswordDelay(int userNumber, System.DateTime alarmDate) {
            base.Channel.MemberPasswordDelay(userNumber, alarmDate);
        }
        
        public System.Threading.Tasks.Task MemberPasswordDelayAsync(int userNumber, System.DateTime alarmDate) {
            return base.Channel.MemberPasswordDelayAsync(userNumber, alarmDate);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.AgreementOption2ChangeResult MemberAgreementOption2Change(int userNumber, string option2) {
            return base.Channel.MemberAgreementOption2Change(userNumber, option2);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.AgreementOption2ChangeResult> MemberAgreementOption2ChangeAsync(int userNumber, string option2) {
            return base.Channel.MemberAgreementOption2ChangeAsync(userNumber, option2);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionCheckResult MemberSecessionCheck(int userNumber) {
            return base.Channel.MemberSecessionCheck(userNumber);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionCheckResult> MemberSecessionCheckAsync(int userNumber) {
            return base.Channel.MemberSecessionCheckAsync(userNumber);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionResult MemberSecession(int userNumber, string secessionReasonKey, string secessionReasonDescription) {
            return base.Channel.MemberSecession(userNumber, secessionReasonKey, secessionReasonDescription);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionResult> MemberSecessionAsync(int userNumber, string secessionReasonKey, string secessionReasonDescription) {
            return base.Channel.MemberSecessionAsync(userNumber, secessionReasonKey, secessionReasonDescription);
        }
        
        public bool PasswordConfirm(int userNumber, string password) {
            return base.Channel.PasswordConfirm(userNumber, password);
        }
        
        public System.Threading.Tasks.Task<bool> PasswordConfirmAsync(int userNumber, string password) {
            return base.Channel.PasswordConfirmAsync(userNumber, password);
        }
        
        public Wow.Tv.Middle.Biz.Member.MemberGradeModel GetMemberGrade(int userNumber) {
            return base.Channel.GetMemberGrade(userNumber);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Biz.Member.MemberGradeModel> GetMemberGradeAsync(int userNumber) {
            return base.Channel.GetMemberGradeAsync(userNumber);
        }
        
        public Wow.Tv.Middle.Biz.Member.TvReplayAuthorityInfoModel GetTvReplayAuthorityInfo(int userNumber, int num) {
            return base.Channel.GetTvReplayAuthorityInfo(userNumber, num);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Biz.Member.TvReplayAuthorityInfoModel> GetTvReplayAuthorityInfoAsync(int userNumber, int num) {
            return base.Channel.GetTvReplayAuthorityInfoAsync(userNumber, num);
        }
        
        public Wow.Tv.Middle.Biz.Member.TvReplayPaymentByPointModel TvReplayPaymentByPoint(int userNumber, int num, string ipAddress) {
            return base.Channel.TvReplayPaymentByPoint(userNumber, num, ipAddress);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Biz.Member.TvReplayPaymentByPointModel> TvReplayPaymentByPointAsync(int userNumber, int num, string ipAddress) {
            return base.Channel.TvReplayPaymentByPointAsync(userNumber, num, ipAddress);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.tblUser GetMemberInfo(string userId) {
            return base.Channel.GetMemberInfo(userId);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUser> GetMemberInfoAsync(string userId) {
            return base.Channel.GetMemberInfoAsync(userId);
        }
        
        public Wow.Tv.Middle.Model.Db89.Sleep_wowbill.bak_tblUser GetDormancyMemberInfo(string userId) {
            return base.Channel.GetDormancyMemberInfo(userId);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.Sleep_wowbill.bak_tblUser> GetDormancyMemberInfoAsync(string userId) {
            return base.Channel.GetDormancyMemberInfoAsync(userId);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.tblUserDetail GetUserDetail(int userNumber) {
            return base.Channel.GetUserDetail(userNumber);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserDetail> GetUserDetailAsync(int userNumber) {
            return base.Channel.GetUserDetailAsync(userNumber);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.tblUserSMS GetUserSMS(int userNumber) {
            return base.Channel.GetUserSMS(userNumber);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblUserSMS> GetUserSMSAsync(int userNumber) {
            return base.Channel.GetUserSMSAsync(userNumber);
        }
        
        public bool UserIdExists(string userId, bool onlyApplied) {
            return base.Channel.UserIdExists(userId, onlyApplied);
        }
        
        public System.Threading.Tasks.Task<bool> UserIdExistsAsync(string userId, bool onlyApplied) {
            return base.Channel.UserIdExistsAsync(userId, onlyApplied);
        }
        
        public void ChangeSmsAdAggrement(int userNumber, string smsAd) {
            base.Channel.ChangeSmsAdAggrement(userNumber, smsAd);
        }
        
        public System.Threading.Tasks.Task ChangeSmsAdAggrementAsync(int userNumber, string smsAd) {
            return base.Channel.ChangeSmsAdAggrementAsync(userNumber, smsAd);
        }
    }
}
