//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.editVOD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db49_editVOD : DbContext
    {
        public Db49_editVOD()
            : base("name=Db49_editVOD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAB_PGM_CMS_AUTH> TAB_PGM_CMS_AUTH { get; set; }
        public virtual DbSet<tblSubConerList> tblSubConerList { get; set; }
        public virtual DbSet<tblCategoryList> tblCategoryList { get; set; }
        public virtual DbSet<tblStockClass> tblStockClass { get; set; }
        public virtual DbSet<tblVODEdit> tblVODEdit { get; set; }
        public virtual DbSet<tblVODList> tblVODList { get; set; }
    
        public virtual ObjectResult<usp_byStockCodeGetVOD_Result> usp_byStockCodeGetVOD(string stockcode, string stockcode2)
        {
            var stockcodeParameter = stockcode != null ?
                new ObjectParameter("stockcode", stockcode) :
                new ObjectParameter("stockcode", typeof(string));
    
            var stockcode2Parameter = stockcode2 != null ?
                new ObjectParameter("stockcode2", stockcode2) :
                new ObjectParameter("stockcode2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_byStockCodeGetVOD_Result>("Db49_editVOD.usp_byStockCodeGetVOD", stockcodeParameter, stockcode2Parameter);
        }
    
        public virtual ObjectResult<usp_GetCornerVODList_WEB_Result> usp_GetCornerVODList_WEB(string cnCode, string scCode, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var cnCodeParameter = cnCode != null ?
                new ObjectParameter("cnCode", cnCode) :
                new ObjectParameter("cnCode", typeof(string));
    
            var scCodeParameter = scCode != null ?
                new ObjectParameter("scCode", scCode) :
                new ObjectParameter("scCode", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCornerVODList_WEB_Result>("Db49_editVOD.usp_GetCornerVODList_WEB", cnCodeParameter, scCodeParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_GetCornerVODList_WEB_COUNT(string cnCode, string scCode, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var cnCodeParameter = cnCode != null ?
                new ObjectParameter("cnCode", cnCode) :
                new ObjectParameter("cnCode", typeof(string));
    
            var scCodeParameter = scCode != null ?
                new ObjectParameter("scCode", scCode) :
                new ObjectParameter("scCode", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Db49_editVOD.usp_GetCornerVODList_WEB_COUNT", cnCodeParameter, scCodeParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual ObjectResult<usp_web_vodTop6List_Result> usp_web_vodTop6List(string arjCode)
        {
            var arjCodeParameter = arjCode != null ?
                new ObjectParameter("ArjCode", arjCode) :
                new ObjectParameter("ArjCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_vodTop6List_Result>("Db49_editVOD.usp_web_vodTop6List", arjCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_listSubTopvod6_Result> usp_web_listSubTopvod6(string ctCode)
        {
            var ctCodeParameter = ctCode != null ?
                new ObjectParameter("ctCode", ctCode) :
                new ObjectParameter("ctCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_listSubTopvod6_Result>("Db49_editVOD.usp_web_listSubTopvod6", ctCodeParameter);
        }
    
        public virtual ObjectResult<NUP_GetCornerVODList_WEB_Result> NUP_GetCornerVODList_WEB(string cnCode, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var cnCodeParameter = cnCode != null ?
                new ObjectParameter("cnCode", cnCode) :
                new ObjectParameter("cnCode", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_GetCornerVODList_WEB_Result>("Db49_editVOD.NUP_GetCornerVODList_WEB", cnCodeParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual ObjectResult<usp_web_vodList_Result> usp_web_vodList(string arjCode)
        {
            var arjCodeParameter = arjCode != null ?
                new ObjectParameter("ArjCode", arjCode) :
                new ObjectParameter("ArjCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_vodList_Result>("Db49_editVOD.usp_web_vodList", arjCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getInvestVodList_Result> usp_web_getInvestVodList(string ctCode)
        {
            var ctCodeParameter = ctCode != null ?
                new ObjectParameter("ctCode", ctCode) :
                new ObjectParameter("ctCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getInvestVodList_Result>("Db49_editVOD.usp_web_getInvestVodList", ctCodeParameter);
        }
    }
}
