//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.editVOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVODList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVODList()
        {
            this.tblStockClass = new HashSet<tblStockClass>();
            this.tblCategoryList = new HashSet<tblCategoryList>();
        }
    
        public int vodNum { get; set; }
        public System.DateTime insDate { get; set; }
        public Nullable<System.DateTime> uptDate { get; set; }
        public string ArticleID { get; set; }
        public Nullable<int> vodListID { get; set; }
        public string Operator { get; set; }
        public string Subject { get; set; }
        public string Writer { get; set; }
        public string Email { get; set; }
        public string Content { get; set; }
        public int DelFlag { get; set; }
        public Nullable<int> ReadCnt { get; set; }
        public string IsMain { get; set; }
        public string ProgramName { get; set; }
        public string BroadcastDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockClass> tblStockClass { get; set; }
        public virtual tblVODEdit tblVODEdit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategoryList> tblCategoryList { get; set; }
    }
}
