//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db51.WOWMMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class mms_msg
    {
        public int MSGKEY { get; set; }
        public string SUBJECT { get; set; }
        public string PHONE { get; set; }
        public string CALLBACK { get; set; }
        public string STATUS { get; set; }
        public System.DateTime REQDATE { get; set; }
        public string MSG { get; set; }
        public int FILE_CNT { get; set; }
        public int FILE_CNT_REAL { get; set; }
        public string FILE_PATH1 { get; set; }
        public Nullable<int> FILE_PATH1_SIZ { get; set; }
        public string FILE_PATH2 { get; set; }
        public Nullable<int> FILE_PATH2_SIZ { get; set; }
        public string FILE_PATH3 { get; set; }
        public Nullable<int> FILE_PATH3_SIZ { get; set; }
        public string FILE_PATH4 { get; set; }
        public Nullable<int> FILE_PATH4_SIZ { get; set; }
        public string FILE_PATH5 { get; set; }
        public Nullable<int> FILE_PATH5_SIZ { get; set; }
        public string EXPIRETIME { get; set; }
        public Nullable<System.DateTime> SENTDATE { get; set; }
        public Nullable<System.DateTime> RSLTDATE { get; set; }
        public Nullable<System.DateTime> REPORTDATE { get; set; }
        public Nullable<System.DateTime> TERMINATEDDATE { get; set; }
        public string RSLT { get; set; }
        public Nullable<int> REPCNT { get; set; }
        public string TYPE { get; set; }
        public string TELCOINFO { get; set; }
        public string ID { get; set; }
        public string POST { get; set; }
        public string ETC1 { get; set; }
        public string ETC2 { get; set; }
        public string ETC3 { get; set; }
        public Nullable<int> ETC4 { get; set; }
    }
}
