//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db51.ARSConsult
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db51_ARSConsult : DbContext
    {
        public Db51_ARSConsult()
            : base("name=Db51_ARSConsult")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCallback> tblCallback { get; set; }
    
        public virtual ObjectResult<NUP_SC_LOG_SELECT_Result> NUP_SC_LOG_SELECT(string sEARCH_TYPE, Nullable<System.DateTime> sEARCH_DATE, string tR_PHONE, string tR_MSG, Nullable<int> i_PAGE, Nullable<int> i_PAGESIZE)
        {
            var sEARCH_TYPEParameter = sEARCH_TYPE != null ?
                new ObjectParameter("SEARCH_TYPE", sEARCH_TYPE) :
                new ObjectParameter("SEARCH_TYPE", typeof(string));
    
            var sEARCH_DATEParameter = sEARCH_DATE.HasValue ?
                new ObjectParameter("SEARCH_DATE", sEARCH_DATE) :
                new ObjectParameter("SEARCH_DATE", typeof(System.DateTime));
    
            var tR_PHONEParameter = tR_PHONE != null ?
                new ObjectParameter("TR_PHONE", tR_PHONE) :
                new ObjectParameter("TR_PHONE", typeof(string));
    
            var tR_MSGParameter = tR_MSG != null ?
                new ObjectParameter("TR_MSG", tR_MSG) :
                new ObjectParameter("TR_MSG", typeof(string));
    
            var i_PAGEParameter = i_PAGE.HasValue ?
                new ObjectParameter("I_PAGE", i_PAGE) :
                new ObjectParameter("I_PAGE", typeof(int));
    
            var i_PAGESIZEParameter = i_PAGESIZE.HasValue ?
                new ObjectParameter("I_PAGESIZE", i_PAGESIZE) :
                new ObjectParameter("I_PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_SC_LOG_SELECT_Result>("Db51_ARSConsult.NUP_SC_LOG_SELECT", sEARCH_TYPEParameter, sEARCH_DATEParameter, tR_PHONEParameter, tR_MSGParameter, i_PAGEParameter, i_PAGESIZEParameter);
        }
    }
}
