//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db51.ems50
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db51_ems50 : DbContext
    {
        public Db51_ems50()
            : base("name=Db51_ems50")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMS_MAILQUEUE> EMS_MAILQUEUE { get; set; }
    
        public virtual int NUP_MAILQUEUE_INSERT(string mAIL_CODE, string tO_EMAIL, string tO_NAME, string fROM_EMAIL, string fROM_NAME, string sUBJECT, string tARGET_FLAG, Nullable<System.DateTime> tARGET_DATE, Nullable<System.DateTime> rEG_DATE, string mAP1, string mAP2, string mAP3, string mAP4, string mAP5, string mAP_CONTENT)
        {
            var mAIL_CODEParameter = mAIL_CODE != null ?
                new ObjectParameter("MAIL_CODE", mAIL_CODE) :
                new ObjectParameter("MAIL_CODE", typeof(string));
    
            var tO_EMAILParameter = tO_EMAIL != null ?
                new ObjectParameter("TO_EMAIL", tO_EMAIL) :
                new ObjectParameter("TO_EMAIL", typeof(string));
    
            var tO_NAMEParameter = tO_NAME != null ?
                new ObjectParameter("TO_NAME", tO_NAME) :
                new ObjectParameter("TO_NAME", typeof(string));
    
            var fROM_EMAILParameter = fROM_EMAIL != null ?
                new ObjectParameter("FROM_EMAIL", fROM_EMAIL) :
                new ObjectParameter("FROM_EMAIL", typeof(string));
    
            var fROM_NAMEParameter = fROM_NAME != null ?
                new ObjectParameter("FROM_NAME", fROM_NAME) :
                new ObjectParameter("FROM_NAME", typeof(string));
    
            var sUBJECTParameter = sUBJECT != null ?
                new ObjectParameter("SUBJECT", sUBJECT) :
                new ObjectParameter("SUBJECT", typeof(string));
    
            var tARGET_FLAGParameter = tARGET_FLAG != null ?
                new ObjectParameter("TARGET_FLAG", tARGET_FLAG) :
                new ObjectParameter("TARGET_FLAG", typeof(string));
    
            var tARGET_DATEParameter = tARGET_DATE.HasValue ?
                new ObjectParameter("TARGET_DATE", tARGET_DATE) :
                new ObjectParameter("TARGET_DATE", typeof(System.DateTime));
    
            var rEG_DATEParameter = rEG_DATE.HasValue ?
                new ObjectParameter("REG_DATE", rEG_DATE) :
                new ObjectParameter("REG_DATE", typeof(System.DateTime));
    
            var mAP1Parameter = mAP1 != null ?
                new ObjectParameter("MAP1", mAP1) :
                new ObjectParameter("MAP1", typeof(string));
    
            var mAP2Parameter = mAP2 != null ?
                new ObjectParameter("MAP2", mAP2) :
                new ObjectParameter("MAP2", typeof(string));
    
            var mAP3Parameter = mAP3 != null ?
                new ObjectParameter("MAP3", mAP3) :
                new ObjectParameter("MAP3", typeof(string));
    
            var mAP4Parameter = mAP4 != null ?
                new ObjectParameter("MAP4", mAP4) :
                new ObjectParameter("MAP4", typeof(string));
    
            var mAP5Parameter = mAP5 != null ?
                new ObjectParameter("MAP5", mAP5) :
                new ObjectParameter("MAP5", typeof(string));
    
            var mAP_CONTENTParameter = mAP_CONTENT != null ?
                new ObjectParameter("MAP_CONTENT", mAP_CONTENT) :
                new ObjectParameter("MAP_CONTENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NUP_MAILQUEUE_INSERT", mAIL_CODEParameter, tO_EMAILParameter, tO_NAMEParameter, fROM_EMAILParameter, fROM_NAMEParameter, sUBJECTParameter, tARGET_FLAGParameter, tARGET_DATEParameter, rEG_DATEParameter, mAP1Parameter, mAP2Parameter, mAP3Parameter, mAP4Parameter, mAP5Parameter, mAP_CONTENTParameter);
        }
    
        public virtual int usp_ExportSendEmail_GFC(string email, string year, string language)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var languageParameter = language != null ?
                new ObjectParameter("language", language) :
                new ObjectParameter("language", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ExportSendEmail_GFC", emailParameter, yearParameter, languageParameter);
        }
    }
}
