//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db89.WOWTV_BILL_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db89_WOWTV_BILL_DB : DbContext
    {
        public Db89_WOWTV_BILL_DB()
            : base("name=Db89_WOWTV_BILL_DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TCouponMst> TCouponMst { get; set; }
        public virtual DbSet<TCouponPubMst> TCouponPubMst { get; set; }
        public virtual DbSet<TItemPriceMst> TItemPriceMst { get; set; }
        public virtual DbSet<TEventDtl> TEventDtl { get; set; }
        public virtual DbSet<TEventMst> TEventMst { get; set; }
        public virtual DbSet<TChargeCancelRequestDtl> TChargeCancelRequestDtl { get; set; }
        public virtual DbSet<TChargeCancelRequestMst> TChargeCancelRequestMst { get; set; }
        public virtual DbSet<TCPMst> TCPMst { get; set; }
        public virtual DbSet<TItemMst> TItemMst { get; set; }
        public virtual DbSet<NUP_TVREPLAY_PAYMENT> NUP_TVREPLAY_PAYMENT { get; set; }
        public virtual DbSet<TAccountCashMst> TAccountCashMst { get; set; }
        public virtual DbSet<TCashMst> TCashMst { get; set; }
        public virtual DbSet<TItemHoldMst> TItemHoldMst { get; set; }
    
        public virtual int UP_PORTAL_BONUSCASH_TX_INS(Nullable<int> pi_intUserNo, string pi_strUserID, string pi_strUserName, string pi_strPersonNo, string pi_strCashAttr, Nullable<decimal> pi_intCashAmt, string pi_strPayToolName, string pi_strAdminID, string pi_strIPAddr, string pi_strEYMD, ObjectParameter po_intCashReal, ObjectParameter po_intCashBonus, ObjectParameter po_intCashNo, ObjectParameter po_strErrMsg, ObjectParameter po_intRetVal)
        {
            var pi_intUserNoParameter = pi_intUserNo.HasValue ?
                new ObjectParameter("pi_intUserNo", pi_intUserNo) :
                new ObjectParameter("pi_intUserNo", typeof(int));
    
            var pi_strUserIDParameter = pi_strUserID != null ?
                new ObjectParameter("pi_strUserID", pi_strUserID) :
                new ObjectParameter("pi_strUserID", typeof(string));
    
            var pi_strUserNameParameter = pi_strUserName != null ?
                new ObjectParameter("pi_strUserName", pi_strUserName) :
                new ObjectParameter("pi_strUserName", typeof(string));
    
            var pi_strPersonNoParameter = pi_strPersonNo != null ?
                new ObjectParameter("pi_strPersonNo", pi_strPersonNo) :
                new ObjectParameter("pi_strPersonNo", typeof(string));
    
            var pi_strCashAttrParameter = pi_strCashAttr != null ?
                new ObjectParameter("pi_strCashAttr", pi_strCashAttr) :
                new ObjectParameter("pi_strCashAttr", typeof(string));
    
            var pi_intCashAmtParameter = pi_intCashAmt.HasValue ?
                new ObjectParameter("pi_intCashAmt", pi_intCashAmt) :
                new ObjectParameter("pi_intCashAmt", typeof(decimal));
    
            var pi_strPayToolNameParameter = pi_strPayToolName != null ?
                new ObjectParameter("pi_strPayToolName", pi_strPayToolName) :
                new ObjectParameter("pi_strPayToolName", typeof(string));
    
            var pi_strAdminIDParameter = pi_strAdminID != null ?
                new ObjectParameter("pi_strAdminID", pi_strAdminID) :
                new ObjectParameter("pi_strAdminID", typeof(string));
    
            var pi_strIPAddrParameter = pi_strIPAddr != null ?
                new ObjectParameter("pi_strIPAddr", pi_strIPAddr) :
                new ObjectParameter("pi_strIPAddr", typeof(string));
    
            var pi_strEYMDParameter = pi_strEYMD != null ?
                new ObjectParameter("pi_strEYMD", pi_strEYMD) :
                new ObjectParameter("pi_strEYMD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_WOWTV_BILL_DB.UP_PORTAL_BONUSCASH_TX_INS", pi_intUserNoParameter, pi_strUserIDParameter, pi_strUserNameParameter, pi_strPersonNoParameter, pi_strCashAttrParameter, pi_intCashAmtParameter, pi_strPayToolNameParameter, pi_strAdminIDParameter, pi_strIPAddrParameter, pi_strEYMDParameter, po_intCashReal, po_intCashBonus, po_intCashNo, po_strErrMsg, po_intRetVal);
        }
    
        public virtual ObjectResult<NUP_MEMBER_CAFE_CHARGE_SELECT_Result> NUP_MEMBER_CAFE_CHARGE_SELECT(Nullable<int> uSERNUMBER, Nullable<int> iTEMNO)
        {
            var uSERNUMBERParameter = uSERNUMBER.HasValue ?
                new ObjectParameter("USERNUMBER", uSERNUMBER) :
                new ObjectParameter("USERNUMBER", typeof(int));
    
            var iTEMNOParameter = iTEMNO.HasValue ?
                new ObjectParameter("ITEMNO", iTEMNO) :
                new ObjectParameter("ITEMNO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_MEMBER_CAFE_CHARGE_SELECT_Result>("Db89_WOWTV_BILL_DB.NUP_MEMBER_CAFE_CHARGE_SELECT", uSERNUMBERParameter, iTEMNOParameter);
        }
    
        public virtual ObjectResult<NUP_ADMIN_MEMBER_SUB_SELECT_Result> NUP_ADMIN_MEMBER_SUB_SELECT(string uSERNUMBER_LIST)
        {
            var uSERNUMBER_LISTParameter = uSERNUMBER_LIST != null ?
                new ObjectParameter("USERNUMBER_LIST", uSERNUMBER_LIST) :
                new ObjectParameter("USERNUMBER_LIST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_ADMIN_MEMBER_SUB_SELECT_Result>("Db89_WOWTV_BILL_DB.NUP_ADMIN_MEMBER_SUB_SELECT", uSERNUMBER_LISTParameter);
        }
    
        public virtual ObjectResult<UP_PORTAL_COUPON_LST_Result> UP_PORTAL_COUPON_LST(Nullable<int> pi_intUserNo, Nullable<int> pi_intUseState)
        {
            var pi_intUserNoParameter = pi_intUserNo.HasValue ?
                new ObjectParameter("pi_intUserNo", pi_intUserNo) :
                new ObjectParameter("pi_intUserNo", typeof(int));
    
            var pi_intUseStateParameter = pi_intUseState.HasValue ?
                new ObjectParameter("pi_intUseState", pi_intUseState) :
                new ObjectParameter("pi_intUseState", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_PORTAL_COUPON_LST_Result>("Db89_WOWTV_BILL_DB.UP_PORTAL_COUPON_LST", pi_intUserNoParameter, pi_intUseStateParameter);
        }
    
        public virtual int UP_PORTAL_CHARGE_LST(Nullable<byte> pi_intSearchType, string pi_strSearchKey, string pi_strYear, string pi_strMonth, Nullable<int> pi_intUseState, Nullable<int> pi_intPageNo, Nullable<int> pi_intPageSize, ObjectParameter po_intRecordCnt)
        {
            var pi_intSearchTypeParameter = pi_intSearchType.HasValue ?
                new ObjectParameter("pi_intSearchType", pi_intSearchType) :
                new ObjectParameter("pi_intSearchType", typeof(byte));
    
            var pi_strSearchKeyParameter = pi_strSearchKey != null ?
                new ObjectParameter("pi_strSearchKey", pi_strSearchKey) :
                new ObjectParameter("pi_strSearchKey", typeof(string));
    
            var pi_strYearParameter = pi_strYear != null ?
                new ObjectParameter("pi_strYear", pi_strYear) :
                new ObjectParameter("pi_strYear", typeof(string));
    
            var pi_strMonthParameter = pi_strMonth != null ?
                new ObjectParameter("pi_strMonth", pi_strMonth) :
                new ObjectParameter("pi_strMonth", typeof(string));
    
            var pi_intUseStateParameter = pi_intUseState.HasValue ?
                new ObjectParameter("pi_intUseState", pi_intUseState) :
                new ObjectParameter("pi_intUseState", typeof(int));
    
            var pi_intPageNoParameter = pi_intPageNo.HasValue ?
                new ObjectParameter("pi_intPageNo", pi_intPageNo) :
                new ObjectParameter("pi_intPageNo", typeof(int));
    
            var pi_intPageSizeParameter = pi_intPageSize.HasValue ?
                new ObjectParameter("pi_intPageSize", pi_intPageSize) :
                new ObjectParameter("pi_intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_WOWTV_BILL_DB.UP_PORTAL_CHARGE_LST", pi_intSearchTypeParameter, pi_strSearchKeyParameter, pi_strYearParameter, pi_strMonthParameter, pi_intUseStateParameter, pi_intPageNoParameter, pi_intPageSizeParameter, po_intRecordCnt);
        }
    
        public virtual ObjectResult<UP_PORTAL_REFUND_LST_Result> UP_PORTAL_REFUND_LST(Nullable<long> pi_intRefundNo, Nullable<int> pi_intUserNo, string pi_strFromYMD, string pi_strToYMD, Nullable<int> pi_intPageSize, Nullable<int> pi_intPageNo, ObjectParameter po_intRecordCnt)
        {
            var pi_intRefundNoParameter = pi_intRefundNo.HasValue ?
                new ObjectParameter("pi_intRefundNo", pi_intRefundNo) :
                new ObjectParameter("pi_intRefundNo", typeof(long));
    
            var pi_intUserNoParameter = pi_intUserNo.HasValue ?
                new ObjectParameter("pi_intUserNo", pi_intUserNo) :
                new ObjectParameter("pi_intUserNo", typeof(int));
    
            var pi_strFromYMDParameter = pi_strFromYMD != null ?
                new ObjectParameter("pi_strFromYMD", pi_strFromYMD) :
                new ObjectParameter("pi_strFromYMD", typeof(string));
    
            var pi_strToYMDParameter = pi_strToYMD != null ?
                new ObjectParameter("pi_strToYMD", pi_strToYMD) :
                new ObjectParameter("pi_strToYMD", typeof(string));
    
            var pi_intPageSizeParameter = pi_intPageSize.HasValue ?
                new ObjectParameter("pi_intPageSize", pi_intPageSize) :
                new ObjectParameter("pi_intPageSize", typeof(int));
    
            var pi_intPageNoParameter = pi_intPageNo.HasValue ?
                new ObjectParameter("pi_intPageNo", pi_intPageNo) :
                new ObjectParameter("pi_intPageNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_PORTAL_REFUND_LST_Result>("Db89_WOWTV_BILL_DB.UP_PORTAL_REFUND_LST", pi_intRefundNoParameter, pi_intUserNoParameter, pi_strFromYMDParameter, pi_strToYMDParameter, pi_intPageSizeParameter, pi_intPageNoParameter, po_intRecordCnt);
        }
    
        public virtual ObjectResult<NUP_MEMBER_INFO_SUB_SELECT_Result> NUP_MEMBER_INFO_SUB_SELECT(Nullable<int> uSERNUMBER)
        {
            var uSERNUMBERParameter = uSERNUMBER.HasValue ?
                new ObjectParameter("USERNUMBER", uSERNUMBER) :
                new ObjectParameter("USERNUMBER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_MEMBER_INFO_SUB_SELECT_Result>("Db89_WOWTV_BILL_DB.NUP_MEMBER_INFO_SUB_SELECT", uSERNUMBERParameter);
        }
    
        public virtual ObjectResult<UP_PORTAL_DELIVERY_LST_Result> UP_PORTAL_DELIVERY_LST(Nullable<long> pi_intChargeNo, Nullable<byte> pi_intSearchType, string pi_strSearchKey, string pi_strYear, string pi_strMonth, string pi_strCategoryID, string pi_strItemPriceID, Nullable<int> pi_intUseState, Nullable<int> pi_intPayState, Nullable<int> pi_intPageNo, Nullable<int> pi_intPageSize, ObjectParameter po_intRecordCnt)
        {
            var pi_intChargeNoParameter = pi_intChargeNo.HasValue ?
                new ObjectParameter("pi_intChargeNo", pi_intChargeNo) :
                new ObjectParameter("pi_intChargeNo", typeof(long));
    
            var pi_intSearchTypeParameter = pi_intSearchType.HasValue ?
                new ObjectParameter("pi_intSearchType", pi_intSearchType) :
                new ObjectParameter("pi_intSearchType", typeof(byte));
    
            var pi_strSearchKeyParameter = pi_strSearchKey != null ?
                new ObjectParameter("pi_strSearchKey", pi_strSearchKey) :
                new ObjectParameter("pi_strSearchKey", typeof(string));
    
            var pi_strYearParameter = pi_strYear != null ?
                new ObjectParameter("pi_strYear", pi_strYear) :
                new ObjectParameter("pi_strYear", typeof(string));
    
            var pi_strMonthParameter = pi_strMonth != null ?
                new ObjectParameter("pi_strMonth", pi_strMonth) :
                new ObjectParameter("pi_strMonth", typeof(string));
    
            var pi_strCategoryIDParameter = pi_strCategoryID != null ?
                new ObjectParameter("pi_strCategoryID", pi_strCategoryID) :
                new ObjectParameter("pi_strCategoryID", typeof(string));
    
            var pi_strItemPriceIDParameter = pi_strItemPriceID != null ?
                new ObjectParameter("pi_strItemPriceID", pi_strItemPriceID) :
                new ObjectParameter("pi_strItemPriceID", typeof(string));
    
            var pi_intUseStateParameter = pi_intUseState.HasValue ?
                new ObjectParameter("pi_intUseState", pi_intUseState) :
                new ObjectParameter("pi_intUseState", typeof(int));
    
            var pi_intPayStateParameter = pi_intPayState.HasValue ?
                new ObjectParameter("pi_intPayState", pi_intPayState) :
                new ObjectParameter("pi_intPayState", typeof(int));
    
            var pi_intPageNoParameter = pi_intPageNo.HasValue ?
                new ObjectParameter("pi_intPageNo", pi_intPageNo) :
                new ObjectParameter("pi_intPageNo", typeof(int));
    
            var pi_intPageSizeParameter = pi_intPageSize.HasValue ?
                new ObjectParameter("pi_intPageSize", pi_intPageSize) :
                new ObjectParameter("pi_intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_PORTAL_DELIVERY_LST_Result>("Db89_WOWTV_BILL_DB.UP_PORTAL_DELIVERY_LST", pi_intChargeNoParameter, pi_intSearchTypeParameter, pi_strSearchKeyParameter, pi_strYearParameter, pi_strMonthParameter, pi_strCategoryIDParameter, pi_strItemPriceIDParameter, pi_intUseStateParameter, pi_intPayStateParameter, pi_intPageNoParameter, pi_intPageSizeParameter, po_intRecordCnt);
        }
    
        public virtual ObjectResult<WOWSP_GET_BALANCE_Result> WOWSP_GET_BALANCE(Nullable<int> userNo)
        {
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("UserNo", userNo) :
                new ObjectParameter("UserNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WOWSP_GET_BALANCE_Result>("Db89_WOWTV_BILL_DB.WOWSP_GET_BALANCE", userNoParameter);
        }
    
        public virtual ObjectResult<UP_PORTAL_MYPAGE_DELIVERY_UR_LST_Result> UP_PORTAL_MYPAGE_DELIVERY_UR_LST(Nullable<int> pi_intUserNo, string pi_strFromYMD, string pi_strToYMD, Nullable<int> pi_intPageSize, Nullable<int> pi_intPageNo, ObjectParameter po_intRecordCnt)
        {
            var pi_intUserNoParameter = pi_intUserNo.HasValue ?
                new ObjectParameter("pi_intUserNo", pi_intUserNo) :
                new ObjectParameter("pi_intUserNo", typeof(int));
    
            var pi_strFromYMDParameter = pi_strFromYMD != null ?
                new ObjectParameter("pi_strFromYMD", pi_strFromYMD) :
                new ObjectParameter("pi_strFromYMD", typeof(string));
    
            var pi_strToYMDParameter = pi_strToYMD != null ?
                new ObjectParameter("pi_strToYMD", pi_strToYMD) :
                new ObjectParameter("pi_strToYMD", typeof(string));
    
            var pi_intPageSizeParameter = pi_intPageSize.HasValue ?
                new ObjectParameter("pi_intPageSize", pi_intPageSize) :
                new ObjectParameter("pi_intPageSize", typeof(int));
    
            var pi_intPageNoParameter = pi_intPageNo.HasValue ?
                new ObjectParameter("pi_intPageNo", pi_intPageNo) :
                new ObjectParameter("pi_intPageNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_PORTAL_MYPAGE_DELIVERY_UR_LST_Result>("Db89_WOWTV_BILL_DB.UP_PORTAL_MYPAGE_DELIVERY_UR_LST", pi_intUserNoParameter, pi_strFromYMDParameter, pi_strToYMDParameter, pi_intPageSizeParameter, pi_intPageNoParameter, po_intRecordCnt);
        }
    
        public virtual int UP_PORTAL_USERCLASS_INFO_GET(Nullable<int> pi_intUserNo, ObjectParameter po_intUsedPrice, ObjectParameter po_intUserClass, ObjectParameter po_intNextClassAmount, ObjectParameter po_intNextAgainClassAmount)
        {
            var pi_intUserNoParameter = pi_intUserNo.HasValue ?
                new ObjectParameter("pi_intUserNo", pi_intUserNo) :
                new ObjectParameter("pi_intUserNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_WOWTV_BILL_DB.UP_PORTAL_USERCLASS_INFO_GET", pi_intUserNoParameter, po_intUsedPrice, po_intUserClass, po_intNextClassAmount, po_intNextAgainClassAmount);
        }
    
        public virtual ObjectResult<UP_PORTAL_MYPAGE_SERVICE_UR_LST_Result> UP_PORTAL_MYPAGE_SERVICE_UR_LST(Nullable<int> pi_intUserNo, string pi_strFromYMD, string pi_strToYMD, string pi_strServiceName, Nullable<byte> pi_intServiceStatus, Nullable<int> pi_intPageSize, Nullable<int> pi_intPageNo, ObjectParameter po_intRecordCnt)
        {
            var pi_intUserNoParameter = pi_intUserNo.HasValue ?
                new ObjectParameter("pi_intUserNo", pi_intUserNo) :
                new ObjectParameter("pi_intUserNo", typeof(int));
    
            var pi_strFromYMDParameter = pi_strFromYMD != null ?
                new ObjectParameter("pi_strFromYMD", pi_strFromYMD) :
                new ObjectParameter("pi_strFromYMD", typeof(string));
    
            var pi_strToYMDParameter = pi_strToYMD != null ?
                new ObjectParameter("pi_strToYMD", pi_strToYMD) :
                new ObjectParameter("pi_strToYMD", typeof(string));
    
            var pi_strServiceNameParameter = pi_strServiceName != null ?
                new ObjectParameter("pi_strServiceName", pi_strServiceName) :
                new ObjectParameter("pi_strServiceName", typeof(string));
    
            var pi_intServiceStatusParameter = pi_intServiceStatus.HasValue ?
                new ObjectParameter("pi_intServiceStatus", pi_intServiceStatus) :
                new ObjectParameter("pi_intServiceStatus", typeof(byte));
    
            var pi_intPageSizeParameter = pi_intPageSize.HasValue ?
                new ObjectParameter("pi_intPageSize", pi_intPageSize) :
                new ObjectParameter("pi_intPageSize", typeof(int));
    
            var pi_intPageNoParameter = pi_intPageNo.HasValue ?
                new ObjectParameter("pi_intPageNo", pi_intPageNo) :
                new ObjectParameter("pi_intPageNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_PORTAL_MYPAGE_SERVICE_UR_LST_Result>("Db89_WOWTV_BILL_DB.UP_PORTAL_MYPAGE_SERVICE_UR_LST", pi_intUserNoParameter, pi_strFromYMDParameter, pi_strToYMDParameter, pi_strServiceNameParameter, pi_intServiceStatusParameter, pi_intPageSizeParameter, pi_intPageNoParameter, po_intRecordCnt);
        }
    
        public virtual ObjectResult<UP_PORTAL_PAYNCHARGE_LST_Result> UP_PORTAL_PAYNCHARGE_LST(Nullable<byte> pi_intSearchType, string pi_strSearchKey, string pi_strFromYMD, string pi_strToYMD, Nullable<int> pi_intPageNo, Nullable<int> pi_intPageSize, ObjectParameter po_intRecordCnt)
        {
            var pi_intSearchTypeParameter = pi_intSearchType.HasValue ?
                new ObjectParameter("pi_intSearchType", pi_intSearchType) :
                new ObjectParameter("pi_intSearchType", typeof(byte));
    
            var pi_strSearchKeyParameter = pi_strSearchKey != null ?
                new ObjectParameter("pi_strSearchKey", pi_strSearchKey) :
                new ObjectParameter("pi_strSearchKey", typeof(string));
    
            var pi_strFromYMDParameter = pi_strFromYMD != null ?
                new ObjectParameter("pi_strFromYMD", pi_strFromYMD) :
                new ObjectParameter("pi_strFromYMD", typeof(string));
    
            var pi_strToYMDParameter = pi_strToYMD != null ?
                new ObjectParameter("pi_strToYMD", pi_strToYMD) :
                new ObjectParameter("pi_strToYMD", typeof(string));
    
            var pi_intPageNoParameter = pi_intPageNo.HasValue ?
                new ObjectParameter("pi_intPageNo", pi_intPageNo) :
                new ObjectParameter("pi_intPageNo", typeof(int));
    
            var pi_intPageSizeParameter = pi_intPageSize.HasValue ?
                new ObjectParameter("pi_intPageSize", pi_intPageSize) :
                new ObjectParameter("pi_intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_PORTAL_PAYNCHARGE_LST_Result>("Db89_WOWTV_BILL_DB.UP_PORTAL_PAYNCHARGE_LST", pi_intSearchTypeParameter, pi_strSearchKeyParameter, pi_strFromYMDParameter, pi_strToYMDParameter, pi_intPageNoParameter, pi_intPageSizeParameter, po_intRecordCnt);
        }
    
        public virtual ObjectResult<UP_PORTAL_MYPAGE_PAYNCHARGE_UR_LST_Result> UP_PORTAL_MYPAGE_PAYNCHARGE_UR_LST(Nullable<int> pi_intUserNo, string pi_strFromYMD, string pi_strToYMD, Nullable<int> pi_intPageNo, Nullable<int> pi_intPageSize, ObjectParameter po_intRecordCnt)
        {
            var pi_intUserNoParameter = pi_intUserNo.HasValue ?
                new ObjectParameter("pi_intUserNo", pi_intUserNo) :
                new ObjectParameter("pi_intUserNo", typeof(int));
    
            var pi_strFromYMDParameter = pi_strFromYMD != null ?
                new ObjectParameter("pi_strFromYMD", pi_strFromYMD) :
                new ObjectParameter("pi_strFromYMD", typeof(string));
    
            var pi_strToYMDParameter = pi_strToYMD != null ?
                new ObjectParameter("pi_strToYMD", pi_strToYMD) :
                new ObjectParameter("pi_strToYMD", typeof(string));
    
            var pi_intPageNoParameter = pi_intPageNo.HasValue ?
                new ObjectParameter("pi_intPageNo", pi_intPageNo) :
                new ObjectParameter("pi_intPageNo", typeof(int));
    
            var pi_intPageSizeParameter = pi_intPageSize.HasValue ?
                new ObjectParameter("pi_intPageSize", pi_intPageSize) :
                new ObjectParameter("pi_intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_PORTAL_MYPAGE_PAYNCHARGE_UR_LST_Result>("Db89_WOWTV_BILL_DB.UP_PORTAL_MYPAGE_PAYNCHARGE_UR_LST", pi_intUserNoParameter, pi_strFromYMDParameter, pi_strToYMDParameter, pi_intPageNoParameter, pi_intPageSizeParameter, po_intRecordCnt);
        }
    
        public virtual ObjectResult<UP_PORTAL_USER_ANAL_LST_Result> UP_PORTAL_USER_ANAL_LST(Nullable<int> pi_intUserNo)
        {
            var pi_intUserNoParameter = pi_intUserNo.HasValue ?
                new ObjectParameter("pi_intUserNo", pi_intUserNo) :
                new ObjectParameter("pi_intUserNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_PORTAL_USER_ANAL_LST_Result>("Db89_WOWTV_BILL_DB.UP_PORTAL_USER_ANAL_LST", pi_intUserNoParameter);
        }
    
        public virtual int UP_KVINA_PURCHASE_AR_LST(string pi_strUserName, string pi_strMobileNum, string pi_strProdName, Nullable<byte> pi_intStateCode, Nullable<long> pi_intChargeNo, string pi_strStartYMD, string pi_strEndYMD, Nullable<int> pi_intPageSize, Nullable<int> pi_intPageNo, ObjectParameter po_DblTotalPurAmt, ObjectParameter po_DblTotalCnlAmt, ObjectParameter po_DblTotalPurCnt, ObjectParameter po_DblTotalCnlCnt, ObjectParameter po_intRecordCnt, ObjectParameter po_intRatval)
        {
            var pi_strUserNameParameter = pi_strUserName != null ?
                new ObjectParameter("pi_strUserName", pi_strUserName) :
                new ObjectParameter("pi_strUserName", typeof(string));
    
            var pi_strMobileNumParameter = pi_strMobileNum != null ?
                new ObjectParameter("pi_strMobileNum", pi_strMobileNum) :
                new ObjectParameter("pi_strMobileNum", typeof(string));
    
            var pi_strProdNameParameter = pi_strProdName != null ?
                new ObjectParameter("pi_strProdName", pi_strProdName) :
                new ObjectParameter("pi_strProdName", typeof(string));
    
            var pi_intStateCodeParameter = pi_intStateCode.HasValue ?
                new ObjectParameter("pi_intStateCode", pi_intStateCode) :
                new ObjectParameter("pi_intStateCode", typeof(byte));
    
            var pi_intChargeNoParameter = pi_intChargeNo.HasValue ?
                new ObjectParameter("pi_intChargeNo", pi_intChargeNo) :
                new ObjectParameter("pi_intChargeNo", typeof(long));
    
            var pi_strStartYMDParameter = pi_strStartYMD != null ?
                new ObjectParameter("pi_strStartYMD", pi_strStartYMD) :
                new ObjectParameter("pi_strStartYMD", typeof(string));
    
            var pi_strEndYMDParameter = pi_strEndYMD != null ?
                new ObjectParameter("pi_strEndYMD", pi_strEndYMD) :
                new ObjectParameter("pi_strEndYMD", typeof(string));
    
            var pi_intPageSizeParameter = pi_intPageSize.HasValue ?
                new ObjectParameter("pi_intPageSize", pi_intPageSize) :
                new ObjectParameter("pi_intPageSize", typeof(int));
    
            var pi_intPageNoParameter = pi_intPageNo.HasValue ?
                new ObjectParameter("pi_intPageNo", pi_intPageNo) :
                new ObjectParameter("pi_intPageNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_WOWTV_BILL_DB.UP_KVINA_PURCHASE_AR_LST", pi_strUserNameParameter, pi_strMobileNumParameter, pi_strProdNameParameter, pi_intStateCodeParameter, pi_intChargeNoParameter, pi_strStartYMDParameter, pi_strEndYMDParameter, pi_intPageSizeParameter, pi_intPageNoParameter, po_DblTotalPurAmt, po_DblTotalCnlAmt, po_DblTotalPurCnt, po_DblTotalCnlCnt, po_intRecordCnt, po_intRatval);
        }
    }
}
