//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db89.WOWTV_BILL_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCashMst
    {
        public long CashNo { get; set; }
        public int UserNo { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string GameCode { get; set; }
        public string CashAttr { get; set; }
        public byte CashType { get; set; }
        public byte Flags { get; set; }
        public decimal OrgCashAmt { get; set; }
        public decimal CashAmt { get; set; }
        public decimal RemainCashAmt { get; set; }
        public byte PayTool { get; set; }
        public string PayToolName { get; set; }
        public string PGCode { get; set; }
        public string MallID { get; set; }
        public short PGVersion { get; set; }
        public string TID { get; set; }
        public string CID { get; set; }
        public string YMD { get; set; }
        public string TYMD { get; set; }
        public string CYMD { get; set; }
        public string TCYMD { get; set; }
        public string EYMD { get; set; }
        public string AdminID { get; set; }
        public string IPAddr { get; set; }
        public Nullable<long> OrgCashNo { get; set; }
        public Nullable<byte> IssueFlag { get; set; }
        public Nullable<int> IssueNo { get; set; }
        public byte UseState { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
    }
}
