//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db89.WOWTV_BILL_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCouponMst
    {
        public int CouponSeqNo { get; set; }
        public string CouponNo { get; set; }
        public string GameCode { get; set; }
        public Nullable<int> UserNo { get; set; }
        public string UserID { get; set; }
        public int CouponID { get; set; }
        public int SeqNo { get; set; }
        public int PubSeqNo { get; set; }
        public string HExpYMD { get; set; }
        public string CExpYMD { get; set; }
        public Nullable<long> ChargeNo { get; set; }
        public Nullable<long> CashNo { get; set; }
        public byte UseState { get; set; }
        public string YMD { get; set; }
        public string RYMD { get; set; }
        public string IPAddr { get; set; }
        public string UsedTitle { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
    }
}
