//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db89.WOWTV_BILL_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCPMst
    {
        public short CPID { get; set; }
        public short CPVersion { get; set; }
        public string CPName { get; set; }
        public string CEOName { get; set; }
        public string MICName { get; set; }
        public string MICEmail { get; set; }
        public string MICTelNo { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public byte SettleMethod { get; set; }
        public decimal SettleAmt { get; set; }
        public Nullable<decimal> PGRate { get; set; }
        public Nullable<decimal> MyRate { get; set; }
        public decimal ETCComm1 { get; set; }
        public decimal ETCComm2 { get; set; }
        public decimal MINComm { get; set; }
        public decimal MAXComm { get; set; }
        public byte COMFlag { get; set; }
        public byte INCVAT { get; set; }
        public byte UseState { get; set; }
        public string AdminID { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
    }
}
