//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db89.WOWTV_BILL_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TItemMst
    {
        public int ItemID { get; set; }
        public short ItemVersion { get; set; }
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public string CategoryID { get; set; }
        public string GameCode { get; set; }
        public byte ShowRate { get; set; }
        public int CPID { get; set; }
        public short CPVersion { get; set; }
        public Nullable<byte> DeptCode { get; set; }
        public byte UseState { get; set; }
        public string AdminID { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string KOSCOMACCTNO { get; set; }
        public string IsAvailBonus { get; set; }
    }
}
