//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db89.WOWTV_BILL_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TItemPriceMst
    {
        public int ItemID { get; set; }
        public int ItemPriceID { get; set; }
        public string ItemName { get; set; }
        public byte ChargeType { get; set; }
        public byte DurationType { get; set; }
        public int Duration { get; set; }
        public int MaxAccessCnt { get; set; }
        public string SYMD { get; set; }
        public string FYMD { get; set; }
        public string ExpireYMD { get; set; }
        public string CPItemID { get; set; }
        public string ServiceURL { get; set; }
        public int Mileage { get; set; }
        public decimal Price { get; set; }
        public byte DiscountRate { get; set; }
        public byte DeliveryAvail { get; set; }
        public decimal DeliveryAmt { get; set; }
        public decimal GiftItemPrice { get; set; }
        public byte GeneralFlag { get; set; }
        public string AnalID { get; set; }
        public Nullable<byte> ARSFlag { get; set; }
        public Nullable<byte> CafeFlag { get; set; }
        public Nullable<byte> CafeLevel { get; set; }
        public Nullable<byte> CancelCafeLevel { get; set; }
        public string DisplayLocation { get; set; }
        public byte DisplayFlag { get; set; }
        public byte ReductionFlag { get; set; }
        public byte ExchangeFlag { get; set; }
        public byte CancelFlag { get; set; }
        public byte ReNewFlag { get; set; }
        public byte UseState { get; set; }
        public string AdminID { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public Nullable<byte> CoopPointFlag { get; set; }
        public Nullable<byte> DupDCFlag { get; set; }
        public Nullable<int> ClassDcFlag { get; set; }
        public Nullable<byte> DupBuyFlag { get; set; }
        public string IsAvailBonus { get; set; }
    }
}
