//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db51.contents
{
    using System;
    using System.Collections.Generic;
    
    public partial class wowtv_deacha
    {
        public int no { get; set; }
        public string year { get; set; }
        public string month { get; set; }
        public string youdongjasan { get; set; }
        public string gojungjasan { get; set; }
        public string jasantotal { get; set; }
        public string youdongbucha { get; set; }
        public string gojungbucha { get; set; }
        public string buchetotal { get; set; }
        public string jabonkum { get; set; }
        public string jabonenyekum { get; set; }
        public string eiceingyekum { get; set; }
        public string jabonjojung { get; set; }
        public string jabontotal { get; set; }
        public string regdage { get; set; }
        public string FLAG { get; set; }
        public string REG_ID { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
    }
}
