//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db123.WOW4989
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db123_WOw4989 : DbContext
    {
        public Db123_WOw4989()
            : base("name=Db123_WOw4989")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<wowstar_unliststock_Result> wowstar_unliststock(string nOWDATE)
        {
            var nOWDATEParameter = nOWDATE != null ?
                new ObjectParameter("NOWDATE", nOWDATE) :
                new ObjectParameter("NOWDATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<wowstar_unliststock_Result>("Db123_WOw4989.wowstar_unliststock", nOWDATEParameter);
        }
    
        public virtual ObjectResult<wowstar_video_Result> wowstar_video(Nullable<int> nums)
        {
            var numsParameter = nums.HasValue ?
                new ObjectParameter("nums", nums) :
                new ObjectParameter("nums", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<wowstar_video_Result>("Db123_WOw4989.wowstar_video", numsParameter);
        }
    
        public virtual ObjectResult<NUP_wowstar_unliststock_Result> NUP_wowstar_unliststock(string nOWDATE)
        {
            var nOWDATEParameter = nOWDATE != null ?
                new ObjectParameter("NOWDATE", nOWDATE) :
                new ObjectParameter("NOWDATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_wowstar_unliststock_Result>("Db123_WOw4989.NUP_wowstar_unliststock", nOWDATEParameter);
        }
    
        public virtual ObjectResult<wowstar_p2p_wowtv_Result> wowstar_p2p_wowtv()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<wowstar_p2p_wowtv_Result>("Db123_WOw4989.wowstar_p2p_wowtv");
        }
    }
}
