//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.Article
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleClass
    {
        public int IDX { get; set; }
        public string WOWCode { get; set; }
        public System.DateTime ArticleDate { get; set; }
        public string CompCode { get; set; }
        public string ClassCode { get; set; }
        public string ArticleID { get; set; }
        public string Title { get; set; }
        public Nullable<int> isHead { get; set; }
        public Nullable<int> isList { get; set; }
        public Nullable<byte> isBold { get; set; }
        public Nullable<int> isList_n { get; set; }
        public Nullable<int> isType { get; set; }
        public Nullable<int> isMarket { get; set; }
        public Nullable<int> isRelation { get; set; }
        public Nullable<int> ordernum { get; set; }
        public Nullable<int> ordernumstockbusiness { get; set; }
        public Nullable<int> ordernumindustry { get; set; }
        public Nullable<int> ordernumestate { get; set; }
        public Nullable<int> ordernument { get; set; }
        public Nullable<int> ordernumbb1 { get; set; }
        public Nullable<int> ordernumbb2 { get; set; }
    }
}
