//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.Article
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleList_WO
    {
        public string CompCode { get; set; }
        public string ArticleID { get; set; }
        public System.DateTime ArticleDate { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public string Writer { get; set; }
        public string EMail { get; set; }
        public string HTML { get; set; }
    }
}
