//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.Article
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db49_Article : DbContext
    {
        public Db49_Article()
            : base("name=Db49_Article")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblNewsStand> tblNewsStand { get; set; }
        public virtual DbSet<ArticleClass> ArticleClass { get; set; }
        public virtual DbSet<tblNewsStandArticleManage> tblNewsStandArticleManage { get; set; }
        public virtual DbSet<tblArticleCreation> tblArticleCreation { get; set; }
        public virtual DbSet<ArticleList_HK> ArticleList_HK { get; set; }
        public virtual DbSet<ArticleList_WO> ArticleList_WO { get; set; }
        public virtual DbSet<ArticleList_YH> ArticleList_YH { get; set; }
        public virtual DbSet<NTB_ARTICLE_CONFIG> NTB_ARTICLE_CONFIG { get; set; }
        public virtual DbSet<tblArticleListFTS> tblArticleListFTS { get; set; }
        public virtual DbSet<ArtClickCount> ArtClickCount { get; set; }
        public virtual DbSet<ArtClickCountHtml> ArtClickCountHtml { get; set; }
        public virtual DbSet<NTB_TEXT_LINK> NTB_TEXT_LINK { get; set; }
        public virtual DbSet<NTB_ARTICLE_SHOW_CONFIG> NTB_ARTICLE_SHOW_CONFIG { get; set; }
        public virtual DbSet<NTB_ARTICLE_SHOW_NUM> NTB_ARTICLE_SHOW_NUM { get; set; }
        public virtual DbSet<NTB_ARTICLE_VIEWPAGE_MANAGE> NTB_ARTICLE_VIEWPAGE_MANAGE { get; set; }
        public virtual DbSet<NTB_ARTICLE_COMMENT> NTB_ARTICLE_COMMENT { get; set; }
        public virtual DbSet<NTB_HARD_CODING_AD> NTB_HARD_CODING_AD { get; set; }
        public virtual DbSet<tblPlanArticle> tblPlanArticle { get; set; }
        public virtual DbSet<tblRelationImage> tblRelationImage { get; set; }
        public virtual DbSet<NTB_ARTICLE_RELATION_CONFIG> NTB_ARTICLE_RELATION_CONFIG { get; set; }
        public virtual DbSet<NTB_REPORTER_AWORD> NTB_REPORTER_AWORD { get; set; }
        public virtual DbSet<NTB_REPORTER_RECOMMEND> NTB_REPORTER_RECOMMEND { get; set; }

		public object usp_WOWTVNewsCenterView_Result(string articleId)
		{
			throw new NotImplementedException();
		}

		public virtual DbSet<NTB_ARTICLE_SUBSCRIPTION> NTB_ARTICLE_SUBSCRIPTION { get; set; }
        public virtual DbSet<ArticleStock> ArticleStock { get; set; }
        public virtual DbSet<tblArticleList> tblArticleList { get; set; }
        public virtual DbSet<NTB_ARTICLE_LIKEIT> NTB_ARTICLE_LIKEIT { get; set; }
        public virtual DbSet<NTB_PREV_ARTICLE_COUNT> NTB_PREV_ARTICLE_COUNT { get; set; }
        public virtual DbSet<ArticleClass_Hanatour> ArticleClass_Hanatour { get; set; }
        public virtual DbSet<NTB_POST> NTB_POST { get; set; }
        public virtual DbSet<NTB_ARTICLE_LIKEIT_HANATOUR> NTB_ARTICLE_LIKEIT_HANATOUR { get; set; }
        public virtual DbSet<NTB_REPORTER_MANAGE> NTB_REPORTER_MANAGE { get; set; }
        public virtual DbSet<NTB_HUB_BUSINESS> NTB_HUB_BUSINESS { get; set; }
        public virtual DbSet<NTB_REPORTER_PROFILE> NTB_REPORTER_PROFILE { get; set; }
    
        public virtual ObjectResult<usp_getArticleTotalList_Result> usp_getArticleTotalList(string classCode, string dateTime, string sKey, string wOWFlag, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var classCodeParameter = classCode != null ?
                new ObjectParameter("ClassCode", classCode) :
                new ObjectParameter("ClassCode", typeof(string));
    
            var dateTimeParameter = dateTime != null ?
                new ObjectParameter("DateTime", dateTime) :
                new ObjectParameter("DateTime", typeof(string));
    
            var sKeyParameter = sKey != null ?
                new ObjectParameter("sKey", sKey) :
                new ObjectParameter("sKey", typeof(string));
    
            var wOWFlagParameter = wOWFlag != null ?
                new ObjectParameter("WOWFlag", wOWFlag) :
                new ObjectParameter("WOWFlag", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getArticleTotalList_Result>("Db49_Article.usp_getArticleTotalList", classCodeParameter, dateTimeParameter, sKeyParameter, wOWFlagParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual int NUP_TBLARTICLELIST_COUNT_SELECT(string s_STARTDATE, string s_ENDDATE, string s_TITLE, string s_ARTICLEID, string s_USERNM, ObjectParameter o_TOTALCOUNT)
        {
            var s_STARTDATEParameter = s_STARTDATE != null ?
                new ObjectParameter("S_STARTDATE", s_STARTDATE) :
                new ObjectParameter("S_STARTDATE", typeof(string));
    
            var s_ENDDATEParameter = s_ENDDATE != null ?
                new ObjectParameter("S_ENDDATE", s_ENDDATE) :
                new ObjectParameter("S_ENDDATE", typeof(string));
    
            var s_TITLEParameter = s_TITLE != null ?
                new ObjectParameter("S_TITLE", s_TITLE) :
                new ObjectParameter("S_TITLE", typeof(string));
    
            var s_ARTICLEIDParameter = s_ARTICLEID != null ?
                new ObjectParameter("S_ARTICLEID", s_ARTICLEID) :
                new ObjectParameter("S_ARTICLEID", typeof(string));
    
            var s_USERNMParameter = s_USERNM != null ?
                new ObjectParameter("S_USERNM", s_USERNM) :
                new ObjectParameter("S_USERNM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db49_Article.NUP_TBLARTICLELIST_COUNT_SELECT", s_STARTDATEParameter, s_ENDDATEParameter, s_TITLEParameter, s_ARTICLEIDParameter, s_USERNMParameter, o_TOTALCOUNT);
        }
    
        public virtual ObjectResult<NUP_NEWSSTAND_SELECT_Result> NUP_NEWSSTAND_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWSSTAND_SELECT_Result>("Db49_Article.NUP_NEWSSTAND_SELECT");
        }
    
        public virtual ObjectResult<NUP_NEWS_MAIN_MAGE_SELECT_Result> NUP_NEWS_MAIN_MAGE_SELECT(string s_SEARCHCOMP, string s_SEARCHGUBUN, string s_SEARCHDEPT, string s_SEARCHTEXT, string s_STARTDATE, string s_ENDDATE, Nullable<int> i_PAGE, Nullable<int> i_PAGESIZE)
        {
            var s_SEARCHCOMPParameter = s_SEARCHCOMP != null ?
                new ObjectParameter("S_SEARCHCOMP", s_SEARCHCOMP) :
                new ObjectParameter("S_SEARCHCOMP", typeof(string));
    
            var s_SEARCHGUBUNParameter = s_SEARCHGUBUN != null ?
                new ObjectParameter("S_SEARCHGUBUN", s_SEARCHGUBUN) :
                new ObjectParameter("S_SEARCHGUBUN", typeof(string));
    
            var s_SEARCHDEPTParameter = s_SEARCHDEPT != null ?
                new ObjectParameter("S_SEARCHDEPT", s_SEARCHDEPT) :
                new ObjectParameter("S_SEARCHDEPT", typeof(string));
    
            var s_SEARCHTEXTParameter = s_SEARCHTEXT != null ?
                new ObjectParameter("S_SEARCHTEXT", s_SEARCHTEXT) :
                new ObjectParameter("S_SEARCHTEXT", typeof(string));
    
            var s_STARTDATEParameter = s_STARTDATE != null ?
                new ObjectParameter("S_STARTDATE", s_STARTDATE) :
                new ObjectParameter("S_STARTDATE", typeof(string));
    
            var s_ENDDATEParameter = s_ENDDATE != null ?
                new ObjectParameter("S_ENDDATE", s_ENDDATE) :
                new ObjectParameter("S_ENDDATE", typeof(string));
    
            var i_PAGEParameter = i_PAGE.HasValue ?
                new ObjectParameter("I_PAGE", i_PAGE) :
                new ObjectParameter("I_PAGE", typeof(int));
    
            var i_PAGESIZEParameter = i_PAGESIZE.HasValue ?
                new ObjectParameter("I_PAGESIZE", i_PAGESIZE) :
                new ObjectParameter("I_PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_MAIN_MAGE_SELECT_Result>("Db49_Article.NUP_NEWS_MAIN_MAGE_SELECT", s_SEARCHCOMPParameter, s_SEARCHGUBUNParameter, s_SEARCHDEPTParameter, s_SEARCHTEXTParameter, s_STARTDATEParameter, s_ENDDATEParameter, i_PAGEParameter, i_PAGESIZEParameter);
        }
    
        public virtual ObjectResult<usp_newsStandMetaXMLTopImg_Result> usp_newsStandMetaXMLTopImg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_newsStandMetaXMLTopImg_Result>("Db49_Article.usp_newsStandMetaXMLTopImg");
        }
    
        public virtual ObjectResult<NUP_NEWS_CARD_VOD_SELECT_Result> NUP_NEWS_CARD_VOD_SELECT(string s_SEARCHGUBUN, string s_SEARCHTEXT, string s_STARTDATE, string s_ENDDATE, Nullable<int> i_PAGE, Nullable<int> i_PAGESIZE)
        {
            var s_SEARCHGUBUNParameter = s_SEARCHGUBUN != null ?
                new ObjectParameter("S_SEARCHGUBUN", s_SEARCHGUBUN) :
                new ObjectParameter("S_SEARCHGUBUN", typeof(string));
    
            var s_SEARCHTEXTParameter = s_SEARCHTEXT != null ?
                new ObjectParameter("S_SEARCHTEXT", s_SEARCHTEXT) :
                new ObjectParameter("S_SEARCHTEXT", typeof(string));
    
            var s_STARTDATEParameter = s_STARTDATE != null ?
                new ObjectParameter("S_STARTDATE", s_STARTDATE) :
                new ObjectParameter("S_STARTDATE", typeof(string));
    
            var s_ENDDATEParameter = s_ENDDATE != null ?
                new ObjectParameter("S_ENDDATE", s_ENDDATE) :
                new ObjectParameter("S_ENDDATE", typeof(string));
    
            var i_PAGEParameter = i_PAGE.HasValue ?
                new ObjectParameter("I_PAGE", i_PAGE) :
                new ObjectParameter("I_PAGE", typeof(int));
    
            var i_PAGESIZEParameter = i_PAGESIZE.HasValue ?
                new ObjectParameter("I_PAGESIZE", i_PAGESIZE) :
                new ObjectParameter("I_PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_CARD_VOD_SELECT_Result>("Db49_Article.NUP_NEWS_CARD_VOD_SELECT", s_SEARCHGUBUNParameter, s_SEARCHTEXTParameter, s_STARTDATEParameter, s_ENDDATEParameter, i_PAGEParameter, i_PAGESIZEParameter);
        }
    
        public virtual ObjectResult<NUP_ARTICLE_SELECT_Result> NUP_ARTICLE_SELECT(Nullable<System.DateTime> sTARTDATE, Nullable<System.DateTime> eNDDATE, string cOMPCODE, string dEPTCD, string wRITER, string tITLE, string aRTID, string uSERID)
        {
            var sTARTDATEParameter = sTARTDATE.HasValue ?
                new ObjectParameter("STARTDATE", sTARTDATE) :
                new ObjectParameter("STARTDATE", typeof(System.DateTime));
    
            var eNDDATEParameter = eNDDATE.HasValue ?
                new ObjectParameter("ENDDATE", eNDDATE) :
                new ObjectParameter("ENDDATE", typeof(System.DateTime));
    
            var cOMPCODEParameter = cOMPCODE != null ?
                new ObjectParameter("COMPCODE", cOMPCODE) :
                new ObjectParameter("COMPCODE", typeof(string));
    
            var dEPTCDParameter = dEPTCD != null ?
                new ObjectParameter("DEPTCD", dEPTCD) :
                new ObjectParameter("DEPTCD", typeof(string));
    
            var wRITERParameter = wRITER != null ?
                new ObjectParameter("WRITER", wRITER) :
                new ObjectParameter("WRITER", typeof(string));
    
            var tITLEParameter = tITLE != null ?
                new ObjectParameter("TITLE", tITLE) :
                new ObjectParameter("TITLE", typeof(string));
    
            var aRTIDParameter = aRTID != null ?
                new ObjectParameter("ARTID", aRTID) :
                new ObjectParameter("ARTID", typeof(string));
    
            var uSERIDParameter = uSERID != null ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_ARTICLE_SELECT_Result>("Db49_Article.NUP_ARTICLE_SELECT", sTARTDATEParameter, eNDDATEParameter, cOMPCODEParameter, dEPTCDParameter, wRITERParameter, tITLEParameter, aRTIDParameter, uSERIDParameter);
        }
    
        public virtual ObjectResult<NUP_ARTICLE_PROVIDE_SELECT_Result> NUP_ARTICLE_PROVIDE_SELECT(Nullable<System.DateTime> sTARTDATE, Nullable<System.DateTime> eNDDATE, string cOMPCODE)
        {
            var sTARTDATEParameter = sTARTDATE.HasValue ?
                new ObjectParameter("STARTDATE", sTARTDATE) :
                new ObjectParameter("STARTDATE", typeof(System.DateTime));
    
            var eNDDATEParameter = eNDDATE.HasValue ?
                new ObjectParameter("ENDDATE", eNDDATE) :
                new ObjectParameter("ENDDATE", typeof(System.DateTime));
    
            var cOMPCODEParameter = cOMPCODE != null ?
                new ObjectParameter("COMPCODE", cOMPCODE) :
                new ObjectParameter("COMPCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_ARTICLE_PROVIDE_SELECT_Result>("Db49_Article.NUP_ARTICLE_PROVIDE_SELECT", sTARTDATEParameter, eNDDATEParameter, cOMPCODEParameter);
        }
    
        public virtual ObjectResult<NUP_FREELANCER_TRAFFIC_SELECT_Result> NUP_FREELANCER_TRAFFIC_SELECT(Nullable<System.DateTime> sTARTDATE, Nullable<System.DateTime> eNDDATE, string cOMPCODE)
        {
            var sTARTDATEParameter = sTARTDATE.HasValue ?
                new ObjectParameter("STARTDATE", sTARTDATE) :
                new ObjectParameter("STARTDATE", typeof(System.DateTime));
    
            var eNDDATEParameter = eNDDATE.HasValue ?
                new ObjectParameter("ENDDATE", eNDDATE) :
                new ObjectParameter("ENDDATE", typeof(System.DateTime));
    
            var cOMPCODEParameter = cOMPCODE != null ?
                new ObjectParameter("COMPCODE", cOMPCODE) :
                new ObjectParameter("COMPCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_FREELANCER_TRAFFIC_SELECT_Result>("Db49_Article.NUP_FREELANCER_TRAFFIC_SELECT", sTARTDATEParameter, eNDDATEParameter, cOMPCODEParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_LAND_ENTSPO_SELECT_Result> NUP_NEWS_LAND_ENTSPO_SELECT(string s_SEARCHGUBUN, string s_SEARCHSECTION, string s_SEARCHTEXT, string s_STARTDATE, string s_ENDDATE, Nullable<int> i_PAGE, Nullable<int> i_PAGESIZE)
        {
            var s_SEARCHGUBUNParameter = s_SEARCHGUBUN != null ?
                new ObjectParameter("S_SEARCHGUBUN", s_SEARCHGUBUN) :
                new ObjectParameter("S_SEARCHGUBUN", typeof(string));
    
            var s_SEARCHSECTIONParameter = s_SEARCHSECTION != null ?
                new ObjectParameter("S_SEARCHSECTION", s_SEARCHSECTION) :
                new ObjectParameter("S_SEARCHSECTION", typeof(string));
    
            var s_SEARCHTEXTParameter = s_SEARCHTEXT != null ?
                new ObjectParameter("S_SEARCHTEXT", s_SEARCHTEXT) :
                new ObjectParameter("S_SEARCHTEXT", typeof(string));
    
            var s_STARTDATEParameter = s_STARTDATE != null ?
                new ObjectParameter("S_STARTDATE", s_STARTDATE) :
                new ObjectParameter("S_STARTDATE", typeof(string));
    
            var s_ENDDATEParameter = s_ENDDATE != null ?
                new ObjectParameter("S_ENDDATE", s_ENDDATE) :
                new ObjectParameter("S_ENDDATE", typeof(string));
    
            var i_PAGEParameter = i_PAGE.HasValue ?
                new ObjectParameter("I_PAGE", i_PAGE) :
                new ObjectParameter("I_PAGE", typeof(int));
    
            var i_PAGESIZEParameter = i_PAGESIZE.HasValue ?
                new ObjectParameter("I_PAGESIZE", i_PAGESIZE) :
                new ObjectParameter("I_PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_LAND_ENTSPO_SELECT_Result>("Db49_Article.NUP_NEWS_LAND_ENTSPO_SELECT", s_SEARCHGUBUNParameter, s_SEARCHSECTIONParameter, s_SEARCHTEXTParameter, s_STARTDATEParameter, s_ENDDATEParameter, i_PAGEParameter, i_PAGESIZEParameter);
        }
    
        public virtual ObjectResult<NUP_FREELANCER_ARTICLE_RANK_SELECT_Result> NUP_FREELANCER_ARTICLE_RANK_SELECT(Nullable<System.DateTime> sTARTDATE, Nullable<System.DateTime> eNDDATE, string cOMPCODE, string dNRS_USER_ID)
        {
            var sTARTDATEParameter = sTARTDATE.HasValue ?
                new ObjectParameter("STARTDATE", sTARTDATE) :
                new ObjectParameter("STARTDATE", typeof(System.DateTime));
    
            var eNDDATEParameter = eNDDATE.HasValue ?
                new ObjectParameter("ENDDATE", eNDDATE) :
                new ObjectParameter("ENDDATE", typeof(System.DateTime));
    
            var cOMPCODEParameter = cOMPCODE != null ?
                new ObjectParameter("COMPCODE", cOMPCODE) :
                new ObjectParameter("COMPCODE", typeof(string));
    
            var dNRS_USER_IDParameter = dNRS_USER_ID != null ?
                new ObjectParameter("DNRS_USER_ID", dNRS_USER_ID) :
                new ObjectParameter("DNRS_USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_FREELANCER_ARTICLE_RANK_SELECT_Result>("Db49_Article.NUP_FREELANCER_ARTICLE_RANK_SELECT", sTARTDATEParameter, eNDDATEParameter, cOMPCODEParameter, dNRS_USER_IDParameter);
        }
    
        public virtual ObjectResult<NUP_REPORTER_MANAGE_SELECT_Result> NUP_REPORTER_MANAGE_SELECT(string s_SEARCHGUBUN, string s_SEARCHTEXT, string s_STARTDATE, string s_ENDDATE, Nullable<int> i_PAGE, Nullable<int> i_PAGESIZE)
        {
            var s_SEARCHGUBUNParameter = s_SEARCHGUBUN != null ?
                new ObjectParameter("S_SEARCHGUBUN", s_SEARCHGUBUN) :
                new ObjectParameter("S_SEARCHGUBUN", typeof(string));
    
            var s_SEARCHTEXTParameter = s_SEARCHTEXT != null ?
                new ObjectParameter("S_SEARCHTEXT", s_SEARCHTEXT) :
                new ObjectParameter("S_SEARCHTEXT", typeof(string));
    
            var s_STARTDATEParameter = s_STARTDATE != null ?
                new ObjectParameter("S_STARTDATE", s_STARTDATE) :
                new ObjectParameter("S_STARTDATE", typeof(string));
    
            var s_ENDDATEParameter = s_ENDDATE != null ?
                new ObjectParameter("S_ENDDATE", s_ENDDATE) :
                new ObjectParameter("S_ENDDATE", typeof(string));
    
            var i_PAGEParameter = i_PAGE.HasValue ?
                new ObjectParameter("I_PAGE", i_PAGE) :
                new ObjectParameter("I_PAGE", typeof(int));
    
            var i_PAGESIZEParameter = i_PAGESIZE.HasValue ?
                new ObjectParameter("I_PAGESIZE", i_PAGESIZE) :
                new ObjectParameter("I_PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_REPORTER_MANAGE_SELECT_Result>("Db49_Article.NUP_REPORTER_MANAGE_SELECT", s_SEARCHGUBUNParameter, s_SEARCHTEXTParameter, s_STARTDATEParameter, s_ENDDATEParameter, i_PAGEParameter, i_PAGESIZEParameter);
        }
    
        public virtual ObjectResult<NUP_MYPIN_REPORTER_SELECT_Result> NUP_MYPIN_REPORTER_SELECT(string uSER_NM, string uSER_ID)
        {
            var uSER_NMParameter = uSER_NM != null ?
                new ObjectParameter("USER_NM", uSER_NM) :
                new ObjectParameter("USER_NM", typeof(string));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_MYPIN_REPORTER_SELECT_Result>("Db49_Article.NUP_MYPIN_REPORTER_SELECT", uSER_NMParameter, uSER_IDParameter);
        }
    
        public virtual ObjectResult<NUP_REPORTER_SELECT_Result> NUP_REPORTER_SELECT(string s_SEARCHID, string s_SEARCHNAME, string s_SEARCHINITIAL, Nullable<int> i_PAGE, Nullable<int> i_PAGESIZE, string s_RANDOM)
        {
            var s_SEARCHIDParameter = s_SEARCHID != null ?
                new ObjectParameter("S_SEARCHID", s_SEARCHID) :
                new ObjectParameter("S_SEARCHID", typeof(string));
    
            var s_SEARCHNAMEParameter = s_SEARCHNAME != null ?
                new ObjectParameter("S_SEARCHNAME", s_SEARCHNAME) :
                new ObjectParameter("S_SEARCHNAME", typeof(string));
    
            var s_SEARCHINITIALParameter = s_SEARCHINITIAL != null ?
                new ObjectParameter("S_SEARCHINITIAL", s_SEARCHINITIAL) :
                new ObjectParameter("S_SEARCHINITIAL", typeof(string));
    
            var i_PAGEParameter = i_PAGE.HasValue ?
                new ObjectParameter("I_PAGE", i_PAGE) :
                new ObjectParameter("I_PAGE", typeof(int));
    
            var i_PAGESIZEParameter = i_PAGESIZE.HasValue ?
                new ObjectParameter("I_PAGESIZE", i_PAGESIZE) :
                new ObjectParameter("I_PAGESIZE", typeof(int));
    
            var s_RANDOMParameter = s_RANDOM != null ?
                new ObjectParameter("S_RANDOM", s_RANDOM) :
                new ObjectParameter("S_RANDOM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_REPORTER_SELECT_Result>("Db49_Article.NUP_REPORTER_SELECT", s_SEARCHIDParameter, s_SEARCHNAMEParameter, s_SEARCHINITIALParameter, i_PAGEParameter, i_PAGESIZEParameter, s_RANDOMParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_MAIN_LIST_Y_SELECT_Result> NUP_NEWS_MAIN_LIST_Y_SELECT(string s_NOT_ARTICLE_ID)
        {
            var s_NOT_ARTICLE_IDParameter = s_NOT_ARTICLE_ID != null ?
                new ObjectParameter("S_NOT_ARTICLE_ID", s_NOT_ARTICLE_ID) :
                new ObjectParameter("S_NOT_ARTICLE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_MAIN_LIST_Y_SELECT_Result>("Db49_Article.NUP_NEWS_MAIN_LIST_Y_SELECT", s_NOT_ARTICLE_IDParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_MAIN_MARKET_SELECT_Result> NUP_NEWS_MAIN_MARKET_SELECT(string s_SEARCHGUBUN, Nullable<int> i_TOPN, string s_NOT_ARTICLE_ID)
        {
            var s_SEARCHGUBUNParameter = s_SEARCHGUBUN != null ?
                new ObjectParameter("S_SEARCHGUBUN", s_SEARCHGUBUN) :
                new ObjectParameter("S_SEARCHGUBUN", typeof(string));
    
            var i_TOPNParameter = i_TOPN.HasValue ?
                new ObjectParameter("I_TOPN", i_TOPN) :
                new ObjectParameter("I_TOPN", typeof(int));
    
            var s_NOT_ARTICLE_IDParameter = s_NOT_ARTICLE_ID != null ?
                new ObjectParameter("S_NOT_ARTICLE_ID", s_NOT_ARTICLE_ID) :
                new ObjectParameter("S_NOT_ARTICLE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_MAIN_MARKET_SELECT_Result>("Db49_Article.NUP_NEWS_MAIN_MARKET_SELECT", s_SEARCHGUBUNParameter, i_TOPNParameter, s_NOT_ARTICLE_IDParameter);
        }
    
        public virtual ObjectResult<NUP_BROAD_MAIN_ARTICLE_SELECT_Result> NUP_BROAD_MAIN_ARTICLE_SELECT(Nullable<int> sEQ)
        {
            var sEQParameter = sEQ.HasValue ?
                new ObjectParameter("SEQ", sEQ) :
                new ObjectParameter("SEQ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_BROAD_MAIN_ARTICLE_SELECT_Result>("Db49_Article.NUP_BROAD_MAIN_ARTICLE_SELECT", sEQParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_MAIN_SECTION_SELECT_Result> NUP_NEWS_MAIN_SECTION_SELECT(string s_SEARCHGUBUN, Nullable<int> i_TOPN, string s_NOT_ARTICLE_ID)
        {
            var s_SEARCHGUBUNParameter = s_SEARCHGUBUN != null ?
                new ObjectParameter("S_SEARCHGUBUN", s_SEARCHGUBUN) :
                new ObjectParameter("S_SEARCHGUBUN", typeof(string));
    
            var i_TOPNParameter = i_TOPN.HasValue ?
                new ObjectParameter("I_TOPN", i_TOPN) :
                new ObjectParameter("I_TOPN", typeof(int));
    
            var s_NOT_ARTICLE_IDParameter = s_NOT_ARTICLE_ID != null ?
                new ObjectParameter("S_NOT_ARTICLE_ID", s_NOT_ARTICLE_ID) :
                new ObjectParameter("S_NOT_ARTICLE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_MAIN_SECTION_SELECT_Result>("Db49_Article.NUP_NEWS_MAIN_SECTION_SELECT", s_SEARCHGUBUNParameter, i_TOPNParameter, s_NOT_ARTICLE_IDParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_MAIN_CARD_SELECT_Result> NUP_NEWS_MAIN_CARD_SELECT(string s_SEARCHGUBUN, Nullable<int> i_TOPN, string s_NOT_ARTICLE_ID)
        {
            var s_SEARCHGUBUNParameter = s_SEARCHGUBUN != null ?
                new ObjectParameter("S_SEARCHGUBUN", s_SEARCHGUBUN) :
                new ObjectParameter("S_SEARCHGUBUN", typeof(string));
    
            var i_TOPNParameter = i_TOPN.HasValue ?
                new ObjectParameter("I_TOPN", i_TOPN) :
                new ObjectParameter("I_TOPN", typeof(int));
    
            var s_NOT_ARTICLE_IDParameter = s_NOT_ARTICLE_ID != null ?
                new ObjectParameter("S_NOT_ARTICLE_ID", s_NOT_ARTICLE_ID) :
                new ObjectParameter("S_NOT_ARTICLE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_MAIN_CARD_SELECT_Result>("Db49_Article.NUP_NEWS_MAIN_CARD_SELECT", s_SEARCHGUBUNParameter, i_TOPNParameter, s_NOT_ARTICLE_IDParameter);
        }
    
        public virtual ObjectResult<usp_getArticleContents_NEW_Result> usp_getArticleContents_NEW(string articleID)
        {
            var articleIDParameter = articleID != null ?
                new ObjectParameter("ArticleID", articleID) :
                new ObjectParameter("ArticleID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getArticleContents_NEW_Result>("Db49_Article.usp_getArticleContents_NEW", articleIDParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_MAIN_VOD_SELECT_Result> NUP_NEWS_MAIN_VOD_SELECT(string s_SEARCHGUBUN, Nullable<int> i_TOPN, string s_NOT_ARTICLE_ID)
        {
            var s_SEARCHGUBUNParameter = s_SEARCHGUBUN != null ?
                new ObjectParameter("S_SEARCHGUBUN", s_SEARCHGUBUN) :
                new ObjectParameter("S_SEARCHGUBUN", typeof(string));
    
            var i_TOPNParameter = i_TOPN.HasValue ?
                new ObjectParameter("I_TOPN", i_TOPN) :
                new ObjectParameter("I_TOPN", typeof(int));
    
            var s_NOT_ARTICLE_IDParameter = s_NOT_ARTICLE_ID != null ?
                new ObjectParameter("S_NOT_ARTICLE_ID", s_NOT_ARTICLE_ID) :
                new ObjectParameter("S_NOT_ARTICLE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_MAIN_VOD_SELECT_Result>("Db49_Article.NUP_NEWS_MAIN_VOD_SELECT", s_SEARCHGUBUNParameter, i_TOPNParameter, s_NOT_ARTICLE_IDParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_MAIN_ENT_SPO_SELECT_Result> NUP_NEWS_MAIN_ENT_SPO_SELECT(string s_SEARCHGUBUN, string s_NOT_ARTICLE_ID)
        {
            var s_SEARCHGUBUNParameter = s_SEARCHGUBUN != null ?
                new ObjectParameter("S_SEARCHGUBUN", s_SEARCHGUBUN) :
                new ObjectParameter("S_SEARCHGUBUN", typeof(string));
    
            var s_NOT_ARTICLE_IDParameter = s_NOT_ARTICLE_ID != null ?
                new ObjectParameter("S_NOT_ARTICLE_ID", s_NOT_ARTICLE_ID) :
                new ObjectParameter("S_NOT_ARTICLE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_MAIN_ENT_SPO_SELECT_Result>("Db49_Article.NUP_NEWS_MAIN_ENT_SPO_SELECT", s_SEARCHGUBUNParameter, s_NOT_ARTICLE_IDParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_SECTION_SELECT_Result> NUP_NEWS_SECTION_SELECT(string s_SECTIONGUBUN, string s_SEARCHTEXT, string s_WOWCODE, string s_COMPCODE, string s_STARTDATE, string s_ENDDATE, Nullable<int> i_PAGE, Nullable<int> i_PAGESIZE)
        {
            var s_SECTIONGUBUNParameter = s_SECTIONGUBUN != null ?
                new ObjectParameter("S_SECTIONGUBUN", s_SECTIONGUBUN) :
                new ObjectParameter("S_SECTIONGUBUN", typeof(string));
    
            var s_SEARCHTEXTParameter = s_SEARCHTEXT != null ?
                new ObjectParameter("S_SEARCHTEXT", s_SEARCHTEXT) :
                new ObjectParameter("S_SEARCHTEXT", typeof(string));
    
            var s_WOWCODEParameter = s_WOWCODE != null ?
                new ObjectParameter("S_WOWCODE", s_WOWCODE) :
                new ObjectParameter("S_WOWCODE", typeof(string));
    
            var s_COMPCODEParameter = s_COMPCODE != null ?
                new ObjectParameter("S_COMPCODE", s_COMPCODE) :
                new ObjectParameter("S_COMPCODE", typeof(string));
    
            var s_STARTDATEParameter = s_STARTDATE != null ?
                new ObjectParameter("S_STARTDATE", s_STARTDATE) :
                new ObjectParameter("S_STARTDATE", typeof(string));
    
            var s_ENDDATEParameter = s_ENDDATE != null ?
                new ObjectParameter("S_ENDDATE", s_ENDDATE) :
                new ObjectParameter("S_ENDDATE", typeof(string));
    
            var i_PAGEParameter = i_PAGE.HasValue ?
                new ObjectParameter("I_PAGE", i_PAGE) :
                new ObjectParameter("I_PAGE", typeof(int));
    
            var i_PAGESIZEParameter = i_PAGESIZE.HasValue ?
                new ObjectParameter("I_PAGESIZE", i_PAGESIZE) :
                new ObjectParameter("I_PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_SECTION_SELECT_Result>("Db49_Article.NUP_NEWS_SECTION_SELECT", s_SECTIONGUBUNParameter, s_SEARCHTEXTParameter, s_WOWCODEParameter, s_COMPCODEParameter, s_STARTDATEParameter, s_ENDDATEParameter, i_PAGEParameter, i_PAGESIZEParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_READ_SELECT_Result> NUP_NEWS_READ_SELECT(string s_ARTICLEID, string s_PREVARTICLEID, string s_MEDIAGUBUN)
        {
            var s_ARTICLEIDParameter = s_ARTICLEID != null ?
                new ObjectParameter("S_ARTICLEID", s_ARTICLEID) :
                new ObjectParameter("S_ARTICLEID", typeof(string));
    
            var s_PREVARTICLEIDParameter = s_PREVARTICLEID != null ?
                new ObjectParameter("S_PREVARTICLEID", s_PREVARTICLEID) :
                new ObjectParameter("S_PREVARTICLEID", typeof(string));
    
            var s_MEDIAGUBUNParameter = s_MEDIAGUBUN != null ?
                new ObjectParameter("S_MEDIAGUBUN", s_MEDIAGUBUN) :
                new ObjectParameter("S_MEDIAGUBUN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_READ_SELECT_Result>("Db49_Article.NUP_NEWS_READ_SELECT", s_ARTICLEIDParameter, s_PREVARTICLEIDParameter, s_MEDIAGUBUNParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_THIS_MANY_SEE_SELECT_Result> NUP_NEWS_THIS_MANY_SEE_SELECT(string s_ARTICLEID)
        {
            var s_ARTICLEIDParameter = s_ARTICLEID != null ?
                new ObjectParameter("S_ARTICLEID", s_ARTICLEID) :
                new ObjectParameter("S_ARTICLEID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_THIS_MANY_SEE_SELECT_Result>("Db49_Article.NUP_NEWS_THIS_MANY_SEE_SELECT", s_ARTICLEIDParameter);
        }
    
        public virtual ObjectResult<NUP_TICKER_SELECT1_Result> NUP_TICKER_SELECT1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_TICKER_SELECT1_Result>("Db49_Article.NUP_TICKER_SELECT1");
        }
    
        public virtual ObjectResult<NUP_TICKER_SELECT2_Result> NUP_TICKER_SELECT2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_TICKER_SELECT2_Result>("Db49_Article.NUP_TICKER_SELECT2");
        }
    
        public virtual ObjectResult<NUP_TICKER_SELECT3_Result> NUP_TICKER_SELECT3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_TICKER_SELECT3_Result>("Db49_Article.NUP_TICKER_SELECT3");
        }
    
        public virtual ObjectResult<NUP_NEWS_MAIN_MARKET_ISSUE_SELECT_Result> NUP_NEWS_MAIN_MARKET_ISSUE_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_MAIN_MARKET_ISSUE_SELECT_Result>("Db49_Article.NUP_NEWS_MAIN_MARKET_ISSUE_SELECT");
        }
    
        public virtual ObjectResult<NUP_NEWS_MAIN_OPINION_SELECT_Result> NUP_NEWS_MAIN_OPINION_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_MAIN_OPINION_SELECT_Result>("Db49_Article.NUP_NEWS_MAIN_OPINION_SELECT");
        }
    
        public virtual int NUP_ARTICLE_LIKEIT_INSERT_UPDATE(string s_ARTICLEID, string s_LIKEITGUBUN)
        {
            var s_ARTICLEIDParameter = s_ARTICLEID != null ?
                new ObjectParameter("S_ARTICLEID", s_ARTICLEID) :
                new ObjectParameter("S_ARTICLEID", typeof(string));
    
            var s_LIKEITGUBUNParameter = s_LIKEITGUBUN != null ?
                new ObjectParameter("S_LIKEITGUBUN", s_LIKEITGUBUN) :
                new ObjectParameter("S_LIKEITGUBUN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db49_Article.NUP_ARTICLE_LIKEIT_INSERT_UPDATE", s_ARTICLEIDParameter, s_LIKEITGUBUNParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_READ_RELATION_SELECT_Result> NUP_NEWS_READ_RELATION_SELECT(string s_ARTICLE_ID, string s_NOT_ARTICLE_ID)
        {
            var s_ARTICLE_IDParameter = s_ARTICLE_ID != null ?
                new ObjectParameter("S_ARTICLE_ID", s_ARTICLE_ID) :
                new ObjectParameter("S_ARTICLE_ID", typeof(string));
    
            var s_NOT_ARTICLE_IDParameter = s_NOT_ARTICLE_ID != null ?
                new ObjectParameter("S_NOT_ARTICLE_ID", s_NOT_ARTICLE_ID) :
                new ObjectParameter("S_NOT_ARTICLE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_READ_RELATION_SELECT_Result>("Db49_Article.NUP_NEWS_READ_RELATION_SELECT", s_ARTICLE_IDParameter, s_NOT_ARTICLE_IDParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_MAIN_LAND_SELECT_Result> NUP_NEWS_MAIN_LAND_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_MAIN_LAND_SELECT_Result>("Db49_Article.NUP_NEWS_MAIN_LAND_SELECT");
        }
    
        public virtual ObjectResult<NUP_NEWS_MAIN_NEWSSTAND_SELECT_Result> NUP_NEWS_MAIN_NEWSSTAND_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_MAIN_NEWSSTAND_SELECT_Result>("Db49_Article.NUP_NEWS_MAIN_NEWSSTAND_SELECT");
        }
    
        public virtual ObjectResult<NUP_NEWS_PREV_NEXT_SELECT_Result> NUP_NEWS_PREV_NEXT_SELECT(string s_ARTICLEID, string s_SECTIONGUBUN, string s_WOWCODE, string s_CLASS, string s_SEARCHTEXT)
        {
            var s_ARTICLEIDParameter = s_ARTICLEID != null ?
                new ObjectParameter("S_ARTICLEID", s_ARTICLEID) :
                new ObjectParameter("S_ARTICLEID", typeof(string));
    
            var s_SECTIONGUBUNParameter = s_SECTIONGUBUN != null ?
                new ObjectParameter("S_SECTIONGUBUN", s_SECTIONGUBUN) :
                new ObjectParameter("S_SECTIONGUBUN", typeof(string));
    
            var s_WOWCODEParameter = s_WOWCODE != null ?
                new ObjectParameter("S_WOWCODE", s_WOWCODE) :
                new ObjectParameter("S_WOWCODE", typeof(string));
    
            var s_CLASSParameter = s_CLASS != null ?
                new ObjectParameter("S_CLASS", s_CLASS) :
                new ObjectParameter("S_CLASS", typeof(string));
    
            var s_SEARCHTEXTParameter = s_SEARCHTEXT != null ?
                new ObjectParameter("S_SEARCHTEXT", s_SEARCHTEXT) :
                new ObjectParameter("S_SEARCHTEXT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_PREV_NEXT_SELECT_Result>("Db49_Article.NUP_NEWS_PREV_NEXT_SELECT", s_ARTICLEIDParameter, s_SECTIONGUBUNParameter, s_WOWCODEParameter, s_CLASSParameter, s_SEARCHTEXTParameter);
        }
    
        public virtual ObjectResult<NUP_NEWS_SECTION_MANY_SEE_SELECT_Result> NUP_NEWS_SECTION_MANY_SEE_SELECT(string s_SECTIONGUBUN, string s_WOWCODE, Nullable<int> i_TOPN, string s_STARTDATE, string s_ENDDATE)
        {
            var s_SECTIONGUBUNParameter = s_SECTIONGUBUN != null ?
                new ObjectParameter("S_SECTIONGUBUN", s_SECTIONGUBUN) :
                new ObjectParameter("S_SECTIONGUBUN", typeof(string));
    
            var s_WOWCODEParameter = s_WOWCODE != null ?
                new ObjectParameter("S_WOWCODE", s_WOWCODE) :
                new ObjectParameter("S_WOWCODE", typeof(string));
    
            var i_TOPNParameter = i_TOPN.HasValue ?
                new ObjectParameter("I_TOPN", i_TOPN) :
                new ObjectParameter("I_TOPN", typeof(int));
    
            var s_STARTDATEParameter = s_STARTDATE != null ?
                new ObjectParameter("S_STARTDATE", s_STARTDATE) :
                new ObjectParameter("S_STARTDATE", typeof(string));
    
            var s_ENDDATEParameter = s_ENDDATE != null ?
                new ObjectParameter("S_ENDDATE", s_ENDDATE) :
                new ObjectParameter("S_ENDDATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWS_SECTION_MANY_SEE_SELECT_Result>("Db49_Article.NUP_NEWS_SECTION_MANY_SEE_SELECT", s_SECTIONGUBUNParameter, s_WOWCODEParameter, i_TOPNParameter, s_STARTDATEParameter, s_ENDDATEParameter);
        }
    
        public virtual ObjectResult<NUP_QUICKMENU_MYPIN_REPORTER_SELECT_Result> NUP_QUICKMENU_MYPIN_REPORTER_SELECT(string s_USER_ID, Nullable<int> i_TOPN)
        {
            var s_USER_IDParameter = s_USER_ID != null ?
                new ObjectParameter("S_USER_ID", s_USER_ID) :
                new ObjectParameter("S_USER_ID", typeof(string));
    
            var i_TOPNParameter = i_TOPN.HasValue ?
                new ObjectParameter("I_TOPN", i_TOPN) :
                new ObjectParameter("I_TOPN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_QUICKMENU_MYPIN_REPORTER_SELECT_Result>("Db49_Article.NUP_QUICKMENU_MYPIN_REPORTER_SELECT", s_USER_IDParameter, i_TOPNParameter);
        }
    
        public virtual int NUP_ARTICLE_LIKEIT_HANATOUR_INSERT_UPDATE(string s_ARTICLEID, string s_LIKEITGUBUN)
        {
            var s_ARTICLEIDParameter = s_ARTICLEID != null ?
                new ObjectParameter("S_ARTICLEID", s_ARTICLEID) :
                new ObjectParameter("S_ARTICLEID", typeof(string));
    
            var s_LIKEITGUBUNParameter = s_LIKEITGUBUN != null ?
                new ObjectParameter("S_LIKEITGUBUN", s_LIKEITGUBUN) :
                new ObjectParameter("S_LIKEITGUBUN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db49_Article.NUP_ARTICLE_LIKEIT_HANATOUR_INSERT_UPDATE", s_ARTICLEIDParameter, s_LIKEITGUBUNParameter);
        }
    
        public virtual ObjectResult<NUP_QUICKMENU_MYPIN_NEWS_SELECT_Result> NUP_QUICKMENU_MYPIN_NEWS_SELECT(string s_USER_ID, Nullable<int> i_TOPN)
        {
            var s_USER_IDParameter = s_USER_ID != null ?
                new ObjectParameter("S_USER_ID", s_USER_ID) :
                new ObjectParameter("S_USER_ID", typeof(string));
    
            var i_TOPNParameter = i_TOPN.HasValue ?
                new ObjectParameter("I_TOPN", i_TOPN) :
                new ObjectParameter("I_TOPN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_QUICKMENU_MYPIN_NEWS_SELECT_Result>("Db49_Article.NUP_QUICKMENU_MYPIN_NEWS_SELECT", s_USER_IDParameter, i_TOPNParameter);
        }
    
        public virtual int usp_articleClassOrderNumChangeExceptNewStand(Nullable<int> ordernum, string articleid, string adminid, string adminname)
        {
            var ordernumParameter = ordernum.HasValue ?
                new ObjectParameter("ordernum", ordernum) :
                new ObjectParameter("ordernum", typeof(int));
    
            var articleidParameter = articleid != null ?
                new ObjectParameter("articleid", articleid) :
                new ObjectParameter("articleid", typeof(string));
    
            var adminidParameter = adminid != null ?
                new ObjectParameter("adminid", adminid) :
                new ObjectParameter("adminid", typeof(string));
    
            var adminnameParameter = adminname != null ?
                new ObjectParameter("adminname", adminname) :
                new ObjectParameter("adminname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db49_Article.usp_articleClassOrderNumChangeExceptNewStand", ordernumParameter, articleidParameter, adminidParameter, adminnameParameter);
        }
    
        public virtual ObjectResult<NUP_NEWSSTAND_KEWORD_SELECT_Result> NUP_NEWSSTAND_KEWORD_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_NEWSSTAND_KEWORD_SELECT_Result>("Db49_Article.NUP_NEWSSTAND_KEWORD_SELECT");
        }
    
        public virtual int usp_tblArticleListStandKeyword_Insert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db49_Article.usp_tblArticleListStandKeyword_Insert");
        }
    
        public virtual ObjectResult<NUP_REPORTER_RECENTLY_SELECT_Result> NUP_REPORTER_RECENTLY_SELECT(string s_SEARCHTEXT)
        {
            var s_SEARCHTEXTParameter = s_SEARCHTEXT != null ?
                new ObjectParameter("S_SEARCHTEXT", s_SEARCHTEXT) :
                new ObjectParameter("S_SEARCHTEXT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_REPORTER_RECENTLY_SELECT_Result>("Db49_Article.NUP_REPORTER_RECENTLY_SELECT", s_SEARCHTEXTParameter);
        }
    
        public virtual ObjectResult<usp_WOWTVNewsCenterView_Result> usp_WOWTVNewsCenterView(string artid)
        {
            var artidParameter = artid != null ?
                new ObjectParameter("artid", artid) :
                new ObjectParameter("artid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_WOWTVNewsCenterView_Result>("Db49_Article.usp_WOWTVNewsCenterView", artidParameter);
        }
    }
}
