//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.Article
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTB_REPORTER_PROFILE
    {
        public string REPORTER_ID { get; set; }
        public string USER_ID { get; set; }
        public string IMAGE_URL { get; set; }
        public string EMAIL { get; set; }
        public string FACEBOOK_URL { get; set; }
        public string FACEBOOK_VIEW_YN { get; set; }
        public string TWITTER_URL { get; set; }
        public string TWITTER_VIEW_YN { get; set; }
        public string BLOG_URL { get; set; }
        public string BLOG_VIEW_YN { get; set; }
        public string INTRODUCTION { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public string MOD_ID { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
    }
}
