//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.Article
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticleList
    {
        public int IDX { get; set; }
        public string CompCode { get; set; }
        public string ArtID { get; set; }
        public string ArtState { get; set; }
        public Nullable<System.DateTime> inputDate { get; set; }
        public Nullable<System.DateTime> ArtDate { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public string Contents_img { get; set; }
        public string Writer { get; set; }
        public string Email { get; set; }
        public string IMGDir { get; set; }
        public string IMGFile { get; set; }
        public Nullable<bool> C_Table { get; set; }
        public string SubTitle { get; set; }
        public string Tag { get; set; }
        public string Thumbnail_type1 { get; set; }
        public string Thumbnail_type2 { get; set; }
        public string CardNews { get; set; }
        public string IMGLink { get; set; }
        public string Keywords { get; set; }
    }
}
