//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.Article
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlanArticle
    {
        public int SEQ { get; set; }
        public string TITLE { get; set; }
        public string IMG_MAIN { get; set; }
        public string IMG_NEWS { get; set; }
        public string VIEW_FLAG { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<short> ORDERN { get; set; }
        public Nullable<short> ORDERN_HOT { get; set; }
        public Nullable<System.DateTime> UP_DATE { get; set; }
        public string IMG_LIST { get; set; }
        public string IMG_BANN { get; set; }
        public string IMG_HOTISSUE { get; set; }
        public string REMRK { get; set; }
        public string VW_FROM { get; set; }
        public string VW_TO { get; set; }
        public string CLASS { get; set; }
        public Nullable<short> ORDERN_HOT_ARTICLE { get; set; }
        public Nullable<short> ORDERN_THEME { get; set; }
        public Nullable<short> ORDERN_SERIES { get; set; }
        public string REVISE_TITLE { get; set; }
        public Nullable<short> ORDERN_STORYBANK { get; set; }
        public string EXTRACTION_TEXT { get; set; }
        public string COLUMNLIST_NAME { get; set; }
        public string REG_ID { get; set; }
        public string MOD_ID { get; set; }
        public string DEL_YN { get; set; }
    }
}
