//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db22.stock
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class D22_stock : DbContext
    {
        public D22_stock()
            : base("name=D22_stock")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<view_AllStockCode> view_AllStockCode { get; set; }
        public virtual DbSet<tblMarketSummary> tblMarketSummaries { get; set; }
        public virtual DbSet<tblOnlineIndex> tblOnlineIndexes { get; set; }
        public virtual DbSet<v_index_all> v_index_all { get; set; }
        public virtual DbSet<tblOnlineSise> tblOnlineSise { get; set; }
        public virtual DbSet<tblStockBatch> tblStockBatch { get; set; }
        public virtual DbSet<TAB_MARKET_RESEARCH> TAB_MARKET_RESEARCH { get; set; }
        public virtual DbSet<t_kosdaq_part> t_kosdaq_part { get; set; }
        public virtual DbSet<t_part> t_part { get; set; }
        public virtual DbSet<NTB_SISE_MASTER> NTB_SISE_MASTER { get; set; }
        public virtual DbSet<NTB_SISE_TIME> NTB_SISE_TIME { get; set; }
        public virtual DbSet<tblMyInvestmentPartners> tblMyInvestmentPartners { get; set; }
        public virtual DbSet<tblMyFavoriteJongMok> tblMyFavoriteJongMok { get; set; }
        public virtual DbSet<TAB_MY_STOCK> TAB_MY_STOCK { get; set; }
        public virtual DbSet<tblVirtualMoney> tblVirtualMoney { get; set; }
    
        public virtual ObjectResult<usp_GetSiseCurrentKospi_Result> usp_GetSiseCurrentKospi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSiseCurrentKospi_Result>("D22_stock.usp_GetSiseCurrentKospi");
        }
    
        public virtual ObjectResult<usp_getSiseMainmergecode_Result> usp_getSiseMainmergecode()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseMainmergecode_Result>("D22_stock.usp_getSiseMainmergecode");
        }
    
        public virtual ObjectResult<usp_GetSiseCurrentKosdaq_Result> usp_GetSiseCurrentKosdaq()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSiseCurrentKosdaq_Result>("D22_stock.usp_GetSiseCurrentKosdaq");
        }
    
        public virtual ObjectResult<usp_getSiseTimeKospi_new_Result> usp_getSiseTimeKospi_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseTimeKospi_new_Result>("D22_stock.usp_getSiseTimeKospi_new");
        }
    
        public virtual ObjectResult<usp_getSiseDayKospi_new_Result> usp_getSiseDayKospi_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseDayKospi_new_Result>("D22_stock.usp_getSiseDayKospi_new");
        }
    
        public virtual ObjectResult<usp_getSiseTimeKosdaq_new_Result> usp_getSiseTimeKosdaq_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseTimeKosdaq_new_Result>("D22_stock.usp_getSiseTimeKosdaq_new");
        }
    
        public virtual ObjectResult<usp_getSiseTimeKosdaqChartData_new_Result> usp_getSiseTimeKosdaqChartData_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseTimeKosdaqChartData_new_Result>("D22_stock.usp_getSiseTimeKosdaqChartData_new");
        }
    
        public virtual ObjectResult<usp_getSiseDayKosdaq_new_Result> usp_getSiseDayKosdaq_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseDayKosdaq_new_Result>("D22_stock.usp_getSiseDayKosdaq_new");
        }
    
        public virtual ObjectResult<usp_GetSiseCurrent_Result> usp_GetSiseCurrent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSiseCurrent_Result>("D22_stock.usp_GetSiseCurrent");
        }
    
        public virtual ObjectResult<usp_getSiseTimeFut_new_Result> usp_getSiseTimeFut_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseTimeFut_new_Result>("D22_stock.usp_getSiseTimeFut_new");
        }
    
        public virtual ObjectResult<usp_getSiseDayFut_new_Result> usp_getSiseDayFut_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseDayFut_new_Result>("D22_stock.usp_getSiseDayFut_new");
        }
    
        public virtual ObjectResult<usp_getSiseTimeFutChartData_new_Result> usp_getSiseTimeFutChartData_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseTimeFutChartData_new_Result>("D22_stock.usp_getSiseTimeFutChartData_new");
        }
    
        public virtual ObjectResult<usp_GetSiseCurrentKPI_Result> usp_GetSiseCurrentKPI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSiseCurrentKPI_Result>("D22_stock.usp_GetSiseCurrentKPI");
        }
    
        public virtual ObjectResult<usp_getSiseTimeKpi200_new_Result> usp_getSiseTimeKpi200_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseTimeKpi200_new_Result>("D22_stock.usp_getSiseTimeKpi200_new");
        }
    
        public virtual ObjectResult<usp_getSiseTimeKpi200ChartData_new_Result> usp_getSiseTimeKpi200ChartData_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseTimeKpi200ChartData_new_Result>("D22_stock.usp_getSiseTimeKpi200ChartData_new");
        }
    
        public virtual ObjectResult<usp_getSiseDayKpi200_new_Result> usp_getSiseDayKpi200_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSiseDayKpi200_new_Result>("D22_stock.usp_getSiseDayKpi200_new");
        }
    
        public virtual ObjectResult<usp_wownet_ETF_stock_group_Result> usp_wownet_ETF_stock_group()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_ETF_stock_group_Result>("D22_stock.usp_wownet_ETF_stock_group");
        }
    
        public virtual ObjectResult<usp_GetStockPrice_Result> usp_GetStockPrice(string serchkey)
        {
            var serchkeyParameter = serchkey != null ?
                new ObjectParameter("serchkey", serchkey) :
                new ObjectParameter("serchkey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetStockPrice_Result>("D22_stock.usp_GetStockPrice", serchkeyParameter);
        }
    
        public virtual ObjectResult<usp_web_getDomesticIndex_Result> usp_web_getDomesticIndex(string class_1, string class_2)
        {
            var class_1Parameter = class_1 != null ?
                new ObjectParameter("Class_1", class_1) :
                new ObjectParameter("Class_1", typeof(string));
    
            var class_2Parameter = class_2 != null ?
                new ObjectParameter("Class_2", class_2) :
                new ObjectParameter("Class_2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getDomesticIndex_Result>("D22_stock.usp_web_getDomesticIndex", class_1Parameter, class_2Parameter);
        }
    
        public virtual ObjectResult<usp_GetIndustryDetail_Result> usp_GetIndustryDetail(string market, string partCode)
        {
            var marketParameter = market != null ?
                new ObjectParameter("Market", market) :
                new ObjectParameter("Market", typeof(string));
    
            var partCodeParameter = partCode != null ?
                new ObjectParameter("PartCode", partCode) :
                new ObjectParameter("PartCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetIndustryDetail_Result>("D22_stock.usp_GetIndustryDetail", marketParameter, partCodeParameter);
        }
    
        public virtual ObjectResult<usp_GetIndustryState_Result> usp_GetIndustryState(string market, string orderby, string targetDT)
        {
            var marketParameter = market != null ?
                new ObjectParameter("Market", market) :
                new ObjectParameter("Market", typeof(string));
    
            var orderbyParameter = orderby != null ?
                new ObjectParameter("Orderby", orderby) :
                new ObjectParameter("Orderby", typeof(string));
    
            var targetDTParameter = targetDT != null ?
                new ObjectParameter("TargetDT", targetDT) :
                new ObjectParameter("TargetDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetIndustryState_Result>("D22_stock.usp_GetIndustryState", marketParameter, orderbyParameter, targetDTParameter);
        }
    
        public virtual ObjectResult<usp_web_getDomesticIndustryIndex_Result> usp_web_getDomesticIndustryIndex(string market, string partCode)
        {
            var marketParameter = market != null ?
                new ObjectParameter("Market", market) :
                new ObjectParameter("Market", typeof(string));
    
            var partCodeParameter = partCode != null ?
                new ObjectParameter("PartCode", partCode) :
                new ObjectParameter("PartCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getDomesticIndustryIndex_Result>("D22_stock.usp_web_getDomesticIndustryIndex", marketParameter, partCodeParameter);
        }
    
        public virtual ObjectResult<usp_GetThemaJisu_Result> usp_GetThemaJisu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetThemaJisu_Result>("D22_stock.usp_GetThemaJisu");
        }
    
        public virtual ObjectResult<usp_GetThemaOnline_Result> usp_GetThemaOnline(Nullable<int> partNum)
        {
            var partNumParameter = partNum.HasValue ?
                new ObjectParameter("PartNum", partNum) :
                new ObjectParameter("PartNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetThemaOnline_Result>("D22_stock.usp_GetThemaOnline", partNumParameter);
        }
    
        public virtual ObjectResult<usp_wownet_usa_index_hour_Result> usp_wownet_usa_index_hour(string group)
        {
            var groupParameter = group != null ?
                new ObjectParameter("group", group) :
                new ObjectParameter("group", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_usa_index_hour_Result>("D22_stock.usp_wownet_usa_index_hour", groupParameter);
        }
    
        public virtual ObjectResult<usp_wownet_usa_index_history_Result> usp_wownet_usa_index_history(string group)
        {
            var groupParameter = group != null ?
                new ObjectParameter("group", group) :
                new ObjectParameter("group", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_usa_index_history_Result>("D22_stock.usp_wownet_usa_index_history", groupParameter);
        }
    
        public virtual ObjectResult<usp_wownet_Asia_Index_history_Result> usp_wownet_Asia_Index_history(string symbol)
        {
            var symbolParameter = symbol != null ?
                new ObjectParameter("Symbol", symbol) :
                new ObjectParameter("Symbol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_Asia_Index_history_Result>("D22_stock.usp_wownet_Asia_Index_history", symbolParameter);
        }
    
        public virtual ObjectResult<usp_wownet_Asia_Index_hour_Result> usp_wownet_Asia_Index_hour(string symbol)
        {
            var symbolParameter = symbol != null ?
                new ObjectParameter("Symbol", symbol) :
                new ObjectParameter("Symbol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_Asia_Index_hour_Result>("D22_stock.usp_wownet_Asia_Index_hour", symbolParameter);
        }
    
        public virtual ObjectResult<usp_wownet_Asia_Index_online_Result> usp_wownet_Asia_Index_online(string symbol)
        {
            var symbolParameter = symbol != null ?
                new ObjectParameter("Symbol", symbol) :
                new ObjectParameter("Symbol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_Asia_Index_online_Result>("D22_stock.usp_wownet_Asia_Index_online", symbolParameter);
        }
    
        public virtual ObjectResult<usp_web_GetSiseStockPlus_Result> usp_web_GetSiseStockPlus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_GetSiseStockPlus_Result>("D22_stock.usp_web_GetSiseStockPlus");
        }
    
        public virtual ObjectResult<usp_web_GetSiseStockPlusK_Result> usp_web_GetSiseStockPlusK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_GetSiseStockPlusK_Result>("D22_stock.usp_web_GetSiseStockPlusK");
        }
    
        public virtual ObjectResult<usp_web_usa_stock_group_Result> usp_web_usa_stock_group(string group)
        {
            var groupParameter = group != null ?
                new ObjectParameter("group", group) :
                new ObjectParameter("group", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_stock_group_Result>("D22_stock.usp_web_usa_stock_group", groupParameter);
        }
    
        public virtual ObjectResult<usp_wownet_usa_index_online_Result> usp_wownet_usa_index_online(string group)
        {
            var groupParameter = group != null ?
                new ObjectParameter("group", group) :
                new ObjectParameter("group", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_usa_index_online_Result>("D22_stock.usp_wownet_usa_index_online", groupParameter);
        }
    
        public virtual ObjectResult<usp_web_korea_adr_Result> usp_web_korea_adr()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_korea_adr_Result>("D22_stock.usp_web_korea_adr");
        }
    
        public virtual ObjectResult<usp_wownet_Europe_Index_history_Result> usp_wownet_Europe_Index_history(string symbol)
        {
            var symbolParameter = symbol != null ?
                new ObjectParameter("Symbol", symbol) :
                new ObjectParameter("Symbol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_Europe_Index_history_Result>("D22_stock.usp_wownet_Europe_Index_history", symbolParameter);
        }
    
        public virtual ObjectResult<usp_wownet_Europe_Index_online_Result> usp_wownet_Europe_Index_online(string symbol)
        {
            var symbolParameter = symbol != null ?
                new ObjectParameter("Symbol", symbol) :
                new ObjectParameter("Symbol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_Europe_Index_online_Result>("D22_stock.usp_wownet_Europe_Index_online", symbolParameter);
        }
    
        public virtual ObjectResult<usp_GetInvestOnline_Result> usp_GetInvestOnline()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetInvestOnline_Result>("D22_stock.usp_GetInvestOnline");
        }
    
        public virtual ObjectResult<usp_GetInvestTotal_Result> usp_GetInvestTotal(Nullable<int> fromDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetInvestTotal_Result>("D22_stock.usp_GetInvestTotal", fromDateParameter);
        }
    
        public virtual ObjectResult<USP_WOWNET_USA_DETAIL_Result> USP_WOWNET_USA_DETAIL(string pARTCODE)
        {
            var pARTCODEParameter = pARTCODE != null ?
                new ObjectParameter("PARTCODE", pARTCODE) :
                new ObjectParameter("PARTCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WOWNET_USA_DETAIL_Result>("D22_stock.USP_WOWNET_USA_DETAIL", pARTCODEParameter);
        }
    
        public virtual ObjectResult<usp_web_usa_adr_Result> usp_web_usa_adr()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_Result>("D22_stock.usp_web_usa_adr");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_dawo_energy_Result> usp_web_usa_adr_dawo_energy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_dawo_energy_Result>("D22_stock.usp_web_usa_adr_dawo_energy");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_dawo_insurance_Result> usp_web_usa_adr_dawo_insurance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_dawo_insurance_Result>("D22_stock.usp_web_usa_adr_dawo_insurance");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_dawo_media_Result> usp_web_usa_adr_dawo_media()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_dawo_media_Result>("D22_stock.usp_web_usa_adr_dawo_media");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_dawo_pharmacy_Result> usp_web_usa_adr_dawo_pharmacy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_dawo_pharmacy_Result>("D22_stock.usp_web_usa_adr_dawo_pharmacy");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_dawo_retail_Result> usp_web_usa_adr_dawo_retail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_dawo_retail_Result>("D22_stock.usp_web_usa_adr_dawo_retail");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_dawo_semiconductor_Result> usp_web_usa_adr_dawo_semiconductor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_dawo_semiconductor_Result>("D22_stock.usp_web_usa_adr_dawo_semiconductor");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_nasdaq_bio_Result> usp_web_usa_adr_nasdaq_bio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_nasdaq_bio_Result>("D22_stock.usp_web_usa_adr_nasdaq_bio");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_nasdaq_computer_Result> usp_web_usa_adr_nasdaq_computer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_nasdaq_computer_Result>("D22_stock.usp_web_usa_adr_nasdaq_computer");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_nasdaq_comunications_Result> usp_web_usa_adr_nasdaq_comunications()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_nasdaq_comunications_Result>("D22_stock.usp_web_usa_adr_nasdaq_comunications");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_nasdaq_internet_Result> usp_web_usa_adr_nasdaq_internet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_nasdaq_internet_Result>("D22_stock.usp_web_usa_adr_nasdaq_internet");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_nasdaq_network_Result> usp_web_usa_adr_nasdaq_network()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_nasdaq_network_Result>("D22_stock.usp_web_usa_adr_nasdaq_network");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_nasdaq_semiconductor_Result> usp_web_usa_adr_nasdaq_semiconductor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_nasdaq_semiconductor_Result>("D22_stock.usp_web_usa_adr_nasdaq_semiconductor");
        }
    
        public virtual ObjectResult<usp_web_usa_adr_sandp500_internet_Result> usp_web_usa_adr_sandp500_internet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_usa_adr_sandp500_internet_Result>("D22_stock.usp_web_usa_adr_sandp500_internet");
        }
    
        public virtual ObjectResult<usp_wownet_Marketindex_BankExchange_Result> usp_wownet_Marketindex_BankExchange()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_Marketindex_BankExchange_Result>("D22_stock.usp_wownet_Marketindex_BankExchange");
        }
    
        public virtual ObjectResult<usp_wownet_Marketindex_worldExchange_Result> usp_wownet_Marketindex_worldExchange()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_Marketindex_worldExchange_Result>("D22_stock.usp_wownet_Marketindex_worldExchange");
        }
    
        public virtual ObjectResult<usp_GetBestSearchOnline_TypeA_Result> usp_GetBestSearchOnline_TypeA(string targetDate)
        {
            var targetDateParameter = targetDate != null ?
                new ObjectParameter("TargetDate", targetDate) :
                new ObjectParameter("TargetDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetBestSearchOnline_TypeA_Result>("D22_stock.usp_GetBestSearchOnline_TypeA", targetDateParameter);
        }
    
        public virtual ObjectResult<usp_GetStockPrice_min_Result> usp_GetStockPrice_min(string sERCHKEY)
        {
            var sERCHKEYParameter = sERCHKEY != null ?
                new ObjectParameter("SERCHKEY", sERCHKEY) :
                new ObjectParameter("SERCHKEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetStockPrice_min_Result>("D22_stock.usp_GetStockPrice_min", sERCHKEYParameter);
        }
    
        public virtual ObjectResult<usp_web_getStockInvestorList_Result> usp_web_getStockInvestorList(string type, string stockCode)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getStockInvestorList_Result>("D22_stock.usp_web_getStockInvestorList", typeParameter, stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getStockInvestorSum_Result> usp_web_getStockInvestorSum(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getStockInvestorSum_Result>("D22_stock.usp_web_getStockInvestorSum", stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getStockPart_Result> usp_web_getStockPart(string partCode)
        {
            var partCodeParameter = partCode != null ?
                new ObjectParameter("PartCode", partCode) :
                new ObjectParameter("PartCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getStockPart_Result>("D22_stock.usp_web_getStockPart", partCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getStockThema_Result> usp_web_getStockThema(string partCode)
        {
            var partCodeParameter = partCode != null ?
                new ObjectParameter("PartCode", partCode) :
                new ObjectParameter("PartCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getStockThema_Result>("D22_stock.usp_web_getStockThema", partCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getRelativeStock_Result> usp_web_getRelativeStock(string gBN, string pART_CODE1, string pART_CODE2)
        {
            var gBNParameter = gBN != null ?
                new ObjectParameter("GBN", gBN) :
                new ObjectParameter("GBN", typeof(string));
    
            var pART_CODE1Parameter = pART_CODE1 != null ?
                new ObjectParameter("PART_CODE1", pART_CODE1) :
                new ObjectParameter("PART_CODE1", typeof(string));
    
            var pART_CODE2Parameter = pART_CODE2 != null ?
                new ObjectParameter("PART_CODE2", pART_CODE2) :
                new ObjectParameter("PART_CODE2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getRelativeStock_Result>("D22_stock.usp_web_getRelativeStock", gBNParameter, pART_CODE1Parameter, pART_CODE2Parameter);
        }
    
        public virtual ObjectResult<usp_web_getNoticeTop6List_Result> usp_web_getNoticeTop6List(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getNoticeTop6List_Result>("D22_stock.usp_web_getNoticeTop6List", stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getStockInvestorToday_Result> usp_web_getStockInvestorToday(string sTOCK_CODE, string dATA_DT)
        {
            var sTOCK_CODEParameter = sTOCK_CODE != null ?
                new ObjectParameter("STOCK_CODE", sTOCK_CODE) :
                new ObjectParameter("STOCK_CODE", typeof(string));
    
            var dATA_DTParameter = dATA_DT != null ?
                new ObjectParameter("DATA_DT", dATA_DT) :
                new ObjectParameter("DATA_DT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getStockInvestorToday_Result>("D22_stock.usp_web_getStockInvestorToday", sTOCK_CODEParameter, dATA_DTParameter);
        }
    
        public virtual ObjectResult<usp_web_getUSAIndex_Result> usp_web_getUSAIndex(string class_1, string class_2)
        {
            var class_1Parameter = class_1 != null ?
                new ObjectParameter("Class_1", class_1) :
                new ObjectParameter("Class_1", typeof(string));
    
            var class_2Parameter = class_2 != null ?
                new ObjectParameter("Class_2", class_2) :
                new ObjectParameter("Class_2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getUSAIndex_Result>("D22_stock.usp_web_getUSAIndex", class_1Parameter, class_2Parameter);
        }
    
        public virtual ObjectResult<usp_LatestStockPrice_Result> usp_LatestStockPrice(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("stockCode", stockCode) :
                new ObjectParameter("stockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_LatestStockPrice_Result>("D22_stock.usp_LatestStockPrice", stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getStockDealing5_Result> usp_web_getStockDealing5(string stockcode)
        {
            var stockcodeParameter = stockcode != null ?
                new ObjectParameter("stockcode", stockcode) :
                new ObjectParameter("stockcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getStockDealing5_Result>("D22_stock.usp_web_getStockDealing5", stockcodeParameter);
        }
    
        public virtual ObjectResult<usp_web_stock_hoga_Result> usp_web_stock_hoga(string stockcode)
        {
            var stockcodeParameter = stockcode != null ?
                new ObjectParameter("stockcode", stockcode) :
                new ObjectParameter("stockcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_stock_hoga_Result>("D22_stock.usp_web_stock_hoga", stockcodeParameter);
        }
    
        public virtual ObjectResult<usp_getDayStockPriceBand_Result> usp_getDayStockPriceBand(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getDayStockPriceBand_Result>("D22_stock.usp_getDayStockPriceBand", stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_SelectStockRecentlyDay_Result> usp_SelectStockRecentlyDay(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectStockRecentlyDay_Result>("D22_stock.usp_SelectStockRecentlyDay", stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_SelectStockRecentlyTime_Result> usp_SelectStockRecentlyTime(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectStockRecentlyTime_Result>("D22_stock.usp_SelectStockRecentlyTime", stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getNowPriceTime_Result> usp_web_getNowPriceTime(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getNowPriceTime_Result>("D22_stock.usp_web_getNowPriceTime", stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_getDailyStockPricePop_Result> usp_getDailyStockPricePop(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getDailyStockPricePop_Result>("D22_stock.usp_getDailyStockPricePop", stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getTradeTrend_Result> usp_web_getTradeTrend(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getTradeTrend_Result>("D22_stock.usp_web_getTradeTrend", stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getStockGongsi_Result> usp_web_getStockGongsi(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getStockGongsi_Result>("D22_stock.usp_web_getStockGongsi", stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getSiseUpper_Result> usp_web_getSiseUpper(string market)
        {
            var marketParameter = market != null ?
                new ObjectParameter("market", market) :
                new ObjectParameter("market", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getSiseUpper_Result>("D22_stock.usp_web_getSiseUpper", marketParameter);
        }
    
        public virtual ObjectResult<usp_web_getSiseLower_Result> usp_web_getSiseLower(string market)
        {
            var marketParameter = market != null ?
                new ObjectParameter("market", market) :
                new ObjectParameter("market", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getSiseLower_Result>("D22_stock.usp_web_getSiseLower", marketParameter);
        }
    
        public virtual ObjectResult<usp_web_getSiseMarketSum_Result1> usp_web_getSiseMarketSum(string market)
        {
            var marketParameter = market != null ?
                new ObjectParameter("market", market) :
                new ObjectParameter("market", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getSiseMarketSum_Result1>("D22_stock.usp_web_getSiseMarketSum", marketParameter);
        }
    
        public virtual ObjectResult<usp_web_getSiseForeignHold_Result> usp_web_getSiseForeignHold(string market)
        {
            var marketParameter = market != null ?
                new ObjectParameter("market", market) :
                new ObjectParameter("market", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getSiseForeignHold_Result>("D22_stock.usp_web_getSiseForeignHold", marketParameter);
        }
    
        public virtual ObjectResult<usp_web_getStockGongsiView_Result> usp_web_getStockGongsiView(string fSeq, string fDataDay, string stockCode)
        {
            var fSeqParameter = fSeq != null ?
                new ObjectParameter("fSeq", fSeq) :
                new ObjectParameter("fSeq", typeof(string));
    
            var fDataDayParameter = fDataDay != null ?
                new ObjectParameter("fDataDay", fDataDay) :
                new ObjectParameter("fDataDay", typeof(string));
    
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getStockGongsiView_Result>("D22_stock.usp_web_getStockGongsiView", fSeqParameter, fDataDayParameter, stockCodeParameter);
        }
    
        public virtual ObjectResult<usp_web_getStockHoliday_Result> usp_web_getStockHoliday(string checkDt)
        {
            var checkDtParameter = checkDt != null ?
                new ObjectParameter("CheckDt", checkDt) :
                new ObjectParameter("CheckDt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getStockHoliday_Result>("D22_stock.usp_web_getStockHoliday", checkDtParameter);
        }
    
        public virtual ObjectResult<usp_web_getExchangeTimeList_Result> usp_web_getExchangeTimeList(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getExchangeTimeList_Result>("D22_stock.usp_web_getExchangeTimeList", codeParameter);
        }
    
        public virtual ObjectResult<usp_web_clfSelectHoliday_Result> usp_web_clfSelectHoliday(string mARKET_DT, string hOLY_YN, string dEL_YN)
        {
            var mARKET_DTParameter = mARKET_DT != null ?
                new ObjectParameter("MARKET_DT", mARKET_DT) :
                new ObjectParameter("MARKET_DT", typeof(string));
    
            var hOLY_YNParameter = hOLY_YN != null ?
                new ObjectParameter("HOLY_YN", hOLY_YN) :
                new ObjectParameter("HOLY_YN", typeof(string));
    
            var dEL_YNParameter = dEL_YN != null ?
                new ObjectParameter("DEL_YN", dEL_YN) :
                new ObjectParameter("DEL_YN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_clfSelectHoliday_Result>("D22_stock.usp_web_clfSelectHoliday", mARKET_DTParameter, hOLY_YNParameter, dEL_YNParameter);
        }
    
        public virtual ObjectResult<usp_web_clfSelectOnlineIndex_Result> usp_web_clfSelectOnlineIndex()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_clfSelectOnlineIndex_Result>("D22_stock.usp_web_clfSelectOnlineIndex");
        }
    
        public virtual ObjectResult<usp_web_clfSelectOnlineItem_Result> usp_web_clfSelectOnlineItem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_clfSelectOnlineItem_Result>("D22_stock.usp_web_clfSelectOnlineItem");
        }
    
        [DbFunction("D22_stock", "FNC_GetThemaJisuTop")]
        public virtual IQueryable<FNC_GetThemaJisuTop_Result> FNC_GetThemaJisuTop(Nullable<int> weekday, Nullable<int> curHour, Nullable<int> curMin)
        {
            var weekdayParameter = weekday.HasValue ?
                new ObjectParameter("weekday", weekday) :
                new ObjectParameter("weekday", typeof(int));
    
            var curHourParameter = curHour.HasValue ?
                new ObjectParameter("curHour", curHour) :
                new ObjectParameter("curHour", typeof(int));
    
            var curMinParameter = curMin.HasValue ?
                new ObjectParameter("curMin", curMin) :
                new ObjectParameter("curMin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FNC_GetThemaJisuTop_Result>("[D22_stock].[FNC_GetThemaJisuTop](@weekday, @curHour, @curMin)", weekdayParameter, curHourParameter, curMinParameter);
        }
    
        public virtual ObjectResult<usp_web_getCurrentSearchStockList_Result> usp_web_getCurrentSearchStockList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getCurrentSearchStockList_Result>("D22_stock.usp_web_getCurrentSearchStockList");
        }
    
        public virtual ObjectResult<usp_web_getAsiaIndex_Result> usp_web_getAsiaIndex(string class_1, string class_2)
        {
            var class_1Parameter = class_1 != null ?
                new ObjectParameter("Class_1", class_1) :
                new ObjectParameter("Class_1", typeof(string));
    
            var class_2Parameter = class_2 != null ?
                new ObjectParameter("Class_2", class_2) :
                new ObjectParameter("Class_2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getAsiaIndex_Result>("D22_stock.usp_web_getAsiaIndex", class_1Parameter, class_2Parameter);
        }
    
        public virtual ObjectResult<usp_web_getVirtualMoney_Result> usp_web_getVirtualMoney()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getVirtualMoney_Result>("D22_stock.usp_web_getVirtualMoney");
        }
    
        public virtual ObjectResult<usp_web_getDomesticIndustryStock_Result> usp_web_getDomesticIndustryStock(string market, string industryCode)
        {
            var marketParameter = market != null ?
                new ObjectParameter("Market", market) :
                new ObjectParameter("Market", typeof(string));
    
            var industryCodeParameter = industryCode != null ?
                new ObjectParameter("IndustryCode", industryCode) :
                new ObjectParameter("IndustryCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getDomesticIndustryStock_Result>("D22_stock.usp_web_getDomesticIndustryStock", marketParameter, industryCodeParameter);
        }
    
        public virtual ObjectResult<usp_wownet_kpi200_stock_group_new_Result> usp_wownet_kpi200_stock_group_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wownet_kpi200_stock_group_new_Result>("D22_stock.usp_wownet_kpi200_stock_group_new");
        }
    }
}
