//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db22.stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_MARKET_RESEARCH
    {
        public int SEQ { get; set; }
        public string BCODE { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<int> REF { get; set; }
        public Nullable<int> REF_STEP { get; set; }
        public Nullable<int> REF_LEVEL { get; set; }
        public Nullable<int> READ_CNT { get; set; }
        public Nullable<int> MEMO_CNT { get; set; }
        public Nullable<int> RECOMMEND_CNT { get; set; }
        public Nullable<int> REVERSE_CNT { get; set; }
        public Nullable<int> ASTROMANCY_CNT { get; set; }
        public Nullable<int> ASTROMANCY_NUM { get; set; }
        public string VIEW_FLAG { get; set; }
        public string EMOTICON { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public string GUBUN { get; set; }
        public string SOURCE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> PUBLICITY_CNT { get; set; }
        public string MARKET_TYPE { get; set; }
        public string BUSINESS { get; set; }
        public string ISSUE { get; set; }
        public string CODE { get; set; }
        public string CNAME { get; set; }
        public string MARKET { get; set; }
        public string INVEST_OPINION { get; set; }
        public string INVEST_STANDARD { get; set; }
        public Nullable<long> END_PRICE { get; set; }
        public Nullable<long> TARGET_PRICE { get; set; }
        public string ANNOUNCE_DATE { get; set; }
        public string CLASS { get; set; }
    }
}
