//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db22.stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMyInvestmentPartners
    {
        public int seq { get; set; }
        public string userId { get; set; }
        public string name { get; set; }
        public string NickName { get; set; }
        public Nullable<short> kospiRate { get; set; }
        public Nullable<short> kosdaqRate { get; set; }
        public Nullable<short> shortItemPercent { get; set; }
        public Nullable<short> swingItemPercent { get; set; }
        public Nullable<short> longItemPercent { get; set; }
        public Nullable<short> losscutKind { get; set; }
        public Nullable<short> investAmount { get; set; }
        public Nullable<short> investKind { get; set; }
        public Nullable<short> monthlyTradeKind { get; set; }
        public Nullable<short> additionalService { get; set; }
        public string InvestPartner1 { get; set; }
        public string InvestPartner2 { get; set; }
        public string InvestPartner3 { get; set; }
        public string InvestPartner4 { get; set; }
        public string InvestPartner5 { get; set; }
        public string InvestPartner6 { get; set; }
        public string InvestPartner7 { get; set; }
        public string InvestPartner8 { get; set; }
        public string InvestPartner9 { get; set; }
        public string InvestPartner10 { get; set; }
        public string InvestPartner11 { get; set; }
        public string InvestPartner12 { get; set; }
        public string ExperiencePartner { get; set; }
        public string useExperience { get; set; }
        public string giveCoupon { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
