//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db22.stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlineSise
    {
        public string StockCode { get; set; }
        public Nullable<System.DateTime> InsertDT { get; set; }
        public string TradeTime { get; set; }
        public string Market { get; set; }
        public string MarketState { get; set; }
        public string TradeType { get; set; }
        public Nullable<int> TradePrice { get; set; }
        public string ChgType { get; set; }
        public Nullable<int> ChgPrice { get; set; }
        public Nullable<long> TradeVol { get; set; }
        public Nullable<int> OpenPrice { get; set; }
        public Nullable<int> HighPrice { get; set; }
        public Nullable<int> LowPrice { get; set; }
        public Nullable<int> TradeAvgPrice { get; set; }
        public Nullable<long> TotalVol { get; set; }
        public Nullable<long> TotalMoney { get; set; }
        public string HogaMatch { get; set; }
        public Nullable<long> LPTakeVol { get; set; }
        public Nullable<int> BidPrice_1 { get; set; }
        public Nullable<int> AskPrice_1 { get; set; }
        public string CloseType { get; set; }
        public Nullable<long> BeforeTradeVol { get; set; }
        public Nullable<long> BeforeTradeMoney { get; set; }
        public Nullable<long> BeforeBidVol { get; set; }
        public Nullable<long> BeforeAskVol { get; set; }
        public Nullable<long> AfterTradeVol { get; set; }
        public Nullable<long> AfterTradeMoney { get; set; }
        public Nullable<long> AfterBidVol { get; set; }
        public Nullable<long> AfterAskVol { get; set; }
        public Nullable<int> ForecastPrice { get; set; }
        public Nullable<long> ForecastVol { get; set; }
    }
}
