//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db22.stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlineIndex
    {
        public string Market { get; set; }
        public string Datatype { get; set; }
        public string IndustryCode { get; set; }
        public Nullable<System.DateTime> InsertDT { get; set; }
        public string TradeTime { get; set; }
        public Nullable<decimal> TradePrice { get; set; }
        public string ChgType { get; set; }
        public Nullable<decimal> ChgPrice { get; set; }
        public Nullable<int> TotalVol { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    }
}
