//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db35.chinaguide
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db35_chinaguide : DbContext
    {
        public Db35_chinaguide()
            : base("name=Db35_chinaguide")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<N_MAIN_MNG> N_MAIN_MNG { get; set; }
    
        public virtual int usp_getArticleList(Nullable<int> type, string market, string searchkey, string stockCode, string startDT, string endDT, Nullable<int> page, Nullable<int> pageSize)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            var marketParameter = market != null ?
                new ObjectParameter("Market", market) :
                new ObjectParameter("Market", typeof(string));
    
            var searchkeyParameter = searchkey != null ?
                new ObjectParameter("Searchkey", searchkey) :
                new ObjectParameter("Searchkey", typeof(string));
    
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            var startDTParameter = startDT != null ?
                new ObjectParameter("StartDT", startDT) :
                new ObjectParameter("StartDT", typeof(string));
    
            var endDTParameter = endDT != null ?
                new ObjectParameter("EndDT", endDT) :
                new ObjectParameter("EndDT", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("Page", page) :
                new ObjectParameter("Page", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getArticleList", typeParameter, marketParameter, searchkeyParameter, stockCodeParameter, startDTParameter, endDTParameter, pageParameter, pageSizeParameter);
        }
    }
}
