//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db35.chinaguide
{
    using System;
    using System.Collections.Generic;
    
    public partial class N_MAIN_MNG
    {
        public int IDX { get; set; }
        public string VIDEO_TITLE { get; set; }
        public string VIDEO_CONTENT { get; set; }
        public string HOT_TICKER1 { get; set; }
        public string HOT_TICKER2 { get; set; }
        public string TOP_NEWS { get; set; }
        public string UPDATE_U_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
