//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db90.DNRS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db90_DNRS : DbContext
    {
        public Db90_DNRS()
            : base("name=Db90_DNRS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAB_PROGRAM_LIST> TAB_PROGRAM_LIST { get; set; }
        public virtual DbSet<IMG_SCHEDULE> IMG_SCHEDULE { get; set; }
        public virtual DbSet<T_NEWS_PRG> T_NEWS_PRG { get; set; }
        public virtual DbSet<tv_program> tv_program { get; set; }
        public virtual DbSet<T_USER> T_USER { get; set; }
        public virtual DbSet<NTB_NEWS_PROGRAM> NTB_NEWS_PROGRAM { get; set; }
        public virtual DbSet<T_RUNDOWN> T_RUNDOWN { get; set; }
        public virtual DbSet<NTB_BROAD_WATCH> NTB_BROAD_WATCH { get; set; }
    
        public virtual int usp_HDVOD_setEncodingList(string broad_date, string title, string fileDir, string fileName, string bu, string programNM, string dep, string today, string content)
        {
            var broad_dateParameter = broad_date != null ?
                new ObjectParameter("Broad_date", broad_date) :
                new ObjectParameter("Broad_date", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var fileDirParameter = fileDir != null ?
                new ObjectParameter("FileDir", fileDir) :
                new ObjectParameter("FileDir", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            var buParameter = bu != null ?
                new ObjectParameter("bu", bu) :
                new ObjectParameter("bu", typeof(string));
    
            var programNMParameter = programNM != null ?
                new ObjectParameter("ProgramNM", programNM) :
                new ObjectParameter("ProgramNM", typeof(string));
    
            var depParameter = dep != null ?
                new ObjectParameter("Dep", dep) :
                new ObjectParameter("Dep", typeof(string));
    
            var todayParameter = today != null ?
                new ObjectParameter("Today", today) :
                new ObjectParameter("Today", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db90_DNRS.usp_HDVOD_setEncodingList", broad_dateParameter, titleParameter, fileDirParameter, fileNameParameter, buParameter, programNMParameter, depParameter, todayParameter, contentParameter);
        }
    
        public virtual ObjectResult<usp_HDVOD_getTodayList_Result> usp_HDVOD_getTodayList(string today)
        {
            var todayParameter = today != null ?
                new ObjectParameter("Today", today) :
                new ObjectParameter("Today", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_HDVOD_getTodayList_Result>("Db90_DNRS.usp_HDVOD_getTodayList", todayParameter);
        }
    
        public virtual ObjectResult<NUP_GetAllProgramEtcList_Result> NUP_GetAllProgramEtcList(string yEAR, Nullable<int> sTART_INDEX, Nullable<int> eND_INDEX)
        {
            var yEARParameter = yEAR != null ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(string));
    
            var sTART_INDEXParameter = sTART_INDEX.HasValue ?
                new ObjectParameter("START_INDEX", sTART_INDEX) :
                new ObjectParameter("START_INDEX", typeof(int));
    
            var eND_INDEXParameter = eND_INDEX.HasValue ?
                new ObjectParameter("END_INDEX", eND_INDEX) :
                new ObjectParameter("END_INDEX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_GetAllProgramEtcList_Result>("Db90_DNRS.NUP_GetAllProgramEtcList", yEARParameter, sTART_INDEXParameter, eND_INDEXParameter);
        }
    
        public virtual ObjectResult<NUP_GetAllProgramList_Result> NUP_GetAllProgramList(string pRG_NAME_START, string pRG_NAME_END, string yEAR, Nullable<int> sTART_INDEX, Nullable<int> eND_INDEX)
        {
            var pRG_NAME_STARTParameter = pRG_NAME_START != null ?
                new ObjectParameter("PRG_NAME_START", pRG_NAME_START) :
                new ObjectParameter("PRG_NAME_START", typeof(string));
    
            var pRG_NAME_ENDParameter = pRG_NAME_END != null ?
                new ObjectParameter("PRG_NAME_END", pRG_NAME_END) :
                new ObjectParameter("PRG_NAME_END", typeof(string));
    
            var yEARParameter = yEAR != null ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(string));
    
            var sTART_INDEXParameter = sTART_INDEX.HasValue ?
                new ObjectParameter("START_INDEX", sTART_INDEX) :
                new ObjectParameter("START_INDEX", typeof(int));
    
            var eND_INDEXParameter = eND_INDEX.HasValue ?
                new ObjectParameter("END_INDEX", eND_INDEX) :
                new ObjectParameter("END_INDEX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_GetAllProgramList_Result>("Db90_DNRS.NUP_GetAllProgramList", pRG_NAME_STARTParameter, pRG_NAME_ENDParameter, yEARParameter, sTART_INDEXParameter, eND_INDEXParameter);
        }
    
        public virtual ObjectResult<NUP_GetRandomProgramList_Result> NUP_GetRandomProgramList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_GetRandomProgramList_Result>("Db90_DNRS.NUP_GetRandomProgramList");
        }
    
        public virtual ObjectResult<NUP_GetBroadWatchList_Result2> NUP_GetBroadWatchList(string bROAD_SECTION_CODE, string iNG_YN, string bROAD_TYPE_CODE, string fAME_YN, Nullable<int> sTART_INDEX, Nullable<int> eND_INDEX)
        {
            var bROAD_SECTION_CODEParameter = bROAD_SECTION_CODE != null ?
                new ObjectParameter("BROAD_SECTION_CODE", bROAD_SECTION_CODE) :
                new ObjectParameter("BROAD_SECTION_CODE", typeof(string));
    
            var iNG_YNParameter = iNG_YN != null ?
                new ObjectParameter("ING_YN", iNG_YN) :
                new ObjectParameter("ING_YN", typeof(string));
    
            var bROAD_TYPE_CODEParameter = bROAD_TYPE_CODE != null ?
                new ObjectParameter("BROAD_TYPE_CODE", bROAD_TYPE_CODE) :
                new ObjectParameter("BROAD_TYPE_CODE", typeof(string));
    
            var fAME_YNParameter = fAME_YN != null ?
                new ObjectParameter("FAME_YN", fAME_YN) :
                new ObjectParameter("FAME_YN", typeof(string));
    
            var sTART_INDEXParameter = sTART_INDEX.HasValue ?
                new ObjectParameter("START_INDEX", sTART_INDEX) :
                new ObjectParameter("START_INDEX", typeof(int));
    
            var eND_INDEXParameter = eND_INDEX.HasValue ?
                new ObjectParameter("END_INDEX", eND_INDEX) :
                new ObjectParameter("END_INDEX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_GetBroadWatchList_Result2>("Db90_DNRS.NUP_GetBroadWatchList", bROAD_SECTION_CODEParameter, iNG_YNParameter, bROAD_TYPE_CODEParameter, fAME_YNParameter, sTART_INDEXParameter, eND_INDEXParameter);
        }
    
        public virtual ObjectResult<NUP_GetVodTodayList_Result> NUP_GetVodTodayList(string searchToday, string programCode)
        {
            var searchTodayParameter = searchToday != null ?
                new ObjectParameter("SearchToday", searchToday) :
                new ObjectParameter("SearchToday", typeof(string));
    
            var programCodeParameter = programCode != null ?
                new ObjectParameter("ProgramCode", programCode) :
                new ObjectParameter("ProgramCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_GetVodTodayList_Result>("Db90_DNRS.NUP_GetVodTodayList", searchTodayParameter, programCodeParameter);
        }
    }
}
