//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db90.DNRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMG_SCHEDULE
    {
        public string prog_id { get; set; }
        public string prog_name { get; set; }
        public string prog_content { get; set; }
        public string link_url { get; set; }
        public string img_path { get; set; }
        public string img_name { get; set; }
        public string img_name2 { get; set; }
        public string folder_name { get; set; }
        public string rebroadcast { get; set; }
        public string corner { get; set; }
        public string file_front_name { get; set; }
        public string bu { get; set; }
        public string hold_time { get; set; }
        public string now_broadcast { get; set; }
        public string web_state { get; set; }
        public int point { get; set; }
        public int runtime { get; set; }
        public string formation { get; set; }
        public string pageformat { get; set; }
        public string parentid { get; set; }
        public string sdate { get; set; }
        public string edate { get; set; }
        public string url { get; set; }
        public string bitrate { get; set; }
        public string dayName { get; set; }
        public byte AutoEnc { get; set; }
        public string SendType { get; set; }
        public bool SendFlag { get; set; }
        public string proginfo { get; set; }
    }
}
