//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db90.DNRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTB_NEWS_PROGRAM
    {
        public string SERVICE_NAME { get; set; }
        public string PUBLISH_YN { get; set; }
        public string ENCODING { get; set; }
        public string CP_NM { get; set; }
        public string PRG_CD { get; set; }
        public string PLAN_BROAD { get; set; }
        public string BROAD_TYPE_CODE { get; set; }
        public string FAME_YN { get; set; }
        public string FIRST_FREE_YN { get; set; }
        public string MAIN_VIEW_TYPE { get; set; }
        public string MAIN_BOTTOM_VIEW_YN { get; set; }
        public string ALL_PROGRAM_VIEW_YN { get; set; }
        public string BROAD_SECTION_CODE { get; set; }
    }
}
