//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db90.DNRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_NEWS_PRG
    {
        public string PRG_CD { get; set; }
        public string AREA_CD { get; set; }
        public string PRG_NM { get; set; }
        public string AREA_NM { get; set; }
        public string ANC1_ID { get; set; }
        public string ANC1_NM { get; set; }
        public string ANC2_ID { get; set; }
        public string PD_ID { get; set; }
        public string ANC2_NM { get; set; }
        public string PD_NM { get; set; }
        public string TD_ID { get; set; }
        public string TD_NM { get; set; }
        public string BRO_START { get; set; }
        public string BRO_END { get; set; }
        public string DIR { get; set; }
        public string PD2_ID { get; set; }
        public string PD2_NM { get; set; }
        public string TD2_ID { get; set; }
        public string TD2_NM { get; set; }
        public string PGMDATE { get; set; }
        public Nullable<int> PGMDAY { get; set; }
        public string DELFLAG { get; set; }
    }
}
