//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db90.DNRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RUNDOWN
    {
        public string SEQ { get; set; }
        public string AREA_CD { get; set; }
        public string RUN_DATE { get; set; }
        public string AREA_NM { get; set; }
        public string PRG_CD { get; set; }
        public string PRG_NM { get; set; }
        public string REMARKS { get; set; }
        public string RUN_START { get; set; }
        public string RUN_END { get; set; }
        public string RBO_TIME { get; set; }
        public string DAY_FLAG { get; set; }
        public string PD_ID { get; set; }
        public string PD_NM { get; set; }
        public string TD_ID { get; set; }
        public string TD_NM { get; set; }
        public string ANC1_ID { get; set; }
        public string ANC1_NM { get; set; }
        public string ANC2_ID { get; set; }
        public string ANC2_NM { get; set; }
        public string MAKE_ID { get; set; }
        public string MAKE_NM { get; set; }
        public string MAKE_DATETIME { get; set; }
        public string DELETE_ID { get; set; }
        public string DELETE_NM { get; set; }
        public string DELETE_DATETIME { get; set; }
        public string DELETE_FLAG { get; set; }
        public string B_STATE { get; set; }
        public string DIR { get; set; }
        public string ASSIGNTIME { get; set; }
        public string EDITOR_ID { get; set; }
        public string EDITOR_NM { get; set; }
        public Nullable<decimal> PLAY_RUN_SEQ { get; set; }
        public Nullable<decimal> STANDBY_RUN_SEQ { get; set; }
        public string INNING { get; set; }
        public Nullable<decimal> END_RUN_SEQ { get; set; }
        public string UPDATE_ID { get; set; }
        public string UPDATE_NM { get; set; }
        public string UPDATE_DATETIME { get; set; }
        public string PD2_ID { get; set; }
        public string PD2_NM { get; set; }
        public string TD2_ID { get; set; }
        public string TD2_NM { get; set; }
        public string PGMID { get; set; }
    }
}
