//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db90.DNRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER
    {
        public string USER_ID { get; set; }
        public string USER_NM { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string USER_PW { get; set; }
        public string DEPT_CD { get; set; }
        public string AUTHORITY_NM { get; set; }
        public string DEPT_NM { get; set; }
        public string USE_FLAG { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string EMAIL { get; set; }
        public string AREA_CD { get; set; }
        public string AREA_NM { get; set; }
        public string CB11 { get; set; }
        public string CB12 { get; set; }
        public string CB13 { get; set; }
        public string CB15 { get; set; }
        public string CB21 { get; set; }
        public string CB22 { get; set; }
        public string CB23 { get; set; }
        public string CB24 { get; set; }
        public string CB25 { get; set; }
        public string CB31 { get; set; }
        public string CB32 { get; set; }
        public string CB33 { get; set; }
        public string CB34 { get; set; }
        public string CB41 { get; set; }
        public string CB42 { get; set; }
        public string CB51 { get; set; }
        public string CB52 { get; set; }
        public string CB53 { get; set; }
        public string CB54 { get; set; }
        public string CB14 { get; set; }
        public string PRIV_ID { get; set; }
        public string DEL_FLAG { get; set; }
        public string DEL_ID { get; set; }
        public string DEL_NM { get; set; }
        public string UPDATE_ID { get; set; }
        public string UPDATE_NM { get; set; }
        public string UPDATE_DATETIME { get; set; }
        public string Filed1 { get; set; }
        public string Filed2 { get; set; }
        public string BylineName { get; set; }
    }
}
