//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db90.DNRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tv_program
    {
        public int Num { get; set; }
        public string broad_date { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public string Link { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string Ext { get; set; }
        public string FileSize { get; set; }
        public string FileorText { get; set; }
        public string WriterID { get; set; }
        public string MailAddr { get; set; }
        public string Program_Name { get; set; }
        public string Dep { get; set; }
        public Nullable<int> tStep { get; set; }
        public Nullable<int> Ref { get; set; }
        public Nullable<int> Re_Level { get; set; }
        public string UploadTime { get; set; }
        public Nullable<int> RecomNum { get; set; }
        public Nullable<int> ClickNum { get; set; }
        public Nullable<int> State { get; set; }
        public string StockCode { get; set; }
        public Nullable<int> Flag_Copy1 { get; set; }
        public Nullable<int> Flag_Copy2 { get; set; }
        public bool SendDaum { get; set; }
        public string ProgInfo { get; set; }
    }
}
