//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db16.wowfa
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOW_M_BANNER
    {
        public int nSort { get; set; }
        public string title { get; set; }
        public System.DateTime sdate { get; set; }
        public System.DateTime edate { get; set; }
        public string post_on { get; set; }
        public int post_num { get; set; }
        public string post_img { get; set; }
        public string link_url { get; set; }
        public string post_target { get; set; }
        public System.DateTime regdate { get; set; }
        public string position { get; set; }
    }
}
