//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wownet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wownetEntities : DbContext
    {
        public wownetEntities()
            : base("name=wownetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAB_STOCK_RESULT> TAB_STOCK_RESULT { get; set; }
        public virtual DbSet<TAB_STOCK_RESULT_CONNECT> TAB_STOCK_RESULT_CONNECT { get; set; }
        public virtual DbSet<TAB_STOCK_SITUATION> TAB_STOCK_SITUATION { get; set; }
    }
}
