//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wownet
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_BOARD_CONFIG_49_NET
    {
        public int SEQ { get; set; }
        public string BCODE { get; set; }
        public string GUBUN { get; set; }
        public string NAME { get; set; }
        public Nullable<byte> FILE_CNT { get; set; }
        public Nullable<bool> FILE_UPLOAD { get; set; }
        public Nullable<bool> WRITE { get; set; }
        public Nullable<bool> MEMO { get; set; }
        public Nullable<bool> REPLY { get; set; }
        public Nullable<bool> RECOMMEND { get; set; }
        public Nullable<bool> ASTROMANCY { get; set; }
        public Nullable<bool> HTML { get; set; }
        public Nullable<bool> REVERSE { get; set; }
        public Nullable<byte> WRITE_LEVEL { get; set; }
        public Nullable<byte> MEMO_LEVEL { get; set; }
        public Nullable<byte> REPLY_LEVEL { get; set; }
        public Nullable<byte> RECOMMEND_LEVEL { get; set; }
        public Nullable<byte> ASTROMANCY_LEVEL { get; set; }
        public Nullable<byte> REVERSE_LEVEL { get; set; }
        public string VIEW_FLAG { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public Nullable<bool> SCRAP { get; set; }
        public Nullable<byte> SCRAP_LEVEL { get; set; }
        public Nullable<bool> SOURCE { get; set; }
        public Nullable<bool> PUBLICITY { get; set; }
        public Nullable<bool> PRINTS { get; set; }
        public string LIST_CNT { get; set; }
        public Nullable<bool> EMAIL { get; set; }
        public Nullable<byte> PRINTS_LEVEL { get; set; }
        public Nullable<byte> EMAIL_LEVEL { get; set; }
        public Nullable<bool> ANNOUNCEMENT { get; set; }
        public Nullable<bool> ASTROMANCY_MEMO { get; set; }
        public Nullable<bool> HARDSHIP { get; set; }
        public Nullable<bool> ITEMCODE { get; set; }
    }
}
