//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wownet
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_LECTURES_SCHEDULE
    {
        public int SEQ { get; set; }
        public int MSEQ { get; set; }
        public string REGION { get; set; }
        public string PLACE { get; set; }
        public string LECTURES_DATE { get; set; }
        public string LECTURES_TIME { get; set; }
        public string LECTURER { get; set; }
        public string ROUGH_SKETCH_PATH { get; set; }
        public string Banner { get; set; }
        public Nullable<int> attendCount { get; set; }
        public Nullable<int> salesCount { get; set; }
        public Nullable<decimal> salesMoney { get; set; }
        public Nullable<decimal> refundMoney { get; set; }
        public Nullable<decimal> pureSalesMoney { get; set; }
        public Nullable<decimal> operatingFee { get; set; }
        public Nullable<decimal> rentalFee { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string ETC { get; set; }
    }
}
