//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wownet
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_SCRAP_CONTENT
    {
        public int SEQ { get; set; }
        public Nullable<int> BSEQ { get; set; }
        public string CNAME { get; set; }
        public string URL { get; set; }
        public string PRO_ID { get; set; }
        public string USER_ID { get; set; }
        public string TITLE { get; set; }
        public string REGDATE { get; set; }
        public Nullable<System.DateTime> SCRAPDATE { get; set; }
        public string ArticleID { get; set; }
    }
}
