//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wownet
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_CONSULTATION_APPLICATION
    {
        public int SEQ { get; set; }
        public Nullable<int> BSEQ { get; set; }
        public string BCODE { get; set; }
        public Nullable<byte> CAREER { get; set; }
        public Nullable<byte> SCALE { get; set; }
        public Nullable<byte> CHARACTER { get; set; }
        public Nullable<byte> GRAVITY { get; set; }
        public Nullable<byte> MAKET { get; set; }
        public Nullable<byte> RELIANCE { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string SEX { get; set; }
        public string AGE { get; set; }
        public string CODE { get; set; }
        public string CNAME { get; set; }
        public string VIEW_FLAG { get; set; }
        public string ITEM_GRAVITY { get; set; }
        public string AVERAGE { get; set; }
        public string CRITICISM { get; set; }
        public string BUY_DATE { get; set; }
        public Nullable<byte> INVESTMENT_OPTION { get; set; }
        public Nullable<int> READ_CNT { get; set; }
        public Nullable<int> RECOMMEND_CNT { get; set; }
        public string BEST_CODE { get; set; }
        public string BEST_NAME { get; set; }
        public Nullable<int> PUBLICITY_CNT { get; set; }
        public Nullable<int> REF { get; set; }
        public Nullable<int> REF_STEP { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<int> MEMO_CNT { get; set; }
        public string MY_WRITE { get; set; }
        public string FUTUREWIZ_YN { get; set; }
        public string MSN_YN { get; set; }
        public string BROOM { get; set; }
        public Nullable<int> VODID { get; set; }
        public string VODTYPE { get; set; }
        public Nullable<int> BCOST { get; set; }
        public Nullable<int> CAFE_REF { get; set; }
        public string USER_IP { get; set; }
    }
}
