//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wownet
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_LECTURES
    {
        public int SEQ { get; set; }
        public string TYPE_FLAG { get; set; }
        public string VIEW_SITE { get; set; }
        public string VIEW_FLAG { get; set; }
        public string TITLE { get; set; }
        public string SUMMARY { get; set; }
        public string CONTENTS { get; set; }
        public int EXPENSE { get; set; }
        public string MANAGER { get; set; }
        public string PHONE { get; set; }
        public string ADMIN_ID { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string IMAGE_FLAG { get; set; }
        public string IMAGE_FILE { get; set; }
        public Nullable<int> L_SEQ { get; set; }
        public string METHOD { get; set; }
        public string GUBUN { get; set; }
        public string WG_IMAGE_FILE { get; set; }
        public string MAIN_CTGR { get; set; }
        public string THUMNAIL_FILE { get; set; }
    }
}
