//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wownet
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCMSMNU_GIFT_USER
    {
        public int PKID { get; set; }
        public int EVENTID { get; set; }
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_NAME2 { get; set; }
        public string GET_USER_NAME { get; set; }
        public string PNAME { get; set; }
        public string POSTNUM { get; set; }
        public string ADDR { get; set; }
        public string TEL { get; set; }
        public string STATUS { get; set; }
        public string WIN_DATE { get; set; }
        public string SEND_DATE { get; set; }
        public string DELY_CO { get; set; }
        public string INVOICE_NUM { get; set; }
        public System.DateTime REG_DATE { get; set; }
    }
}
