//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wownet
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        public int seq { get; set; }
        public string bcode { get; set; }
        public string proId { get; set; }
        public string eventType { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string bannerImage { get; set; }
        public string linkUrl { get; set; }
        public string linkTarget { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string viewFlag { get; set; }
        public string adminId { get; set; }
        public Nullable<int> readCount { get; set; }
        public System.DateTime regdate { get; set; }
        public string VIEW_SITE { get; set; }
        public Nullable<System.DateTime> WINNER_DATE { get; set; }
        public string WIN_VIEW_FLAG { get; set; }
        public string WIN_CONTENT { get; set; }
        public string DEL_YN { get; set; }
    }
}
