//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTB_BOARD_CONTENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NTB_BOARD_CONTENT()
        {
            this.NTB_BOARD_COMMENT = new HashSet<NTB_BOARD_COMMENT>();
        }
    
        public int BOARD_CONTENT_SEQ { get; set; }
        public int BOARD_SEQ { get; set; }
        public int TOP_BOARD_CONTENT_SEQ { get; set; }
        public int UP_BOARD_CONTENT_SEQ { get; set; }
        public int SORD_ORDER { get; set; }
        public int DEPTH { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public string NOTICE_YN { get; set; }
        public string KEYWORD { get; set; }
        public string PASSWORD { get; set; }
        public string DEL_YN { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public string MOD_ID { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public string EMAIL_YN { get; set; }
        public int CONTENT_ID { get; set; }
        public string EMAIL { get; set; }
        public int READ_CNT { get; set; }
        public string COMMON_CODE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string USER_ID { get; set; }
        public string USER_PHONE { get; set; }
        public string VIEW_YN { get; set; }
        public string USER_NAME { get; set; }
        public string REPLY_YN { get; set; }
        public string AGREE_YN { get; set; }
        public string UP_COMMON_CODE { get; set; }
        public string PAGE_LINK { get; set; }
        public string BLIND_YN { get; set; }
        public string REG_IP { get; set; }
    
        public virtual NTB_BOARD NTB_BOARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NTB_BOARD_COMMENT> NTB_BOARD_COMMENT { get; set; }
    }
}
