//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTB_COMMON_CODE
    {
        public string COMMON_CODE { get; set; }
        public string UP_COMMON_CODE { get; set; }
        public string CODE_NAME { get; set; }
        public int SORT_ORDER { get; set; }
        public string CODE_VALUE1 { get; set; }
        public string CODE_VALUE2 { get; set; }
        public string CODE_VALUE3 { get; set; }
        public string CODE_VALUE4 { get; set; }
        public string CODE_VALUE5 { get; set; }
        public string ACTIVE_YN { get; set; }
        public string DEL_YN { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DATE { get; set; }
    }
}
