//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTB_PROGRAM_TEMPLATE_GROUP
    {
        public int PROGRAM_TEMPLATE_SEQ { get; set; }
        public int PROGRAM_GROUP_SEQ { get; set; }
        public int ORDER_INDEX { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
    
        public virtual NTB_PROGRAM_TEMPLATE NTB_PROGRAM_TEMPLATE { get; set; }
        public virtual NTB_PROGRAM_GROUP NTB_PROGRAM_GROUP { get; set; }
    }
}
