//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTB_ATTACH_FILE
    {
        public int ATTACH_FILE_SEQ { get; set; }
        public string TABLE_CODE { get; set; }
        public string TABLE_KEY { get; set; }
        public string USER_UPLOAD_FILE_NAME { get; set; }
        public int FILE_SIZE { get; set; }
        public string REAL_FILE_PATH { get; set; }
        public string REAL_WEB_PATH { get; set; }
        public string EXTENSION { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public string DEL_YN { get; set; }
    }
}
