//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTB_BOARD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NTB_BOARD()
        {
            this.NTB_BOARD_CONTENT = new HashSet<NTB_BOARD_CONTENT>();
        }
    
        public int BOARD_SEQ { get; set; }
        public string BOARD_TYPE_CODE { get; set; }
        public string BOARD_NAME { get; set; }
        public string TOP_NOTICE_YN { get; set; }
        public int NOTICE_COUNT { get; set; }
        public string COMMENT_YN { get; set; }
        public string REPLY_YN { get; set; }
        public string ATTACH_FILE_YN { get; set; }
        public int FILE_COUNT { get; set; }
        public string SCRAP_YN { get; set; }
        public string ACTIVE_YN { get; set; }
        public string BLIND_YN { get; set; }
        public string KEYWORD_YN { get; set; }
        public string PASSWORD_YN { get; set; }
        public string TOP_CONTENT { get; set; }
        public string BOTTOM_CONTENT { get; set; }
        public string DEL_YN { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DATE { get; set; }
        public string EMAIL_YN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NTB_BOARD_CONTENT> NTB_BOARD_CONTENT { get; set; }
    }
}
