//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTB_BROAD_LIVE
    {
        public int BROAD_LIVE_ID { get; set; }
        public string PROGRAM_NAME { get; set; }
        public System.DateTime BROAD_DATE { get; set; }
        public int START_HOUR { get; set; }
        public int START_MINUT { get; set; }
        public int END_HOUR { get; set; }
        public int END_MINUT { get; set; }
        public string YOUTUBE_URL { get; set; }
        public string YOUTUBE_STA_URL { get; set; }
        public int YOUTUBE_COUNT { get; set; }
        public int YOUTUBE_PAGE_COUNT { get; set; }
        public string AFREECA_URL { get; set; }
        public string AFREECA_STA_URL { get; set; }
        public int AFREECA_COUNT { get; set; }
        public int AFREECA_PAGE_COUNT { get; set; }
        public string KAKAO_URL { get; set; }
        public string KAKAO_STA_URL { get; set; }
        public int KAKAO_COUNT { get; set; }
        public int KAKAO_PAGE_COUNT { get; set; }
        public string FACEBOOK_URL { get; set; }
        public string FACEBOOK_STA_URL { get; set; }
        public int FACEBOOK_COUNT { get; set; }
        public int FACEBOOK_PAGE_COUNT { get; set; }
        public string PUBLISH_YN { get; set; }
        public string REMARK { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DATE { get; set; }
        public string DEL_YN { get; set; }
        public string MAIN_VOD_URL { get; set; }
    }
}
