//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_WOWEVENT
    {
        public int IDX { get; set; }
        public string E_TITLE { get; set; }
        public int E_YEAR { get; set; }
        public int E_MONTH { get; set; }
        public int E_DATE { get; set; }
        public string E_INTRO { get; set; }
        public string E_PATH { get; set; }
        public string E_IMG { get; set; }
        public string E_CONTENT { get; set; }
        public int E_COUNT { get; set; }
        public string E_VIEWYN { get; set; }
        public string E_WRITER { get; set; }
        public System.DateTime E_REGDATE { get; set; }
        public Nullable<System.DateTime> E_MODDATE { get; set; }
    }
}
