//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ANCHOR
    {
        public int SEQ { get; set; }
        public string ID { get; set; }
        public string NAME { get; set; }
        public string INTRO { get; set; }
        public string HISTORY { get; set; }
        public string PHOTO { get; set; }
        public string PGM_IDS { get; set; }
        public string PGM_NAMES { get; set; }
        public Nullable<bool> SHOW_MAIN { get; set; }
        public string REG_ID { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    }
}
