//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_TOUR_MEMBER
    {
        public int seq { get; set; }
        public Nullable<int> tourSeq { get; set; }
        public string UserName_K { get; set; }
        public string UserName_E { get; set; }
        public string IdenNo { get; set; }
        public string Company_K { get; set; }
        public string Company_E { get; set; }
        public string Depart { get; set; }
        public string JobOrder { get; set; }
        public string ZIpcode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Hphone { get; set; }
        public string Email { get; set; }
        public string PassYN { get; set; }
        public string PassDate { get; set; }
        public string PassNo { get; set; }
        public string VisaYN { get; set; }
        public string VisaDate { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> regDate { get; set; }
        public string receiptYN { get; set; }
        public string finishYN { get; set; }
        public string userid { get; set; }
    }
}
