//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_IR_CLUB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_IR_CLUB()
        {
            this.TAB_IR_CLUB_MANAGER = new HashSet<TAB_IR_CLUB_MANAGER>();
        }
    
        public int SEQ { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COSTOCK_CODE { get; set; }
        public string COMPANY_PHONE { get; set; }
        public string COMPANY_FAX { get; set; }
        public string COMPANY_LOGO { get; set; }
        public string COMPANY_ADDR { get; set; }
        public string BIZ_REG_NUMBER { get; set; }
        public string FOUNDATION_DAY { get; set; }
        public string HOMEPAGE { get; set; }
        public string INDUSTRY_TYPE { get; set; }
        public string INDUSTRY_NAME { get; set; }
        public string CEO_NAME { get; set; }
        public string CEO_BIRTH { get; set; }
        public string CEO_HPHONE { get; set; }
        public string CEO_PHONE { get; set; }
        public string CEO_EMAIL { get; set; }
        public string CEO_PHOTO { get; set; }
        public string CEO_SOCIAL_ID { get; set; }
        public string CEO_HIGH_SCHOOL { get; set; }
        public string CEO_UNIV { get; set; }
        public string CEO_POSTGRADUATE { get; set; }
        public string CEO_MASTER { get; set; }
        public string MANAGER_NAME { get; set; }
        public string MANAGER_PHONE { get; set; }
        public string MANAGER_EMAIL { get; set; }
        public string ADMISSION_REPORTER { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public string DUES_PAYMENT { get; set; }
        public string TAX_ACCOUNT { get; set; }
        public string RECEIPTS_TYPE { get; set; }
        public string VIEW_FLAG { get; set; }
        public string APPROVAL_FLAG { get; set; }
        public string REG_TYPE { get; set; }
        public string IR_VOD_URL { get; set; }
        public string CEO_VOD_URL { get; set; }
        public string COMPANY_INFORMATION { get; set; }
        public string CEO_PROFILE { get; set; }
        public Nullable<int> CAPITAL { get; set; }
        public Nullable<int> STOCK_ISSUE { get; set; }
        public Nullable<int> EMPLOYEE { get; set; }
        public string LISTED_STOCKS_DATE { get; set; }
        public Nullable<int> OFFERING_PRICE_LAST { get; set; }
        public Nullable<int> OFFERING_PRICE_CURRENT { get; set; }
        public Nullable<int> CLEAR_PROFIT_LAST { get; set; }
        public Nullable<int> CLEAR_PROFIT_CURRENT { get; set; }
        public string MAJOR_PRODUCTS_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_IR_CLUB_MANAGER> TAB_IR_CLUB_MANAGER { get; set; }
    }
}
