//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_PGM_ORDER
    {
        public int SEQ { get; set; }
        public decimal CATE_CODE { get; set; }
        public string PGM_ID { get; set; }
        public string PGM_NAME { get; set; }
        public string PGM_GUBUN { get; set; }
        public string BROAD_DATE { get; set; }
        public string BROAD_TIME { get; set; }
        public string STIME { get; set; }
        public string ETIME { get; set; }
        public string CMP_NAME { get; set; }
        public string CMP_CEO { get; set; }
        public string CMP_LIC_NO { get; set; }
        public string DPT_NAME { get; set; }
        public string CHARGE_NAME { get; set; }
        public string TEL_NO { get; set; }
        public string MOBILE_NO { get; set; }
        public string FAX_NO { get; set; }
        public string EMAIL { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public string USE_VOD { get; set; }
        public string FILE_PATH { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string CMP_ADDR { get; set; }
        public string CMP_BUSINESS { get; set; }
        public string CMP_INDUSTRY { get; set; }
        public string ZIPCODE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> ORDER_CNT { get; set; }
        public string RECEIPT { get; set; }
    }
}
