//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBCBOARD
    {
        public int SEQ { get; set; }
        public string CODE1 { get; set; }
        public string CODE2 { get; set; }
        public string TITLE { get; set; }
        public string CONTENTS { get; set; }
        public Nullable<System.DateTime> UDTDT { get; set; }
        public Nullable<int> READCNT { get; set; }
        public Nullable<int> RECOMMEND { get; set; }
        public string VIEWYN { get; set; }
        public string HOTBEST { get; set; }
        public string thumnail { get; set; }
        public string MAINNEWSYN { get; set; }
    }
}
