//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_POPUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_POPUP()
        {
            this.TAB_POPUP_EVENT_LOG = new HashSet<TAB_POPUP_EVENT_LOG>();
            this.TAB_POPUP_VIEWING_LOG = new HashSet<TAB_POPUP_VIEWING_LOG>();
        }
    
        public int SEQ { get; set; }
        public string TYPE { get; set; }
        public string TITLE { get; set; }
        public string CODES { get; set; }
        public string VIEW_FLAG { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public string ADMIN_ID { get; set; }
        public Nullable<short> POSITION_X { get; set; }
        public Nullable<short> POSITION_Y { get; set; }
        public int WIDTH { get; set; }
        public int HEIGHT { get; set; }
        public string FILE_PATH { get; set; }
        public string COOKIE_NAME { get; set; }
        public string NOTICE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string VIEW_TYPE { get; set; }
        public string VIEW_TIME { get; set; }
        public Nullable<byte> VIEW_RATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_POPUP_EVENT_LOG> TAB_POPUP_EVENT_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_POPUP_VIEWING_LOG> TAB_POPUP_VIEWING_LOG { get; set; }
    }
}
