//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_CMS_MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_CMS_MENU()
        {
            this.TAB_CMS_ADMIN = new HashSet<TAB_CMS_ADMIN>();
        }
    
        public int MSEQ { get; set; }
        public Nullable<int> PSEQ { get; set; }
        public string BCODE { get; set; }
        public string MENU_NAME { get; set; }
        public string SERVICE_URL { get; set; }
        public string URL { get; set; }
        public string SUB_CODE { get; set; }
        public Nullable<byte> DISP_ORDER { get; set; }
        public string DISP_YN { get; set; }
        public string CONT_YN { get; set; }
        public string SERVICE_DISP_YN { get; set; }
        public string MENU_ICON { get; set; }
        public string REG_ID { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string TITLE_SUB { get; set; }
        public string CONTENT_TOP { get; set; }
        public string CONTENT_BOTTOM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_CMS_ADMIN> TAB_CMS_ADMIN { get; set; }
    }
}
