//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_JOBRESUME
    {
        public int seq { get; set; }
        public string title { get; set; }
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string user_birth { get; set; }
        public string sex { get; set; }
        public string name_open { get; set; }
        public string sex_open { get; set; }
        public string birth_open { get; set; }
        public string phone_open { get; set; }
        public string sellphone_open { get; set; }
        public string addr_open { get; set; }
        public string pic_open { get; set; }
        public string education_school { get; set; }
        public string education { get; set; }
        public string education_etc { get; set; }
        public string career { get; set; }
        public string license { get; set; }
        public string lang_abl { get; set; }
        public string lang_etc { get; set; }
        public string oa_abl { get; set; }
        public string oa_etc { get; set; }
        public string oversea { get; set; }
        public string introduce { get; set; }
        public string salary { get; set; }
        public string jobclass { get; set; }
        public string file_image { get; set; }
        public string file_attach { get; set; }
        public Nullable<int> read_cnt { get; set; }
        public Nullable<int> memo_cnt { get; set; }
        public string view_flag { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
    }
}
