//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_FAQ
    {
        public int SEQ { get; set; }
        public string BCODE { get; set; }
        public string FAQ_CODE { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public int READ_CNT { get; set; }
        public Nullable<int> FAQ_CHECK { get; set; }
    }
}
