//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDaeBakChunKuk
    {
        public int seq { get; set; }
        public string cornerCode { get; set; }
        public string title { get; set; }
        public string proId { get; set; }
        public string proImg { get; set; }
        public string nickName { get; set; }
        public string investType { get; set; }
        public string broadDate { get; set; }
        public string broadTime { get; set; }
        public string howToApply { get; set; }
        public string applyFee { get; set; }
        public string recordUrl { get; set; }
        public string cafeUrl { get; set; }
        public string joinUrl { get; set; }
        public Nullable<System.DateTime> regDt { get; set; }
    }
}
