//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmediacnt
    {
        public int idx { get; set; }
        public Nullable<int> parentidx { get; set; }
        public string pcode { get; set; }
        public string lcode { get; set; }
        public string date { get; set; }
        public Nullable<int> count { get; set; }
        public string mcode { get; set; }
        public string mtitle { get; set; }
    }
}
