//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTradingStarTrade
    {
        public int seq { get; set; }
        public string cname { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> broaddt { get; set; }
        public Nullable<System.DateTime> buydt { get; set; }
        public Nullable<int> buycost { get; set; }
        public string buystate { get; set; }
        public Nullable<System.DateTime> selldt { get; set; }
        public Nullable<int> sellcost { get; set; }
        public Nullable<System.DateTime> regdt { get; set; }
        public Nullable<int> regseq { get; set; }
        public string strategybuy { get; set; }
        public string strategytarget { get; set; }
        public string strategylosscut { get; set; }
        public Nullable<double> earningRate { get; set; }
        public Nullable<double> starMark { get; set; }
        public Nullable<double> topperEarningRate { get; set; }
        public Nullable<int> goalEarningRate { get; set; }
        public Nullable<int> targetCost { get; set; }
        public Nullable<int> losscutCost { get; set; }
    }
}
