//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ARSsmsEntities : DbContext
    {
        public ARSsmsEntities()
            : base("name=ARSsmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SC_TRAN> SC_TRAN { get; set; }
    
        public virtual int USP_SC_TRAN_INSERT(string mobile, string callbackNum, string sendMsg, string trid, string trEtc1, string trEtc2, string trEtc3, string trEtc4, string trEtc5, string trEtc6)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var callbackNumParameter = callbackNum != null ?
                new ObjectParameter("callbackNum", callbackNum) :
                new ObjectParameter("callbackNum", typeof(string));
    
            var sendMsgParameter = sendMsg != null ?
                new ObjectParameter("sendMsg", sendMsg) :
                new ObjectParameter("sendMsg", typeof(string));
    
            var tridParameter = trid != null ?
                new ObjectParameter("trid", trid) :
                new ObjectParameter("trid", typeof(string));
    
            var trEtc1Parameter = trEtc1 != null ?
                new ObjectParameter("trEtc1", trEtc1) :
                new ObjectParameter("trEtc1", typeof(string));
    
            var trEtc2Parameter = trEtc2 != null ?
                new ObjectParameter("trEtc2", trEtc2) :
                new ObjectParameter("trEtc2", typeof(string));
    
            var trEtc3Parameter = trEtc3 != null ?
                new ObjectParameter("trEtc3", trEtc3) :
                new ObjectParameter("trEtc3", typeof(string));
    
            var trEtc4Parameter = trEtc4 != null ?
                new ObjectParameter("trEtc4", trEtc4) :
                new ObjectParameter("trEtc4", typeof(string));
    
            var trEtc5Parameter = trEtc5 != null ?
                new ObjectParameter("trEtc5", trEtc5) :
                new ObjectParameter("trEtc5", typeof(string));
    
            var trEtc6Parameter = trEtc6 != null ?
                new ObjectParameter("trEtc6", trEtc6) :
                new ObjectParameter("trEtc6", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_SC_TRAN_INSERT", mobileParameter, callbackNumParameter, sendMsgParameter, tridParameter, trEtc1Parameter, trEtc2Parameter, trEtc3Parameter, trEtc4Parameter, trEtc5Parameter, trEtc6Parameter);
        }
    }
}
