//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_TRAN
    {
        public int TR_NUM { get; set; }
        public System.DateTime TR_SENDDATE { get; set; }
        public string TR_ID { get; set; }
        public string TR_SENDSTAT { get; set; }
        public string TR_RSLTSTAT { get; set; }
        public string TR_MSGTYPE { get; set; }
        public string TR_PHONE { get; set; }
        public string TR_CALLBACK { get; set; }
        public Nullable<System.DateTime> TR_RSLTDATE { get; set; }
        public Nullable<System.DateTime> TR_MODIFIED { get; set; }
        public string TR_MSG { get; set; }
        public string TR_ETC1 { get; set; }
        public string TR_ETC2 { get; set; }
        public string TR_ETC3 { get; set; }
        public string TR_ETC4 { get; set; }
        public string TR_ETC5 { get; set; }
        public string TR_ETC6 { get; set; }
        public string TR_NET { get; set; }
        public string TR_ROUTEID { get; set; }
        public Nullable<System.DateTime> TR_REALSENDDATE { get; set; }
    }
}
