//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.broadcast
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db49_broadcast : DbContext
    {
        public Db49_broadcast()
            : base("name=Db49_broadcast")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NTB_PROGRAM_CAST> NTB_PROGRAM_CAST { get; set; }
        public virtual DbSet<Pro_wowList> Pro_wowList { get; set; }
        public virtual DbSet<Pro_wowWellList> Pro_wowWellList { get; set; }
        public virtual DbSet<Pro_wowListStockKing> Pro_wowListStockKing { get; set; }
        public virtual DbSet<PRO_SETOPTION> PRO_SETOPTION { get; set; }
        public virtual DbSet<Pro_wow_junmunga_broadcast> Pro_wow_junmunga_broadcast { get; set; }
        public virtual DbSet<BestStockPro> BestStockPro { get; set; }
        public virtual DbSet<export_personal_menu> export_personal_menu { get; set; }
        public virtual DbSet<EXPORT_PRODUCT> EXPORT_PRODUCT { get; set; }
    
        public virtual ObjectResult<USP_GetBroadcast1ByProId_Result> USP_GetBroadcast1ByProId(string proId)
        {
            var proIdParameter = proId != null ?
                new ObjectParameter("proId", proId) :
                new ObjectParameter("proId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetBroadcast1ByProId_Result>("Db49_broadcast.USP_GetBroadcast1ByProId", proIdParameter);
        }
    
        public virtual ObjectResult<USP_GetRecommendPro3_Result> USP_GetRecommendPro3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetRecommendPro3_Result>("Db49_broadcast.USP_GetRecommendPro3");
        }
    
        public virtual ObjectResult<USP_GetBroadcast1ByWellList_Result> USP_GetBroadcast1ByWellList(string gubun)
        {
            var gubunParameter = gubun != null ?
                new ObjectParameter("gubun", gubun) :
                new ObjectParameter("gubun", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetBroadcast1ByWellList_Result>("Db49_broadcast.USP_GetBroadcast1ByWellList", gubunParameter);
        }
    
        public virtual ObjectResult<usp_getInvestmentPartners_Result> usp_getInvestmentPartners(string proNickname1, string proNickname2, string proNickname3, string proNickname4, string proNickname5, string proNickname6, string proNickname7, string proNickname8, string proNickname9, string proNickname10, string proNickname11, string proNickname12)
        {
            var proNickname1Parameter = proNickname1 != null ?
                new ObjectParameter("proNickname1", proNickname1) :
                new ObjectParameter("proNickname1", typeof(string));
    
            var proNickname2Parameter = proNickname2 != null ?
                new ObjectParameter("proNickname2", proNickname2) :
                new ObjectParameter("proNickname2", typeof(string));
    
            var proNickname3Parameter = proNickname3 != null ?
                new ObjectParameter("proNickname3", proNickname3) :
                new ObjectParameter("proNickname3", typeof(string));
    
            var proNickname4Parameter = proNickname4 != null ?
                new ObjectParameter("proNickname4", proNickname4) :
                new ObjectParameter("proNickname4", typeof(string));
    
            var proNickname5Parameter = proNickname5 != null ?
                new ObjectParameter("proNickname5", proNickname5) :
                new ObjectParameter("proNickname5", typeof(string));
    
            var proNickname6Parameter = proNickname6 != null ?
                new ObjectParameter("proNickname6", proNickname6) :
                new ObjectParameter("proNickname6", typeof(string));
    
            var proNickname7Parameter = proNickname7 != null ?
                new ObjectParameter("proNickname7", proNickname7) :
                new ObjectParameter("proNickname7", typeof(string));
    
            var proNickname8Parameter = proNickname8 != null ?
                new ObjectParameter("proNickname8", proNickname8) :
                new ObjectParameter("proNickname8", typeof(string));
    
            var proNickname9Parameter = proNickname9 != null ?
                new ObjectParameter("proNickname9", proNickname9) :
                new ObjectParameter("proNickname9", typeof(string));
    
            var proNickname10Parameter = proNickname10 != null ?
                new ObjectParameter("proNickname10", proNickname10) :
                new ObjectParameter("proNickname10", typeof(string));
    
            var proNickname11Parameter = proNickname11 != null ?
                new ObjectParameter("proNickname11", proNickname11) :
                new ObjectParameter("proNickname11", typeof(string));
    
            var proNickname12Parameter = proNickname12 != null ?
                new ObjectParameter("proNickname12", proNickname12) :
                new ObjectParameter("proNickname12", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getInvestmentPartners_Result>("Db49_broadcast.usp_getInvestmentPartners", proNickname1Parameter, proNickname2Parameter, proNickname3Parameter, proNickname4Parameter, proNickname5Parameter, proNickname6Parameter, proNickname7Parameter, proNickname8Parameter, proNickname9Parameter, proNickname10Parameter, proNickname11Parameter, proNickname12Parameter);
        }
    
        public virtual ObjectResult<usp_web_getBestProHintStocking_Result> usp_web_getBestProHintStocking()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getBestProHintStocking_Result>("Db49_broadcast.usp_web_getBestProHintStocking");
        }
    
        public virtual ObjectResult<usp_web_getWorldProHintPartner_Result> usp_web_getWorldProHintPartner()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_web_getWorldProHintPartner_Result>("Db49_broadcast.usp_web_getWorldProHintPartner");
        }
    
        public virtual ObjectResult<usp_GetlivePro_Result> usp_GetlivePro(string memType, Nullable<int> rowCount)
        {
            var memTypeParameter = memType != null ?
                new ObjectParameter("memType", memType) :
                new ObjectParameter("memType", typeof(string));
    
            var rowCountParameter = rowCount.HasValue ?
                new ObjectParameter("rowCount", rowCount) :
                new ObjectParameter("rowCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetlivePro_Result>("Db49_broadcast.usp_GetlivePro", memTypeParameter, rowCountParameter);
        }
    }
}
