//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class export_personal_menu
    {
        public int idx { get; set; }
        public string proID { get; set; }
        public string export_id { get; set; }
        public string export_nic { get; set; }
        public string export_pro { get; set; }
        public short AddMenuCount { get; set; }
        public System.DateTime regdate { get; set; }
        public System.DateTime modydate { get; set; }
        public byte[] modyid { get; set; }
        public string export_intro { get; set; }
    }
}
