//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_wow_junmunga_broadcast
    {
        public string bRoom { get; set; }
        public string nickName { get; set; }
        public string bTitle { get; set; }
        public string bContents { get; set; }
        public string bIntroduce { get; set; }
        public string bMemType { get; set; }
        public Nullable<int> bCost { get; set; }
        public string brStartTime { get; set; }
        public string brEndTime { get; set; }
        public int brUserCount { get; set; }
        public Nullable<int> bVodCost { get; set; }
        public string Pro_id { get; set; }
        public int Num { get; set; }
        public Nullable<int> CurCount { get; set; }
        public Nullable<int> MaxCount { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> ClickNum { get; set; }
        public Nullable<int> flag { get; set; }
        public string btype { get; set; }
        public Nullable<System.DateTime> OnAirTime { get; set; }
        public Nullable<System.DateTime> MaxPeakTime { get; set; }
        public string bMemTypeCafe { get; set; }
        public string bPlayType { get; set; }
    }
}
