//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowcafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class CafeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CafeInfo()
        {
            this.CafeMemberInfo = new HashSet<CafeMemberInfo>();
        }
    
        public int CafeCode { get; set; }
        public string CafeName { get; set; }
        public string CafeExplanation { get; set; }
        public string KeyWord1 { get; set; }
        public string KeyWord2 { get; set; }
        public string KeyWord3 { get; set; }
        public int MainCode { get; set; }
        public int SubCode { get; set; }
        public string OpenFlag { get; set; }
        public string RegFlag { get; set; }
        public string RegMemFlag { get; set; }
        public string CafeDomain { get; set; }
        public string CafeRegulation { get; set; }
        public string RegulationFlag { get; set; }
        public string MainRegistFlag { get; set; }
        public System.DateTime RegDate { get; set; }
        public string Question1 { get; set; }
        public string Question2 { get; set; }
        public string Question3 { get; set; }
        public string Question4 { get; set; }
        public string Question5 { get; set; }
        public string DelFlag { get; set; }
        public string UseFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CafeMemberInfo> CafeMemberInfo { get; set; }
    }
}
