//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db49.wowcafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class CafeMemberInfo
    {
        public string UserID { get; set; }
        public int CafeCode { get; set; }
        public int GradeLevel { get; set; }
        public string NickName { get; set; }
        public string Jumin1 { get; set; }
        public string Jumin2 { get; set; }
        public string Email { get; set; }
        public string EmailOpenFlag { get; set; }
        public string Hphone { get; set; }
        public string SMSOpenFlag { get; set; }
        public string Introduction { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public Nullable<System.DateTime> LastVisitDate { get; set; }
        public string DelFlag { get; set; }
        public string ReJoin { get; set; }
        public string NameOpenLev { get; set; }
        public string SexOpenLev { get; set; }
        public string AgeOpenLev { get; set; }
        public string IntroOpenLev { get; set; }
        public string Answer1 { get; set; }
        public string Answer1OpenLev { get; set; }
        public string Answer2 { get; set; }
        public string Answer2OpenLev { get; set; }
        public string Answer3 { get; set; }
        public string Answer3OpenLev { get; set; }
        public string Answer4 { get; set; }
        public string Answer4OpenLev { get; set; }
        public string Answer5 { get; set; }
        public string Answer5OpenLev { get; set; }
        public Nullable<int> DownStep { get; set; }
        public string starclubid { get; set; }
        public string goldEmail { get; set; }
        public string goldSMS { get; set; }
        public string AddrOpenLev { get; set; }
        public Nullable<int> test { get; set; }
    
        public virtual CafeInfo CafeInfo { get; set; }
    }
}
