//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db89.wowbill
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db89_wowbill : DbContext
    {
        public Db89_wowbill()
            : base("name=Db89_wowbill")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<TblMemberBlackList> TblMemberBlackList { get; set; }
        public virtual DbSet<TblMemberIdSearchLog> TblMemberIdSearchLog { get; set; }
        public virtual DbSet<tblUser_IPIN> tblUser_IPIN { get; set; }
        public virtual DbSet<TblMemberDIDenialList> TblMemberDIDenialList { get; set; }
        public virtual DbSet<tblUser_Log> tblUser_Log { get; set; }
        public virtual DbSet<tblPost> tblPost { get; set; }
        public virtual DbSet<tblUser_FailLog> tblUser_FailLog { get; set; }
        public virtual DbSet<TBL_STOCKLOAN_CONSLT> TBL_STOCKLOAN_CONSLT { get; set; }
        public virtual DbSet<tbl_Nickname> tbl_Nickname { get; set; }
        public virtual DbSet<tblRecruit> tblRecruit { get; set; }
        public virtual DbSet<tblCodeHobby> tblCodeHobby { get; set; }
        public virtual DbSet<tblCodeInfoAcquirement> tblCodeInfoAcquirement { get; set; }
        public virtual DbSet<tblCodeInterestItem> tblCodeInterestItem { get; set; }
        public virtual DbSet<tblCodeInvestmentPeriod> tblCodeInvestmentPeriod { get; set; }
        public virtual DbSet<tblCodeInvestmentPreferenceObject> tblCodeInvestmentPreferenceObject { get; set; }
        public virtual DbSet<tblCodeInvestmentPropensity> tblCodeInvestmentPropensity { get; set; }
        public virtual DbSet<tblCodeInvestmentScale> tblCodeInvestmentScale { get; set; }
        public virtual DbSet<tblCodeJob> tblCodeJob { get; set; }
        public virtual DbSet<tblCodeStockCompany> tblCodeStockCompany { get; set; }
        public virtual DbSet<tblCodeResidingStatus> tblCodeResidingStatus { get; set; }
        public virtual DbSet<tblCodeSalary> tblCodeSalary { get; set; }
        public virtual DbSet<tblUserHistory> tblUserHistory { get; set; }
        public virtual DbSet<tblCodeSalaryDetail> tblCodeSalaryDetail { get; set; }
        public virtual DbSet<tblUserDetail> tblUserDetail { get; set; }
        public virtual DbSet<tblCodeInfoAcquirementDetail> tblCodeInfoAcquirementDetail { get; set; }
        public virtual DbSet<tblCodeInvestmentPeriodDetail> tblCodeInvestmentPeriodDetail { get; set; }
        public virtual DbSet<tblCodeInvestmentPreferenceObjectDetail> tblCodeInvestmentPreferenceObjectDetail { get; set; }
        public virtual DbSet<tblCodeInvestmentPropensityDetail> tblCodeInvestmentPropensityDetail { get; set; }
        public virtual DbSet<tblCodeInvestmentScaleDetail> tblCodeInvestmentScaleDetail { get; set; }
        public virtual DbSet<tblCodeStockCompanyDetail> tblCodeStockCompanyDetail { get; set; }
        public virtual DbSet<tblCodeInterest> tblCodeInterest { get; set; }
        public virtual DbSet<tblCodeInterestDetail> tblCodeInterestDetail { get; set; }
        public virtual DbSet<tblMemberEmailAuth> tblMemberEmailAuth { get; set; }
        public virtual DbSet<tblCodeRegistRoute> tblCodeRegistRoute { get; set; }
        public virtual DbSet<tblCodeTransactionType> tblCodeTransactionType { get; set; }
        public virtual DbSet<tblTransaction> tblTransaction { get; set; }
        public virtual DbSet<tblcoupon_Daebak> tblcoupon_Daebak { get; set; }
        public virtual DbSet<tblUserSNSKakao> tblUserSNSKakao { get; set; }
        public virtual DbSet<tblUserSNSFacebook> tblUserSNSFacebook { get; set; }
        public virtual DbSet<tblUserSNSNaver> tblUserSNSNaver { get; set; }
        public virtual DbSet<tblContent> tblContent { get; set; }
        public virtual DbSet<tblUserSMS> tblUserSMS { get; set; }
        public virtual DbSet<tblUserEmailSend> tblUserEmailSend { get; set; }
        public virtual DbSet<tblUser_approvalLog> tblUser_approvalLog { get; set; }
        public virtual DbSet<NTB_USER_LOGIN_LOG> NTB_USER_LOGIN_LOG { get; set; }
        public virtual DbSet<TblMemberPasswordHistory> TblMemberPasswordHistory { get; set; }
        public virtual DbSet<tblUserPost> tblUserPost { get; set; }
        public virtual DbSet<tblCompanyDetail> tblCompanyDetail { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_InsertContractSale(Nullable<int> money, Nullable<int> number, Nullable<int> payerNumber, string serviceId, ObjectParameter contractSaleId)
        {
            var moneyParameter = money.HasValue ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(int));
    
            var numberParameter = number.HasValue ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(int));
    
            var payerNumberParameter = payerNumber.HasValue ?
                new ObjectParameter("payerNumber", payerNumber) :
                new ObjectParameter("payerNumber", typeof(int));
    
            var serviceIdParameter = serviceId != null ?
                new ObjectParameter("serviceId", serviceId) :
                new ObjectParameter("serviceId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Db89_wowbill.sp_InsertContractSale", moneyParameter, numberParameter, payerNumberParameter, serviceIdParameter, contractSaleId);
        }
    
        public virtual int NUP_MEMBER_CREATE(string uSERID, string pASSWORD, string nAME, string sSNO, string tEL, Nullable<byte> pASSWORDCONFIRMID, string pASSWORDCONFIRMANSWER, string eMAIL, string zIPCODE, string aDDRESS, Nullable<bool> iSSENDEMAIL, string iSSENDSMS, string nICKNAME, string mOBILE, string oPTION1, string oPTION2, string cEO_NAME, string bUSINESS_ITEM, string bUSINESS_CONDITION, string bUSINESS_CATEGORY, string cORPORATION_NUMBER, Nullable<bool> lISTED, string eSTABLISHMENTANNIVERSARY, Nullable<int> lANDCENTERYN)
        {
            var uSERIDParameter = uSERID != null ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var sSNOParameter = sSNO != null ?
                new ObjectParameter("SSNO", sSNO) :
                new ObjectParameter("SSNO", typeof(string));
    
            var tELParameter = tEL != null ?
                new ObjectParameter("TEL", tEL) :
                new ObjectParameter("TEL", typeof(string));
    
            var pASSWORDCONFIRMIDParameter = pASSWORDCONFIRMID.HasValue ?
                new ObjectParameter("PASSWORDCONFIRMID", pASSWORDCONFIRMID) :
                new ObjectParameter("PASSWORDCONFIRMID", typeof(byte));
    
            var pASSWORDCONFIRMANSWERParameter = pASSWORDCONFIRMANSWER != null ?
                new ObjectParameter("PASSWORDCONFIRMANSWER", pASSWORDCONFIRMANSWER) :
                new ObjectParameter("PASSWORDCONFIRMANSWER", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var zIPCODEParameter = zIPCODE != null ?
                new ObjectParameter("ZIPCODE", zIPCODE) :
                new ObjectParameter("ZIPCODE", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var iSSENDEMAILParameter = iSSENDEMAIL.HasValue ?
                new ObjectParameter("ISSENDEMAIL", iSSENDEMAIL) :
                new ObjectParameter("ISSENDEMAIL", typeof(bool));
    
            var iSSENDSMSParameter = iSSENDSMS != null ?
                new ObjectParameter("ISSENDSMS", iSSENDSMS) :
                new ObjectParameter("ISSENDSMS", typeof(string));
    
            var nICKNAMEParameter = nICKNAME != null ?
                new ObjectParameter("NICKNAME", nICKNAME) :
                new ObjectParameter("NICKNAME", typeof(string));
    
            var mOBILEParameter = mOBILE != null ?
                new ObjectParameter("MOBILE", mOBILE) :
                new ObjectParameter("MOBILE", typeof(string));
    
            var oPTION1Parameter = oPTION1 != null ?
                new ObjectParameter("OPTION1", oPTION1) :
                new ObjectParameter("OPTION1", typeof(string));
    
            var oPTION2Parameter = oPTION2 != null ?
                new ObjectParameter("OPTION2", oPTION2) :
                new ObjectParameter("OPTION2", typeof(string));
    
            var cEO_NAMEParameter = cEO_NAME != null ?
                new ObjectParameter("CEO_NAME", cEO_NAME) :
                new ObjectParameter("CEO_NAME", typeof(string));
    
            var bUSINESS_ITEMParameter = bUSINESS_ITEM != null ?
                new ObjectParameter("BUSINESS_ITEM", bUSINESS_ITEM) :
                new ObjectParameter("BUSINESS_ITEM", typeof(string));
    
            var bUSINESS_CONDITIONParameter = bUSINESS_CONDITION != null ?
                new ObjectParameter("BUSINESS_CONDITION", bUSINESS_CONDITION) :
                new ObjectParameter("BUSINESS_CONDITION", typeof(string));
    
            var bUSINESS_CATEGORYParameter = bUSINESS_CATEGORY != null ?
                new ObjectParameter("BUSINESS_CATEGORY", bUSINESS_CATEGORY) :
                new ObjectParameter("BUSINESS_CATEGORY", typeof(string));
    
            var cORPORATION_NUMBERParameter = cORPORATION_NUMBER != null ?
                new ObjectParameter("CORPORATION_NUMBER", cORPORATION_NUMBER) :
                new ObjectParameter("CORPORATION_NUMBER", typeof(string));
    
            var lISTEDParameter = lISTED.HasValue ?
                new ObjectParameter("LISTED", lISTED) :
                new ObjectParameter("LISTED", typeof(bool));
    
            var eSTABLISHMENTANNIVERSARYParameter = eSTABLISHMENTANNIVERSARY != null ?
                new ObjectParameter("ESTABLISHMENTANNIVERSARY", eSTABLISHMENTANNIVERSARY) :
                new ObjectParameter("ESTABLISHMENTANNIVERSARY", typeof(string));
    
            var lANDCENTERYNParameter = lANDCENTERYN.HasValue ?
                new ObjectParameter("LANDCENTERYN", lANDCENTERYN) :
                new ObjectParameter("LANDCENTERYN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_MEMBER_CREATE", uSERIDParameter, pASSWORDParameter, nAMEParameter, sSNOParameter, tELParameter, pASSWORDCONFIRMIDParameter, pASSWORDCONFIRMANSWERParameter, eMAILParameter, zIPCODEParameter, aDDRESSParameter, iSSENDEMAILParameter, iSSENDSMSParameter, nICKNAMEParameter, mOBILEParameter, oPTION1Parameter, oPTION2Parameter, cEO_NAMEParameter, bUSINESS_ITEMParameter, bUSINESS_CONDITIONParameter, bUSINESS_CATEGORYParameter, cORPORATION_NUMBERParameter, lISTEDParameter, eSTABLISHMENTANNIVERSARYParameter, lANDCENTERYNParameter);
        }
    
        public virtual ObjectResult<string> NUP_MEMBER_PWD_ENC_SELECT(string pASSWORD)
        {
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Db89_wowbill.NUP_MEMBER_PWD_ENC_SELECT", pASSWORDParameter);
        }
    
        public virtual ObjectResult<tblRecruit> usp_RecruitData(string name, string ssno, string img)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var ssnoParameter = ssno != null ?
                new ObjectParameter("ssno", ssno) :
                new ObjectParameter("ssno", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblRecruit>("Db89_wowbill.usp_RecruitData", nameParameter, ssnoParameter, imgParameter);
        }
    
        public virtual ObjectResult<tblRecruit> usp_RecruitData(string name, string ssno, string img, MergeOption mergeOption)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var ssnoParameter = ssno != null ?
                new ObjectParameter("ssno", ssno) :
                new ObjectParameter("ssno", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblRecruit>("Db89_wowbill.usp_RecruitData", mergeOption, nameParameter, ssnoParameter, imgParameter);
        }
    
        public virtual ObjectResult<string> NUP_ENC_SELECT(string tYPE, string aLGORITHM, string wORD)
        {
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            var aLGORITHMParameter = aLGORITHM != null ?
                new ObjectParameter("ALGORITHM", aLGORITHM) :
                new ObjectParameter("ALGORITHM", typeof(string));
    
            var wORDParameter = wORD != null ?
                new ObjectParameter("WORD", wORD) :
                new ObjectParameter("WORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Db89_wowbill.NUP_ENC_SELECT", tYPEParameter, aLGORITHMParameter, wORDParameter);
        }
    
        public virtual int NUP_MEMBER_CREATE_IPIN(string uSERID, string nICKNAME, string pASSWORD, string nAME, string sSNO, string tEL, string mOBILE, Nullable<byte> pASSWORDCONFIRMID, string pASSWORDCONFIRMANSWER, string eMAIL, Nullable<bool> iSSENDEMAIL, string iSSENDSMS, string eMAILAD, string sMSAD, string oPTION1, string oPTION2, string zIPCODE, string aDDRESS1, string aDDRESS2, string bIRTHDATE, Nullable<bool> iSSOLAR, Nullable<bool> gENDER, string dUP_INFO, string cONN_INFO, ObjectParameter rETURN_NUMBER, ObjectParameter rETURN_MESSAGE)
        {
            var uSERIDParameter = uSERID != null ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(string));
    
            var nICKNAMEParameter = nICKNAME != null ?
                new ObjectParameter("NICKNAME", nICKNAME) :
                new ObjectParameter("NICKNAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var sSNOParameter = sSNO != null ?
                new ObjectParameter("SSNO", sSNO) :
                new ObjectParameter("SSNO", typeof(string));
    
            var tELParameter = tEL != null ?
                new ObjectParameter("TEL", tEL) :
                new ObjectParameter("TEL", typeof(string));
    
            var mOBILEParameter = mOBILE != null ?
                new ObjectParameter("MOBILE", mOBILE) :
                new ObjectParameter("MOBILE", typeof(string));
    
            var pASSWORDCONFIRMIDParameter = pASSWORDCONFIRMID.HasValue ?
                new ObjectParameter("PASSWORDCONFIRMID", pASSWORDCONFIRMID) :
                new ObjectParameter("PASSWORDCONFIRMID", typeof(byte));
    
            var pASSWORDCONFIRMANSWERParameter = pASSWORDCONFIRMANSWER != null ?
                new ObjectParameter("PASSWORDCONFIRMANSWER", pASSWORDCONFIRMANSWER) :
                new ObjectParameter("PASSWORDCONFIRMANSWER", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var iSSENDEMAILParameter = iSSENDEMAIL.HasValue ?
                new ObjectParameter("ISSENDEMAIL", iSSENDEMAIL) :
                new ObjectParameter("ISSENDEMAIL", typeof(bool));
    
            var iSSENDSMSParameter = iSSENDSMS != null ?
                new ObjectParameter("ISSENDSMS", iSSENDSMS) :
                new ObjectParameter("ISSENDSMS", typeof(string));
    
            var eMAILADParameter = eMAILAD != null ?
                new ObjectParameter("EMAILAD", eMAILAD) :
                new ObjectParameter("EMAILAD", typeof(string));
    
            var sMSADParameter = sMSAD != null ?
                new ObjectParameter("SMSAD", sMSAD) :
                new ObjectParameter("SMSAD", typeof(string));
    
            var oPTION1Parameter = oPTION1 != null ?
                new ObjectParameter("OPTION1", oPTION1) :
                new ObjectParameter("OPTION1", typeof(string));
    
            var oPTION2Parameter = oPTION2 != null ?
                new ObjectParameter("OPTION2", oPTION2) :
                new ObjectParameter("OPTION2", typeof(string));
    
            var zIPCODEParameter = zIPCODE != null ?
                new ObjectParameter("ZIPCODE", zIPCODE) :
                new ObjectParameter("ZIPCODE", typeof(string));
    
            var aDDRESS1Parameter = aDDRESS1 != null ?
                new ObjectParameter("ADDRESS1", aDDRESS1) :
                new ObjectParameter("ADDRESS1", typeof(string));
    
            var aDDRESS2Parameter = aDDRESS2 != null ?
                new ObjectParameter("ADDRESS2", aDDRESS2) :
                new ObjectParameter("ADDRESS2", typeof(string));
    
            var bIRTHDATEParameter = bIRTHDATE != null ?
                new ObjectParameter("BIRTHDATE", bIRTHDATE) :
                new ObjectParameter("BIRTHDATE", typeof(string));
    
            var iSSOLARParameter = iSSOLAR.HasValue ?
                new ObjectParameter("ISSOLAR", iSSOLAR) :
                new ObjectParameter("ISSOLAR", typeof(bool));
    
            var gENDERParameter = gENDER.HasValue ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(bool));
    
            var dUP_INFOParameter = dUP_INFO != null ?
                new ObjectParameter("DUP_INFO", dUP_INFO) :
                new ObjectParameter("DUP_INFO", typeof(string));
    
            var cONN_INFOParameter = cONN_INFO != null ?
                new ObjectParameter("CONN_INFO", cONN_INFO) :
                new ObjectParameter("CONN_INFO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_MEMBER_CREATE_IPIN", uSERIDParameter, nICKNAMEParameter, pASSWORDParameter, nAMEParameter, sSNOParameter, tELParameter, mOBILEParameter, pASSWORDCONFIRMIDParameter, pASSWORDCONFIRMANSWERParameter, eMAILParameter, iSSENDEMAILParameter, iSSENDSMSParameter, eMAILADParameter, sMSADParameter, oPTION1Parameter, oPTION2Parameter, zIPCODEParameter, aDDRESS1Parameter, aDDRESS2Parameter, bIRTHDATEParameter, iSSOLARParameter, gENDERParameter, dUP_INFOParameter, cONN_INFOParameter, rETURN_NUMBER, rETURN_MESSAGE);
        }
    
        public virtual int NUP_MEMBER_CREATE_COMPANY(string uSERID, string nICKNAME, string pASSWORD, string nAME, string sSNO, string tEL, string mOBILE, Nullable<byte> pASSWORDCONFIRMID, string pASSWORDCONFIRMANSWER, string eMAIL, Nullable<bool> iSSENDSMS, Nullable<bool> iSSENDSMSAD, Nullable<bool> iSSENDEMAIL, Nullable<bool> iSSENDEMAILAD, string oPTION1, string oPTION2, string zIPCODE, string aDDRESS, string oWNER, string bUSINESS_ITEM, string bUSINESS_CONDITION, string bUSINESS_TYPE, string cOMPANY_NO, Nullable<bool> lISTED, string eSTABLISHMENT_ANNIVERSARY, Nullable<bool> lANDCENTER, ObjectParameter rETURN_NUMBER, ObjectParameter rETURN_MESSAGE, ObjectParameter uSER_NUMBER)
        {
            var uSERIDParameter = uSERID != null ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(string));
    
            var nICKNAMEParameter = nICKNAME != null ?
                new ObjectParameter("NICKNAME", nICKNAME) :
                new ObjectParameter("NICKNAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var sSNOParameter = sSNO != null ?
                new ObjectParameter("SSNO", sSNO) :
                new ObjectParameter("SSNO", typeof(string));
    
            var tELParameter = tEL != null ?
                new ObjectParameter("TEL", tEL) :
                new ObjectParameter("TEL", typeof(string));
    
            var mOBILEParameter = mOBILE != null ?
                new ObjectParameter("MOBILE", mOBILE) :
                new ObjectParameter("MOBILE", typeof(string));
    
            var pASSWORDCONFIRMIDParameter = pASSWORDCONFIRMID.HasValue ?
                new ObjectParameter("PASSWORDCONFIRMID", pASSWORDCONFIRMID) :
                new ObjectParameter("PASSWORDCONFIRMID", typeof(byte));
    
            var pASSWORDCONFIRMANSWERParameter = pASSWORDCONFIRMANSWER != null ?
                new ObjectParameter("PASSWORDCONFIRMANSWER", pASSWORDCONFIRMANSWER) :
                new ObjectParameter("PASSWORDCONFIRMANSWER", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var iSSENDSMSParameter = iSSENDSMS.HasValue ?
                new ObjectParameter("ISSENDSMS", iSSENDSMS) :
                new ObjectParameter("ISSENDSMS", typeof(bool));
    
            var iSSENDSMSADParameter = iSSENDSMSAD.HasValue ?
                new ObjectParameter("ISSENDSMSAD", iSSENDSMSAD) :
                new ObjectParameter("ISSENDSMSAD", typeof(bool));
    
            var iSSENDEMAILParameter = iSSENDEMAIL.HasValue ?
                new ObjectParameter("ISSENDEMAIL", iSSENDEMAIL) :
                new ObjectParameter("ISSENDEMAIL", typeof(bool));
    
            var iSSENDEMAILADParameter = iSSENDEMAILAD.HasValue ?
                new ObjectParameter("ISSENDEMAILAD", iSSENDEMAILAD) :
                new ObjectParameter("ISSENDEMAILAD", typeof(bool));
    
            var oPTION1Parameter = oPTION1 != null ?
                new ObjectParameter("OPTION1", oPTION1) :
                new ObjectParameter("OPTION1", typeof(string));
    
            var oPTION2Parameter = oPTION2 != null ?
                new ObjectParameter("OPTION2", oPTION2) :
                new ObjectParameter("OPTION2", typeof(string));
    
            var zIPCODEParameter = zIPCODE != null ?
                new ObjectParameter("ZIPCODE", zIPCODE) :
                new ObjectParameter("ZIPCODE", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var oWNERParameter = oWNER != null ?
                new ObjectParameter("OWNER", oWNER) :
                new ObjectParameter("OWNER", typeof(string));
    
            var bUSINESS_ITEMParameter = bUSINESS_ITEM != null ?
                new ObjectParameter("BUSINESS_ITEM", bUSINESS_ITEM) :
                new ObjectParameter("BUSINESS_ITEM", typeof(string));
    
            var bUSINESS_CONDITIONParameter = bUSINESS_CONDITION != null ?
                new ObjectParameter("BUSINESS_CONDITION", bUSINESS_CONDITION) :
                new ObjectParameter("BUSINESS_CONDITION", typeof(string));
    
            var bUSINESS_TYPEParameter = bUSINESS_TYPE != null ?
                new ObjectParameter("BUSINESS_TYPE", bUSINESS_TYPE) :
                new ObjectParameter("BUSINESS_TYPE", typeof(string));
    
            var cOMPANY_NOParameter = cOMPANY_NO != null ?
                new ObjectParameter("COMPANY_NO", cOMPANY_NO) :
                new ObjectParameter("COMPANY_NO", typeof(string));
    
            var lISTEDParameter = lISTED.HasValue ?
                new ObjectParameter("LISTED", lISTED) :
                new ObjectParameter("LISTED", typeof(bool));
    
            var eSTABLISHMENT_ANNIVERSARYParameter = eSTABLISHMENT_ANNIVERSARY != null ?
                new ObjectParameter("ESTABLISHMENT_ANNIVERSARY", eSTABLISHMENT_ANNIVERSARY) :
                new ObjectParameter("ESTABLISHMENT_ANNIVERSARY", typeof(string));
    
            var lANDCENTERParameter = lANDCENTER.HasValue ?
                new ObjectParameter("LANDCENTER", lANDCENTER) :
                new ObjectParameter("LANDCENTER", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_MEMBER_CREATE_COMPANY", uSERIDParameter, nICKNAMEParameter, pASSWORDParameter, nAMEParameter, sSNOParameter, tELParameter, mOBILEParameter, pASSWORDCONFIRMIDParameter, pASSWORDCONFIRMANSWERParameter, eMAILParameter, iSSENDSMSParameter, iSSENDSMSADParameter, iSSENDEMAILParameter, iSSENDEMAILADParameter, oPTION1Parameter, oPTION2Parameter, zIPCODEParameter, aDDRESSParameter, oWNERParameter, bUSINESS_ITEMParameter, bUSINESS_CONDITIONParameter, bUSINESS_TYPEParameter, cOMPANY_NOParameter, lISTEDParameter, eSTABLISHMENT_ANNIVERSARYParameter, lANDCENTERParameter, rETURN_NUMBER, rETURN_MESSAGE, uSER_NUMBER);
        }
    
        public virtual int NUP_MEMBER_CREATE_SMS(string uSERID, string nICKNAME, string pASSWORD, string nAME, string sSNO, string tEL, string mOBILE, Nullable<byte> pASSWORDCONFIRMID, string pASSWORDCONFIRMANSWER, string eMAIL, Nullable<bool> iSSENDEMAIL, string iSSENDSMS, string eMAILAD, string sMSAD, string oPTION1, string oPTION2, string zIPCODE, string aDDRESS1, string aDDRESS2, string bIRTHDATE, Nullable<bool> iSSOLAR, Nullable<bool> gENDER, string dUP_INFO, string cONN_INFO, ObjectParameter rETURN_NUMBER, ObjectParameter rETURN_MESSAGE)
        {
            var uSERIDParameter = uSERID != null ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(string));
    
            var nICKNAMEParameter = nICKNAME != null ?
                new ObjectParameter("NICKNAME", nICKNAME) :
                new ObjectParameter("NICKNAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var sSNOParameter = sSNO != null ?
                new ObjectParameter("SSNO", sSNO) :
                new ObjectParameter("SSNO", typeof(string));
    
            var tELParameter = tEL != null ?
                new ObjectParameter("TEL", tEL) :
                new ObjectParameter("TEL", typeof(string));
    
            var mOBILEParameter = mOBILE != null ?
                new ObjectParameter("MOBILE", mOBILE) :
                new ObjectParameter("MOBILE", typeof(string));
    
            var pASSWORDCONFIRMIDParameter = pASSWORDCONFIRMID.HasValue ?
                new ObjectParameter("PASSWORDCONFIRMID", pASSWORDCONFIRMID) :
                new ObjectParameter("PASSWORDCONFIRMID", typeof(byte));
    
            var pASSWORDCONFIRMANSWERParameter = pASSWORDCONFIRMANSWER != null ?
                new ObjectParameter("PASSWORDCONFIRMANSWER", pASSWORDCONFIRMANSWER) :
                new ObjectParameter("PASSWORDCONFIRMANSWER", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var iSSENDEMAILParameter = iSSENDEMAIL.HasValue ?
                new ObjectParameter("ISSENDEMAIL", iSSENDEMAIL) :
                new ObjectParameter("ISSENDEMAIL", typeof(bool));
    
            var iSSENDSMSParameter = iSSENDSMS != null ?
                new ObjectParameter("ISSENDSMS", iSSENDSMS) :
                new ObjectParameter("ISSENDSMS", typeof(string));
    
            var eMAILADParameter = eMAILAD != null ?
                new ObjectParameter("EMAILAD", eMAILAD) :
                new ObjectParameter("EMAILAD", typeof(string));
    
            var sMSADParameter = sMSAD != null ?
                new ObjectParameter("SMSAD", sMSAD) :
                new ObjectParameter("SMSAD", typeof(string));
    
            var oPTION1Parameter = oPTION1 != null ?
                new ObjectParameter("OPTION1", oPTION1) :
                new ObjectParameter("OPTION1", typeof(string));
    
            var oPTION2Parameter = oPTION2 != null ?
                new ObjectParameter("OPTION2", oPTION2) :
                new ObjectParameter("OPTION2", typeof(string));
    
            var zIPCODEParameter = zIPCODE != null ?
                new ObjectParameter("ZIPCODE", zIPCODE) :
                new ObjectParameter("ZIPCODE", typeof(string));
    
            var aDDRESS1Parameter = aDDRESS1 != null ?
                new ObjectParameter("ADDRESS1", aDDRESS1) :
                new ObjectParameter("ADDRESS1", typeof(string));
    
            var aDDRESS2Parameter = aDDRESS2 != null ?
                new ObjectParameter("ADDRESS2", aDDRESS2) :
                new ObjectParameter("ADDRESS2", typeof(string));
    
            var bIRTHDATEParameter = bIRTHDATE != null ?
                new ObjectParameter("BIRTHDATE", bIRTHDATE) :
                new ObjectParameter("BIRTHDATE", typeof(string));
    
            var iSSOLARParameter = iSSOLAR.HasValue ?
                new ObjectParameter("ISSOLAR", iSSOLAR) :
                new ObjectParameter("ISSOLAR", typeof(bool));
    
            var gENDERParameter = gENDER.HasValue ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(bool));
    
            var dUP_INFOParameter = dUP_INFO != null ?
                new ObjectParameter("DUP_INFO", dUP_INFO) :
                new ObjectParameter("DUP_INFO", typeof(string));
    
            var cONN_INFOParameter = cONN_INFO != null ?
                new ObjectParameter("CONN_INFO", cONN_INFO) :
                new ObjectParameter("CONN_INFO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_MEMBER_CREATE_SMS", uSERIDParameter, nICKNAMEParameter, pASSWORDParameter, nAMEParameter, sSNOParameter, tELParameter, mOBILEParameter, pASSWORDCONFIRMIDParameter, pASSWORDCONFIRMANSWERParameter, eMAILParameter, iSSENDEMAILParameter, iSSENDSMSParameter, eMAILADParameter, sMSADParameter, oPTION1Parameter, oPTION2Parameter, zIPCODEParameter, aDDRESS1Parameter, aDDRESS2Parameter, bIRTHDATEParameter, iSSOLARParameter, gENDERParameter, dUP_INFOParameter, cONN_INFOParameter, rETURN_NUMBER, rETURN_MESSAGE);
        }
    
        public virtual ObjectResult<usp_MemberSearch_dormancy_Result> usp_MemberSearch_dormancy(string dupInfo)
        {
            var dupInfoParameter = dupInfo != null ?
                new ObjectParameter("DupInfo", dupInfo) :
                new ObjectParameter("DupInfo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MemberSearch_dormancy_Result>("Db89_wowbill.usp_MemberSearch_dormancy", dupInfoParameter);
        }
    
        public virtual int usp_MemberRestoreDormancy(Nullable<int> usernumber)
        {
            var usernumberParameter = usernumber.HasValue ?
                new ObjectParameter("usernumber", usernumber) :
                new ObjectParameter("usernumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.usp_MemberRestoreDormancy", usernumberParameter);
        }
    
        public virtual ObjectResult<usp_MemberPasswordHistoryCheck_Result> usp_MemberPasswordHistoryCheck(string userid, string setdate)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var setdateParameter = setdate != null ?
                new ObjectParameter("setdate", setdate) :
                new ObjectParameter("setdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MemberPasswordHistoryCheck_Result>("Db89_wowbill.usp_MemberPasswordHistoryCheck", useridParameter, setdateParameter);
        }
    
        public virtual ObjectResult<NUP_ADMIN_MEMBER_LIST_SELECT_Result> NUP_ADMIN_MEMBER_LIST_SELECT(Nullable<System.DateTime> rEGIST_DT_FROM, Nullable<System.DateTime> rEGIST_DT_TO, Nullable<System.DateTime> lATEST_CONNECT_DT_FROM, Nullable<System.DateTime> lATEST_CONNECT_DT_TO, string sEARCH_TYPE, string sEARCH_TEXT, Nullable<int> pAGE_INDEX, Nullable<int> pAGE_SIZE)
        {
            var rEGIST_DT_FROMParameter = rEGIST_DT_FROM.HasValue ?
                new ObjectParameter("REGIST_DT_FROM", rEGIST_DT_FROM) :
                new ObjectParameter("REGIST_DT_FROM", typeof(System.DateTime));
    
            var rEGIST_DT_TOParameter = rEGIST_DT_TO.HasValue ?
                new ObjectParameter("REGIST_DT_TO", rEGIST_DT_TO) :
                new ObjectParameter("REGIST_DT_TO", typeof(System.DateTime));
    
            var lATEST_CONNECT_DT_FROMParameter = lATEST_CONNECT_DT_FROM.HasValue ?
                new ObjectParameter("LATEST_CONNECT_DT_FROM", lATEST_CONNECT_DT_FROM) :
                new ObjectParameter("LATEST_CONNECT_DT_FROM", typeof(System.DateTime));
    
            var lATEST_CONNECT_DT_TOParameter = lATEST_CONNECT_DT_TO.HasValue ?
                new ObjectParameter("LATEST_CONNECT_DT_TO", lATEST_CONNECT_DT_TO) :
                new ObjectParameter("LATEST_CONNECT_DT_TO", typeof(System.DateTime));
    
            var sEARCH_TYPEParameter = sEARCH_TYPE != null ?
                new ObjectParameter("SEARCH_TYPE", sEARCH_TYPE) :
                new ObjectParameter("SEARCH_TYPE", typeof(string));
    
            var sEARCH_TEXTParameter = sEARCH_TEXT != null ?
                new ObjectParameter("SEARCH_TEXT", sEARCH_TEXT) :
                new ObjectParameter("SEARCH_TEXT", typeof(string));
    
            var pAGE_INDEXParameter = pAGE_INDEX.HasValue ?
                new ObjectParameter("PAGE_INDEX", pAGE_INDEX) :
                new ObjectParameter("PAGE_INDEX", typeof(int));
    
            var pAGE_SIZEParameter = pAGE_SIZE.HasValue ?
                new ObjectParameter("PAGE_SIZE", pAGE_SIZE) :
                new ObjectParameter("PAGE_SIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_ADMIN_MEMBER_LIST_SELECT_Result>("Db89_wowbill.NUP_ADMIN_MEMBER_LIST_SELECT", rEGIST_DT_FROMParameter, rEGIST_DT_TOParameter, lATEST_CONNECT_DT_FROMParameter, lATEST_CONNECT_DT_TOParameter, sEARCH_TYPEParameter, sEARCH_TEXTParameter, pAGE_INDEXParameter, pAGE_SIZEParameter);
        }
    
        public virtual ObjectResult<NUP_ADMIN_MEMBER_INFO_SELECT_Result> NUP_ADMIN_MEMBER_INFO_SELECT(Nullable<int> uSER_NUMBER)
        {
            var uSER_NUMBERParameter = uSER_NUMBER.HasValue ?
                new ObjectParameter("USER_NUMBER", uSER_NUMBER) :
                new ObjectParameter("USER_NUMBER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_ADMIN_MEMBER_INFO_SELECT_Result>("Db89_wowbill.NUP_ADMIN_MEMBER_INFO_SELECT", uSER_NUMBERParameter);
        }
    
        public virtual int NUP_ADMIN_MEMBER_INFO_UPDATE(Nullable<int> uSER_NUMBER, string uSER_SECTION, Nullable<bool> iS_SEND_EMAIL, Nullable<bool> iS_SEND_SMS, string tEL_NO, string fAX_NO, string mOBILE_NO, string zIPCODE, string aDDRESS, Nullable<byte> sALARY_ID, Nullable<byte> iNVESTMENT_PREFERENCE_OBJECT_ID, Nullable<byte> iNFO_ACQUIREMENT_ID, Nullable<byte> iNVESTMENT_PERIOD_ID, Nullable<byte> iNVESTMENT_PROPENSITY_ID, Nullable<byte> sTOCK_COMPANY_ID, Nullable<byte> iNVESTMENT_SCALE_ID, string iNTEREST_AREA, string cOMPANY_NAME, string bUSINESS_CONDITION, string bUSINESS_ITEM, string bUSINESS_NUMBER, string aDMIN_ID, ObjectParameter rETURN_NUMBER, ObjectParameter rETURN_MESSAGE)
        {
            var uSER_NUMBERParameter = uSER_NUMBER.HasValue ?
                new ObjectParameter("USER_NUMBER", uSER_NUMBER) :
                new ObjectParameter("USER_NUMBER", typeof(int));
    
            var uSER_SECTIONParameter = uSER_SECTION != null ?
                new ObjectParameter("USER_SECTION", uSER_SECTION) :
                new ObjectParameter("USER_SECTION", typeof(string));
    
            var iS_SEND_EMAILParameter = iS_SEND_EMAIL.HasValue ?
                new ObjectParameter("IS_SEND_EMAIL", iS_SEND_EMAIL) :
                new ObjectParameter("IS_SEND_EMAIL", typeof(bool));
    
            var iS_SEND_SMSParameter = iS_SEND_SMS.HasValue ?
                new ObjectParameter("IS_SEND_SMS", iS_SEND_SMS) :
                new ObjectParameter("IS_SEND_SMS", typeof(bool));
    
            var tEL_NOParameter = tEL_NO != null ?
                new ObjectParameter("TEL_NO", tEL_NO) :
                new ObjectParameter("TEL_NO", typeof(string));
    
            var fAX_NOParameter = fAX_NO != null ?
                new ObjectParameter("FAX_NO", fAX_NO) :
                new ObjectParameter("FAX_NO", typeof(string));
    
            var mOBILE_NOParameter = mOBILE_NO != null ?
                new ObjectParameter("MOBILE_NO", mOBILE_NO) :
                new ObjectParameter("MOBILE_NO", typeof(string));
    
            var zIPCODEParameter = zIPCODE != null ?
                new ObjectParameter("ZIPCODE", zIPCODE) :
                new ObjectParameter("ZIPCODE", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var sALARY_IDParameter = sALARY_ID.HasValue ?
                new ObjectParameter("SALARY_ID", sALARY_ID) :
                new ObjectParameter("SALARY_ID", typeof(byte));
    
            var iNVESTMENT_PREFERENCE_OBJECT_IDParameter = iNVESTMENT_PREFERENCE_OBJECT_ID.HasValue ?
                new ObjectParameter("INVESTMENT_PREFERENCE_OBJECT_ID", iNVESTMENT_PREFERENCE_OBJECT_ID) :
                new ObjectParameter("INVESTMENT_PREFERENCE_OBJECT_ID", typeof(byte));
    
            var iNFO_ACQUIREMENT_IDParameter = iNFO_ACQUIREMENT_ID.HasValue ?
                new ObjectParameter("INFO_ACQUIREMENT_ID", iNFO_ACQUIREMENT_ID) :
                new ObjectParameter("INFO_ACQUIREMENT_ID", typeof(byte));
    
            var iNVESTMENT_PERIOD_IDParameter = iNVESTMENT_PERIOD_ID.HasValue ?
                new ObjectParameter("INVESTMENT_PERIOD_ID", iNVESTMENT_PERIOD_ID) :
                new ObjectParameter("INVESTMENT_PERIOD_ID", typeof(byte));
    
            var iNVESTMENT_PROPENSITY_IDParameter = iNVESTMENT_PROPENSITY_ID.HasValue ?
                new ObjectParameter("INVESTMENT_PROPENSITY_ID", iNVESTMENT_PROPENSITY_ID) :
                new ObjectParameter("INVESTMENT_PROPENSITY_ID", typeof(byte));
    
            var sTOCK_COMPANY_IDParameter = sTOCK_COMPANY_ID.HasValue ?
                new ObjectParameter("STOCK_COMPANY_ID", sTOCK_COMPANY_ID) :
                new ObjectParameter("STOCK_COMPANY_ID", typeof(byte));
    
            var iNVESTMENT_SCALE_IDParameter = iNVESTMENT_SCALE_ID.HasValue ?
                new ObjectParameter("INVESTMENT_SCALE_ID", iNVESTMENT_SCALE_ID) :
                new ObjectParameter("INVESTMENT_SCALE_ID", typeof(byte));
    
            var iNTEREST_AREAParameter = iNTEREST_AREA != null ?
                new ObjectParameter("INTEREST_AREA", iNTEREST_AREA) :
                new ObjectParameter("INTEREST_AREA", typeof(string));
    
            var cOMPANY_NAMEParameter = cOMPANY_NAME != null ?
                new ObjectParameter("COMPANY_NAME", cOMPANY_NAME) :
                new ObjectParameter("COMPANY_NAME", typeof(string));
    
            var bUSINESS_CONDITIONParameter = bUSINESS_CONDITION != null ?
                new ObjectParameter("BUSINESS_CONDITION", bUSINESS_CONDITION) :
                new ObjectParameter("BUSINESS_CONDITION", typeof(string));
    
            var bUSINESS_ITEMParameter = bUSINESS_ITEM != null ?
                new ObjectParameter("BUSINESS_ITEM", bUSINESS_ITEM) :
                new ObjectParameter("BUSINESS_ITEM", typeof(string));
    
            var bUSINESS_NUMBERParameter = bUSINESS_NUMBER != null ?
                new ObjectParameter("BUSINESS_NUMBER", bUSINESS_NUMBER) :
                new ObjectParameter("BUSINESS_NUMBER", typeof(string));
    
            var aDMIN_IDParameter = aDMIN_ID != null ?
                new ObjectParameter("ADMIN_ID", aDMIN_ID) :
                new ObjectParameter("ADMIN_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_ADMIN_MEMBER_INFO_UPDATE", uSER_NUMBERParameter, uSER_SECTIONParameter, iS_SEND_EMAILParameter, iS_SEND_SMSParameter, tEL_NOParameter, fAX_NOParameter, mOBILE_NOParameter, zIPCODEParameter, aDDRESSParameter, sALARY_IDParameter, iNVESTMENT_PREFERENCE_OBJECT_IDParameter, iNFO_ACQUIREMENT_IDParameter, iNVESTMENT_PERIOD_IDParameter, iNVESTMENT_PROPENSITY_IDParameter, sTOCK_COMPANY_IDParameter, iNVESTMENT_SCALE_IDParameter, iNTEREST_AREAParameter, cOMPANY_NAMEParameter, bUSINESS_CONDITIONParameter, bUSINESS_ITEMParameter, bUSINESS_NUMBERParameter, aDMIN_IDParameter, rETURN_NUMBER, rETURN_MESSAGE);
        }
    
        public virtual int NUP_ADMIN_MEMBER_INFO_DELETE(Nullable<int> uSER_NUMBER, ObjectParameter rETURN_NUMBER, ObjectParameter rETURN_MESSAGE)
        {
            var uSER_NUMBERParameter = uSER_NUMBER.HasValue ?
                new ObjectParameter("USER_NUMBER", uSER_NUMBER) :
                new ObjectParameter("USER_NUMBER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_ADMIN_MEMBER_INFO_DELETE", uSER_NUMBERParameter, rETURN_NUMBER, rETURN_MESSAGE);
        }
    
        public virtual int NUP_ADMIN_MEMBER_STATISTICS_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_ADMIN_MEMBER_STATISTICS_SELECT");
        }
    
        public virtual ObjectResult<NUP_MEMBER_INFO_SELECT_Result> NUP_MEMBER_INFO_SELECT(Nullable<int> uSER_NUMBER)
        {
            var uSER_NUMBERParameter = uSER_NUMBER.HasValue ?
                new ObjectParameter("USER_NUMBER", uSER_NUMBER) :
                new ObjectParameter("USER_NUMBER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_MEMBER_INFO_SELECT_Result>("Db89_wowbill.NUP_MEMBER_INFO_SELECT", uSER_NUMBERParameter);
        }
    
        public virtual int NUP_MEMBER_CREATE_GENERAL(string uSERID, string nICKNAME, string pASSWORD, string nAME, string sSNO, string tEL, string mOBILE, Nullable<byte> pASSWORDCONFIRMID, string pASSWORDCONFIRMANSWER, string eMAIL, Nullable<bool> iSSENDSMS, Nullable<bool> iSSENDSMSAD, Nullable<bool> iSSENDEMAIL, Nullable<bool> iSSENDEMAILAD, string oPTION1, string oPTION2, string sIDO, string gUGUN, string bIRTHDATE, Nullable<bool> iSSOLAR, Nullable<bool> gENDER, string dUP_INFO, string cONN_INFO, Nullable<byte> uSER_SECTION_ID, ObjectParameter rETURN_NUMBER, ObjectParameter rETURN_MESSAGE, ObjectParameter uSER_NUMBER)
        {
            var uSERIDParameter = uSERID != null ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(string));
    
            var nICKNAMEParameter = nICKNAME != null ?
                new ObjectParameter("NICKNAME", nICKNAME) :
                new ObjectParameter("NICKNAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var sSNOParameter = sSNO != null ?
                new ObjectParameter("SSNO", sSNO) :
                new ObjectParameter("SSNO", typeof(string));
    
            var tELParameter = tEL != null ?
                new ObjectParameter("TEL", tEL) :
                new ObjectParameter("TEL", typeof(string));
    
            var mOBILEParameter = mOBILE != null ?
                new ObjectParameter("MOBILE", mOBILE) :
                new ObjectParameter("MOBILE", typeof(string));
    
            var pASSWORDCONFIRMIDParameter = pASSWORDCONFIRMID.HasValue ?
                new ObjectParameter("PASSWORDCONFIRMID", pASSWORDCONFIRMID) :
                new ObjectParameter("PASSWORDCONFIRMID", typeof(byte));
    
            var pASSWORDCONFIRMANSWERParameter = pASSWORDCONFIRMANSWER != null ?
                new ObjectParameter("PASSWORDCONFIRMANSWER", pASSWORDCONFIRMANSWER) :
                new ObjectParameter("PASSWORDCONFIRMANSWER", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var iSSENDSMSParameter = iSSENDSMS.HasValue ?
                new ObjectParameter("ISSENDSMS", iSSENDSMS) :
                new ObjectParameter("ISSENDSMS", typeof(bool));
    
            var iSSENDSMSADParameter = iSSENDSMSAD.HasValue ?
                new ObjectParameter("ISSENDSMSAD", iSSENDSMSAD) :
                new ObjectParameter("ISSENDSMSAD", typeof(bool));
    
            var iSSENDEMAILParameter = iSSENDEMAIL.HasValue ?
                new ObjectParameter("ISSENDEMAIL", iSSENDEMAIL) :
                new ObjectParameter("ISSENDEMAIL", typeof(bool));
    
            var iSSENDEMAILADParameter = iSSENDEMAILAD.HasValue ?
                new ObjectParameter("ISSENDEMAILAD", iSSENDEMAILAD) :
                new ObjectParameter("ISSENDEMAILAD", typeof(bool));
    
            var oPTION1Parameter = oPTION1 != null ?
                new ObjectParameter("OPTION1", oPTION1) :
                new ObjectParameter("OPTION1", typeof(string));
    
            var oPTION2Parameter = oPTION2 != null ?
                new ObjectParameter("OPTION2", oPTION2) :
                new ObjectParameter("OPTION2", typeof(string));
    
            var sIDOParameter = sIDO != null ?
                new ObjectParameter("SIDO", sIDO) :
                new ObjectParameter("SIDO", typeof(string));
    
            var gUGUNParameter = gUGUN != null ?
                new ObjectParameter("GUGUN", gUGUN) :
                new ObjectParameter("GUGUN", typeof(string));
    
            var bIRTHDATEParameter = bIRTHDATE != null ?
                new ObjectParameter("BIRTHDATE", bIRTHDATE) :
                new ObjectParameter("BIRTHDATE", typeof(string));
    
            var iSSOLARParameter = iSSOLAR.HasValue ?
                new ObjectParameter("ISSOLAR", iSSOLAR) :
                new ObjectParameter("ISSOLAR", typeof(bool));
    
            var gENDERParameter = gENDER.HasValue ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(bool));
    
            var dUP_INFOParameter = dUP_INFO != null ?
                new ObjectParameter("DUP_INFO", dUP_INFO) :
                new ObjectParameter("DUP_INFO", typeof(string));
    
            var cONN_INFOParameter = cONN_INFO != null ?
                new ObjectParameter("CONN_INFO", cONN_INFO) :
                new ObjectParameter("CONN_INFO", typeof(string));
    
            var uSER_SECTION_IDParameter = uSER_SECTION_ID.HasValue ?
                new ObjectParameter("USER_SECTION_ID", uSER_SECTION_ID) :
                new ObjectParameter("USER_SECTION_ID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_MEMBER_CREATE_GENERAL", uSERIDParameter, nICKNAMEParameter, pASSWORDParameter, nAMEParameter, sSNOParameter, tELParameter, mOBILEParameter, pASSWORDCONFIRMIDParameter, pASSWORDCONFIRMANSWERParameter, eMAILParameter, iSSENDSMSParameter, iSSENDSMSADParameter, iSSENDEMAILParameter, iSSENDEMAILADParameter, oPTION1Parameter, oPTION2Parameter, sIDOParameter, gUGUNParameter, bIRTHDATEParameter, iSSOLARParameter, gENDERParameter, dUP_INFOParameter, cONN_INFOParameter, uSER_SECTION_IDParameter, rETURN_NUMBER, rETURN_MESSAGE, uSER_NUMBER);
        }
    
        public virtual int NUP_MEMBER_UPDATE_GENERAL(Nullable<int> uSERNUMBER, string nICKNAME, string tEL, string mOBILE, string eMAIL, string iSSENDSMS, Nullable<bool> iSSENDEMAIL, string sIDO, string gUGUN, string zIPCODE, string aDDRESS, Nullable<byte> sALARY_ID, Nullable<byte> iNVESTMENT_PERIOD_ID, Nullable<byte> iNVESTMENT_SCALE_ID, Nullable<byte> iNVESTMENT_PROPENSITY_ID, Nullable<byte> iNVESTMENT_PREFERENCE_OBJECT_ID, Nullable<byte> sTOCK_COMPANY_ID, Nullable<byte> iNFO_ACQUIREMENT_ID, string iNTEREST_AREA, Nullable<byte> jOB_ID, Nullable<byte> rEGIST_ROUTE_ID, ObjectParameter rETURN_NUMBER, ObjectParameter rETURN_MESSAGE)
        {
            var uSERNUMBERParameter = uSERNUMBER.HasValue ?
                new ObjectParameter("USERNUMBER", uSERNUMBER) :
                new ObjectParameter("USERNUMBER", typeof(int));
    
            var nICKNAMEParameter = nICKNAME != null ?
                new ObjectParameter("NICKNAME", nICKNAME) :
                new ObjectParameter("NICKNAME", typeof(string));
    
            var tELParameter = tEL != null ?
                new ObjectParameter("TEL", tEL) :
                new ObjectParameter("TEL", typeof(string));
    
            var mOBILEParameter = mOBILE != null ?
                new ObjectParameter("MOBILE", mOBILE) :
                new ObjectParameter("MOBILE", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var iSSENDSMSParameter = iSSENDSMS != null ?
                new ObjectParameter("ISSENDSMS", iSSENDSMS) :
                new ObjectParameter("ISSENDSMS", typeof(string));
    
            var iSSENDEMAILParameter = iSSENDEMAIL.HasValue ?
                new ObjectParameter("ISSENDEMAIL", iSSENDEMAIL) :
                new ObjectParameter("ISSENDEMAIL", typeof(bool));
    
            var sIDOParameter = sIDO != null ?
                new ObjectParameter("SIDO", sIDO) :
                new ObjectParameter("SIDO", typeof(string));
    
            var gUGUNParameter = gUGUN != null ?
                new ObjectParameter("GUGUN", gUGUN) :
                new ObjectParameter("GUGUN", typeof(string));
    
            var zIPCODEParameter = zIPCODE != null ?
                new ObjectParameter("ZIPCODE", zIPCODE) :
                new ObjectParameter("ZIPCODE", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var sALARY_IDParameter = sALARY_ID.HasValue ?
                new ObjectParameter("SALARY_ID", sALARY_ID) :
                new ObjectParameter("SALARY_ID", typeof(byte));
    
            var iNVESTMENT_PERIOD_IDParameter = iNVESTMENT_PERIOD_ID.HasValue ?
                new ObjectParameter("INVESTMENT_PERIOD_ID", iNVESTMENT_PERIOD_ID) :
                new ObjectParameter("INVESTMENT_PERIOD_ID", typeof(byte));
    
            var iNVESTMENT_SCALE_IDParameter = iNVESTMENT_SCALE_ID.HasValue ?
                new ObjectParameter("INVESTMENT_SCALE_ID", iNVESTMENT_SCALE_ID) :
                new ObjectParameter("INVESTMENT_SCALE_ID", typeof(byte));
    
            var iNVESTMENT_PROPENSITY_IDParameter = iNVESTMENT_PROPENSITY_ID.HasValue ?
                new ObjectParameter("INVESTMENT_PROPENSITY_ID", iNVESTMENT_PROPENSITY_ID) :
                new ObjectParameter("INVESTMENT_PROPENSITY_ID", typeof(byte));
    
            var iNVESTMENT_PREFERENCE_OBJECT_IDParameter = iNVESTMENT_PREFERENCE_OBJECT_ID.HasValue ?
                new ObjectParameter("INVESTMENT_PREFERENCE_OBJECT_ID", iNVESTMENT_PREFERENCE_OBJECT_ID) :
                new ObjectParameter("INVESTMENT_PREFERENCE_OBJECT_ID", typeof(byte));
    
            var sTOCK_COMPANY_IDParameter = sTOCK_COMPANY_ID.HasValue ?
                new ObjectParameter("STOCK_COMPANY_ID", sTOCK_COMPANY_ID) :
                new ObjectParameter("STOCK_COMPANY_ID", typeof(byte));
    
            var iNFO_ACQUIREMENT_IDParameter = iNFO_ACQUIREMENT_ID.HasValue ?
                new ObjectParameter("INFO_ACQUIREMENT_ID", iNFO_ACQUIREMENT_ID) :
                new ObjectParameter("INFO_ACQUIREMENT_ID", typeof(byte));
    
            var iNTEREST_AREAParameter = iNTEREST_AREA != null ?
                new ObjectParameter("INTEREST_AREA", iNTEREST_AREA) :
                new ObjectParameter("INTEREST_AREA", typeof(string));
    
            var jOB_IDParameter = jOB_ID.HasValue ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(byte));
    
            var rEGIST_ROUTE_IDParameter = rEGIST_ROUTE_ID.HasValue ?
                new ObjectParameter("REGIST_ROUTE_ID", rEGIST_ROUTE_ID) :
                new ObjectParameter("REGIST_ROUTE_ID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_MEMBER_UPDATE_GENERAL", uSERNUMBERParameter, nICKNAMEParameter, tELParameter, mOBILEParameter, eMAILParameter, iSSENDSMSParameter, iSSENDEMAILParameter, sIDOParameter, gUGUNParameter, zIPCODEParameter, aDDRESSParameter, sALARY_IDParameter, iNVESTMENT_PERIOD_IDParameter, iNVESTMENT_SCALE_IDParameter, iNVESTMENT_PROPENSITY_IDParameter, iNVESTMENT_PREFERENCE_OBJECT_IDParameter, sTOCK_COMPANY_IDParameter, iNFO_ACQUIREMENT_IDParameter, iNTEREST_AREAParameter, jOB_IDParameter, rEGIST_ROUTE_IDParameter, rETURN_NUMBER, rETURN_MESSAGE);
        }
    
        public virtual ObjectResult<NUP_RecruitData_Result> NUP_RecruitData(string name, string ssno, string img)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var ssnoParameter = ssno != null ?
                new ObjectParameter("ssno", ssno) :
                new ObjectParameter("ssno", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_RecruitData_Result>("Db89_wowbill.NUP_RecruitData", nameParameter, ssnoParameter, imgParameter);
        }
    
        public virtual ObjectResult<NUP_MEMBER_INFO_SELECT_COMPANY_Result> NUP_MEMBER_INFO_SELECT_COMPANY(Nullable<int> uSER_NUMBER)
        {
            var uSER_NUMBERParameter = uSER_NUMBER.HasValue ?
                new ObjectParameter("USER_NUMBER", uSER_NUMBER) :
                new ObjectParameter("USER_NUMBER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_MEMBER_INFO_SELECT_COMPANY_Result>("Db89_wowbill.NUP_MEMBER_INFO_SELECT_COMPANY", uSER_NUMBERParameter);
        }
    
        public virtual ObjectResult<NUP_MEMBER_INFO_SELECT_GENERAL_Result> NUP_MEMBER_INFO_SELECT_GENERAL(Nullable<int> uSER_NUMBER)
        {
            var uSER_NUMBERParameter = uSER_NUMBER.HasValue ?
                new ObjectParameter("USER_NUMBER", uSER_NUMBER) :
                new ObjectParameter("USER_NUMBER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_MEMBER_INFO_SELECT_GENERAL_Result>("Db89_wowbill.NUP_MEMBER_INFO_SELECT_GENERAL", uSER_NUMBERParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_GetMYCancelPoint(string usernumber, string registDt)
        {
            var usernumberParameter = usernumber != null ?
                new ObjectParameter("usernumber", usernumber) :
                new ObjectParameter("usernumber", typeof(string));
    
            var registDtParameter = registDt != null ?
                new ObjectParameter("registDt", registDt) :
                new ObjectParameter("registDt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Db89_wowbill.USP_GetMYCancelPoint", usernumberParameter, registDtParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_GetMYCancelPointCash(string usernumber, string registDt)
        {
            var usernumberParameter = usernumber != null ?
                new ObjectParameter("usernumber", usernumber) :
                new ObjectParameter("usernumber", typeof(string));
    
            var registDtParameter = registDt != null ?
                new ObjectParameter("registDt", registDt) :
                new ObjectParameter("registDt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Db89_wowbill.USP_GetMYCancelPointCash", usernumberParameter, registDtParameter);
        }
    
        public virtual ObjectResult<USP_GetMYCurrentCash_Result> USP_GetMYCurrentCash(string usernumber)
        {
            var usernumberParameter = usernumber != null ?
                new ObjectParameter("usernumber", usernumber) :
                new ObjectParameter("usernumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetMYCurrentCash_Result>("Db89_wowbill.USP_GetMYCurrentCash", usernumberParameter);
        }
    
        public virtual ObjectResult<NUP_RECRUIT_SELECT_Result> NUP_RECRUIT_SELECT(string nAME, string sSNO, Nullable<int> sEQ, Nullable<int> pAGE_SIZE, Nullable<int> pAGE, string pASSWORD)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var sSNOParameter = sSNO != null ?
                new ObjectParameter("SSNO", sSNO) :
                new ObjectParameter("SSNO", typeof(string));
    
            var sEQParameter = sEQ.HasValue ?
                new ObjectParameter("SEQ", sEQ) :
                new ObjectParameter("SEQ", typeof(int));
    
            var pAGE_SIZEParameter = pAGE_SIZE.HasValue ?
                new ObjectParameter("PAGE_SIZE", pAGE_SIZE) :
                new ObjectParameter("PAGE_SIZE", typeof(int));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_RECRUIT_SELECT_Result>("Db89_wowbill.NUP_RECRUIT_SELECT", nAMEParameter, sSNOParameter, sEQParameter, pAGE_SIZEParameter, pAGEParameter, pASSWORDParameter);
        }
    
        public virtual int NUP_RECRUIT_INSERT(string tYPE, string nAME, string sSNO, string iMG, string jOB, string pASSWORD, string aGREEMENT, Nullable<int> mAXNO)
        {
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var sSNOParameter = sSNO != null ?
                new ObjectParameter("SSNO", sSNO) :
                new ObjectParameter("SSNO", typeof(string));
    
            var iMGParameter = iMG != null ?
                new ObjectParameter("IMG", iMG) :
                new ObjectParameter("IMG", typeof(string));
    
            var jOBParameter = jOB != null ?
                new ObjectParameter("JOB", jOB) :
                new ObjectParameter("JOB", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var aGREEMENTParameter = aGREEMENT != null ?
                new ObjectParameter("AGREEMENT", aGREEMENT) :
                new ObjectParameter("AGREEMENT", typeof(string));
    
            var mAXNOParameter = mAXNO.HasValue ?
                new ObjectParameter("MAXNO", mAXNO) :
                new ObjectParameter("MAXNO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_RECRUIT_INSERT", tYPEParameter, nAMEParameter, sSNOParameter, iMGParameter, jOBParameter, pASSWORDParameter, aGREEMENTParameter, mAXNOParameter);
        }
    
        public virtual ObjectResult<NUP_ADMIN_MEMBER_STATISTICS_SELECT1_Result> NUP_ADMIN_MEMBER_STATISTICS_SELECT1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_ADMIN_MEMBER_STATISTICS_SELECT1_Result>("Db89_wowbill.NUP_ADMIN_MEMBER_STATISTICS_SELECT1");
        }
    
        public virtual int NUP_MEMBER_UPDATE(Nullable<int> uSERNUMBER, string uSERNAME, string nICKNAME, string tEL, string mOBILE, string eMAIL, string iSSENDSMS, Nullable<bool> iSSENDEMAIL, string sIDO, string gUGUN, string zIPCODE, string aDDRESS, Nullable<byte> sALARY_ID, Nullable<byte> iNVESTMENT_PERIOD_ID, Nullable<byte> iNVESTMENT_SCALE_ID, Nullable<byte> iNVESTMENT_PROPENSITY_ID, Nullable<byte> iNVESTMENT_PREFERENCE_OBJECT_ID, Nullable<byte> sTOCK_COMPANY_ID, Nullable<byte> iNFO_ACQUIREMENT_ID, string iNTEREST_AREA, Nullable<byte> jOB_ID, Nullable<byte> rEGIST_ROUTE_ID, string bUSINESS_CONDITION, string bUSINESS_ITEM, string cOMPANY_NO, string cEO_NAME, Nullable<bool> lISTED, ObjectParameter rETURN_NUMBER, ObjectParameter rETURN_MESSAGE)
        {
            var uSERNUMBERParameter = uSERNUMBER.HasValue ?
                new ObjectParameter("USERNUMBER", uSERNUMBER) :
                new ObjectParameter("USERNUMBER", typeof(int));
    
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            var nICKNAMEParameter = nICKNAME != null ?
                new ObjectParameter("NICKNAME", nICKNAME) :
                new ObjectParameter("NICKNAME", typeof(string));
    
            var tELParameter = tEL != null ?
                new ObjectParameter("TEL", tEL) :
                new ObjectParameter("TEL", typeof(string));
    
            var mOBILEParameter = mOBILE != null ?
                new ObjectParameter("MOBILE", mOBILE) :
                new ObjectParameter("MOBILE", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var iSSENDSMSParameter = iSSENDSMS != null ?
                new ObjectParameter("ISSENDSMS", iSSENDSMS) :
                new ObjectParameter("ISSENDSMS", typeof(string));
    
            var iSSENDEMAILParameter = iSSENDEMAIL.HasValue ?
                new ObjectParameter("ISSENDEMAIL", iSSENDEMAIL) :
                new ObjectParameter("ISSENDEMAIL", typeof(bool));
    
            var sIDOParameter = sIDO != null ?
                new ObjectParameter("SIDO", sIDO) :
                new ObjectParameter("SIDO", typeof(string));
    
            var gUGUNParameter = gUGUN != null ?
                new ObjectParameter("GUGUN", gUGUN) :
                new ObjectParameter("GUGUN", typeof(string));
    
            var zIPCODEParameter = zIPCODE != null ?
                new ObjectParameter("ZIPCODE", zIPCODE) :
                new ObjectParameter("ZIPCODE", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var sALARY_IDParameter = sALARY_ID.HasValue ?
                new ObjectParameter("SALARY_ID", sALARY_ID) :
                new ObjectParameter("SALARY_ID", typeof(byte));
    
            var iNVESTMENT_PERIOD_IDParameter = iNVESTMENT_PERIOD_ID.HasValue ?
                new ObjectParameter("INVESTMENT_PERIOD_ID", iNVESTMENT_PERIOD_ID) :
                new ObjectParameter("INVESTMENT_PERIOD_ID", typeof(byte));
    
            var iNVESTMENT_SCALE_IDParameter = iNVESTMENT_SCALE_ID.HasValue ?
                new ObjectParameter("INVESTMENT_SCALE_ID", iNVESTMENT_SCALE_ID) :
                new ObjectParameter("INVESTMENT_SCALE_ID", typeof(byte));
    
            var iNVESTMENT_PROPENSITY_IDParameter = iNVESTMENT_PROPENSITY_ID.HasValue ?
                new ObjectParameter("INVESTMENT_PROPENSITY_ID", iNVESTMENT_PROPENSITY_ID) :
                new ObjectParameter("INVESTMENT_PROPENSITY_ID", typeof(byte));
    
            var iNVESTMENT_PREFERENCE_OBJECT_IDParameter = iNVESTMENT_PREFERENCE_OBJECT_ID.HasValue ?
                new ObjectParameter("INVESTMENT_PREFERENCE_OBJECT_ID", iNVESTMENT_PREFERENCE_OBJECT_ID) :
                new ObjectParameter("INVESTMENT_PREFERENCE_OBJECT_ID", typeof(byte));
    
            var sTOCK_COMPANY_IDParameter = sTOCK_COMPANY_ID.HasValue ?
                new ObjectParameter("STOCK_COMPANY_ID", sTOCK_COMPANY_ID) :
                new ObjectParameter("STOCK_COMPANY_ID", typeof(byte));
    
            var iNFO_ACQUIREMENT_IDParameter = iNFO_ACQUIREMENT_ID.HasValue ?
                new ObjectParameter("INFO_ACQUIREMENT_ID", iNFO_ACQUIREMENT_ID) :
                new ObjectParameter("INFO_ACQUIREMENT_ID", typeof(byte));
    
            var iNTEREST_AREAParameter = iNTEREST_AREA != null ?
                new ObjectParameter("INTEREST_AREA", iNTEREST_AREA) :
                new ObjectParameter("INTEREST_AREA", typeof(string));
    
            var jOB_IDParameter = jOB_ID.HasValue ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(byte));
    
            var rEGIST_ROUTE_IDParameter = rEGIST_ROUTE_ID.HasValue ?
                new ObjectParameter("REGIST_ROUTE_ID", rEGIST_ROUTE_ID) :
                new ObjectParameter("REGIST_ROUTE_ID", typeof(byte));
    
            var bUSINESS_CONDITIONParameter = bUSINESS_CONDITION != null ?
                new ObjectParameter("BUSINESS_CONDITION", bUSINESS_CONDITION) :
                new ObjectParameter("BUSINESS_CONDITION", typeof(string));
    
            var bUSINESS_ITEMParameter = bUSINESS_ITEM != null ?
                new ObjectParameter("BUSINESS_ITEM", bUSINESS_ITEM) :
                new ObjectParameter("BUSINESS_ITEM", typeof(string));
    
            var cOMPANY_NOParameter = cOMPANY_NO != null ?
                new ObjectParameter("COMPANY_NO", cOMPANY_NO) :
                new ObjectParameter("COMPANY_NO", typeof(string));
    
            var cEO_NAMEParameter = cEO_NAME != null ?
                new ObjectParameter("CEO_NAME", cEO_NAME) :
                new ObjectParameter("CEO_NAME", typeof(string));
    
            var lISTEDParameter = lISTED.HasValue ?
                new ObjectParameter("LISTED", lISTED) :
                new ObjectParameter("LISTED", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_MEMBER_UPDATE", uSERNUMBERParameter, uSERNAMEParameter, nICKNAMEParameter, tELParameter, mOBILEParameter, eMAILParameter, iSSENDSMSParameter, iSSENDEMAILParameter, sIDOParameter, gUGUNParameter, zIPCODEParameter, aDDRESSParameter, sALARY_IDParameter, iNVESTMENT_PERIOD_IDParameter, iNVESTMENT_SCALE_IDParameter, iNVESTMENT_PROPENSITY_IDParameter, iNVESTMENT_PREFERENCE_OBJECT_IDParameter, sTOCK_COMPANY_IDParameter, iNFO_ACQUIREMENT_IDParameter, iNTEREST_AREAParameter, jOB_IDParameter, rEGIST_ROUTE_IDParameter, bUSINESS_CONDITIONParameter, bUSINESS_ITEMParameter, cOMPANY_NOParameter, cEO_NAMEParameter, lISTEDParameter, rETURN_NUMBER, rETURN_MESSAGE);
        }
    
        public virtual int NUP_MEMBER_TV_VOD_CRM_LOG_INSERT(string dEP, Nullable<int> vODNUM, string bROADDATE, string pROGRAMNAME, Nullable<int> uSERNUMBER, string uSERID, string eNTERROUTE)
        {
            var dEPParameter = dEP != null ?
                new ObjectParameter("DEP", dEP) :
                new ObjectParameter("DEP", typeof(string));
    
            var vODNUMParameter = vODNUM.HasValue ?
                new ObjectParameter("VODNUM", vODNUM) :
                new ObjectParameter("VODNUM", typeof(int));
    
            var bROADDATEParameter = bROADDATE != null ?
                new ObjectParameter("BROADDATE", bROADDATE) :
                new ObjectParameter("BROADDATE", typeof(string));
    
            var pROGRAMNAMEParameter = pROGRAMNAME != null ?
                new ObjectParameter("PROGRAMNAME", pROGRAMNAME) :
                new ObjectParameter("PROGRAMNAME", typeof(string));
    
            var uSERNUMBERParameter = uSERNUMBER.HasValue ?
                new ObjectParameter("USERNUMBER", uSERNUMBER) :
                new ObjectParameter("USERNUMBER", typeof(int));
    
            var uSERIDParameter = uSERID != null ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(string));
    
            var eNTERROUTEParameter = eNTERROUTE != null ?
                new ObjectParameter("ENTERROUTE", eNTERROUTE) :
                new ObjectParameter("ENTERROUTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Db89_wowbill.NUP_MEMBER_TV_VOD_CRM_LOG_INSERT", dEPParameter, vODNUMParameter, bROADDATEParameter, pROGRAMNAMEParameter, uSERNUMBERParameter, uSERIDParameter, eNTERROUTEParameter);
        }
    
        public virtual ObjectResult<NUP_ADMIN_MEMBER_INFO_HISTORY_SELECT_Result> NUP_ADMIN_MEMBER_INFO_HISTORY_SELECT(Nullable<int> uSER_NUMBER)
        {
            var uSER_NUMBERParameter = uSER_NUMBER.HasValue ?
                new ObjectParameter("USER_NUMBER", uSER_NUMBER) :
                new ObjectParameter("USER_NUMBER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NUP_ADMIN_MEMBER_INFO_HISTORY_SELECT_Result>("Db89_wowbill.NUP_ADMIN_MEMBER_INFO_HISTORY_SELECT", uSER_NUMBERParameter);
        }
    }
}
