//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db89.wowbill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyDetail
    {
        public int companyDetailId { get; set; }
        public string businessNumber { get; set; }
        public string ceoName { get; set; }
        public string businessItem { get; set; }
        public string businessCondition { get; set; }
        public string businessCategory { get; set; }
        public string corporationNumber { get; set; }
        public bool listed { get; set; }
        public string establishmentAnniversary { get; set; }
        public System.DateTime registDt { get; set; }
        public string adminId { get; set; }
        public bool apply { get; set; }
    }
}
