//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db89.wowbill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int transactionId { get; set; }
        public byte transactionCode { get; set; }
        public int userNumber { get; set; }
        public int wowCashBalance { get; set; }
        public int pointToWowCashBalance { get; set; }
        public int pointBalance { get; set; }
        public int wowCashAmount { get; set; }
        public int pointToWowCashAmount { get; set; }
        public int pointAmount { get; set; }
        public System.DateTime registDt { get; set; }
    
        public virtual tblCodeTransactionType tblCodeTransactionType { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
