//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Middle.Model.Db89.wowbill
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserDetail
    {
        public int userNumber { get; set; }
        public Nullable<bool> isSolar { get; set; }
        public string birthday { get; set; }
        public string zipcode { get; set; }
        public string address { get; set; }
        public string handphone { get; set; }
        public string companyName { get; set; }
        public string companyDepartmentName { get; set; }
        public string companyZipcode { get; set; }
        public string companyAddress { get; set; }
        public string companyTel { get; set; }
        public Nullable<byte> jobId { get; set; }
        public string homepageUrl { get; set; }
        public Nullable<byte> registRouteId { get; set; }
        public Nullable<byte> statusChangeReasonId { get; set; }
        public Nullable<byte> salaryId { get; set; }
        public Nullable<byte> investmentPeriodId { get; set; }
        public Nullable<byte> investmentScaleId { get; set; }
        public Nullable<byte> investmentPropensityId { get; set; }
        public Nullable<byte> investmentPreferenceObjectId { get; set; }
        public Nullable<byte> stockCompanyId { get; set; }
        public Nullable<byte> infoAcquirementId { get; set; }
        public string interestItemId1 { get; set; }
        public string interestItemId2 { get; set; }
        public string interestItemId3 { get; set; }
        public Nullable<byte> hobbyId { get; set; }
        public string weddingAnniversary { get; set; }
        public Nullable<byte> residingStatusId { get; set; }
        public System.DateTime registDt { get; set; }
        public string adminId { get; set; }
        public bool apply { get; set; }
        public string interestArea { get; set; }
    
        public virtual tblCodeHobby tblCodeHobby { get; set; }
        public virtual tblCodeInfoAcquirement tblCodeInfoAcquirement { get; set; }
        public virtual tblCodeInterestItem tblCodeInterestItem { get; set; }
        public virtual tblCodeInterestItem tblCodeInterestItem1 { get; set; }
        public virtual tblCodeInterestItem tblCodeInterestItem2 { get; set; }
        public virtual tblCodeInvestmentPeriod tblCodeInvestmentPeriod { get; set; }
        public virtual tblCodeInvestmentPreferenceObject tblCodeInvestmentPreferenceObject { get; set; }
        public virtual tblCodeInvestmentPropensity tblCodeInvestmentPropensity { get; set; }
        public virtual tblCodeInvestmentScale tblCodeInvestmentScale { get; set; }
        public virtual tblCodeJob tblCodeJob { get; set; }
        public virtual tblCodeResidingStatus tblCodeResidingStatus { get; set; }
        public virtual tblCodeSalary tblCodeSalary { get; set; }
        public virtual tblCodeStockCompany tblCodeStockCompany { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblCodeRegistRoute tblCodeRegistRoute { get; set; }
    }
}
